### ISSUE TITLE
WASM gifsicle

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#10]
https://github.com/kohler/gifsicle

**Comment by RobbyCowell** [comment]
Gif support would be amazing!

**Comment by surma** [comment]
Gifs are mostly used for animations nowadays (even though they shouldn’t), so we probably won’t add special codecs for it.

**Comment by alexander-akait** [comment]
@surma `gifsicle` will be used not only for animation, it is still used on legacy sites and will be good to compress them too, also animation gifs can be compressed too

**Comment by joelanman** [comment]
In Safari, I get a compression option for 'Browser Gif' which I don't get in Chrome

**Comment by jakearchibald** [comment]
Yeah, Safari has more compression formats built in. I'm not sure how useful it is, but figured we'd expose it anyway.

**Comment by Airkro** [comment]
There is [@wasm-codecs/gifsicle](https://github.com/cyrilwanner/wasm-codecs/blob/master/packages/gifsicle), but ...

**Comment by renzhezhilu** [comment]
hey guys
I'm done [gifsicle-wasm-browser](https://github.com/renzhezhilu/gifsicle-wasm-browser)

<img src="https://cdn.jsdelivr.net/gh/renzhezhilu/gifsicle-wasm-browser@master/demo/ui.jpg" >
