### ISSUE TITLE
Question: AVIF compression settings for lossless?

### ISSUE THREAD

**Issue by tomByrer** [GoogleChromeLabs/squoosh#1005]
Good news!  Squoosh.app is the only AVIF encoder that I can find with [truly lossless](https://github.com/lovell/sharp/issues/2696)! 
How do you do this? (settings, or don't compress & just use HEIF container?)

TIA

**Comment by jakearchibald** [comment]
Here's where we interact with avif https://github.com/GoogleChromeLabs/squoosh/blob/dev/codecs/avif/enc/avif_enc.cpp. The lossless settings are in there.
