### ISSUE TITLE
squoosh-cli bus-errors on mac M1 mac book pro

### ISSUE THREAD

**Issue by andystevenson** [GoogleChromeLabs/squoosh#1010]
running squoosh-cli on M1 (Apple Silicon) bus errors when trying to compress any jpeg file (I haven't tried it on other formats)

**To Reproduce**
1. npm i -g @squoosh/cli
2. squoosh-cli --mozjpeg auto 1.jpg
3. After a few seconds....
4. zsh: bus error  squoosh-cli --mozjpeg auto 1.jp
<img width="596" alt="image" src="https://user-images.githubusercontent.com/1989620/117572202-ac443b80-b0c9-11eb-861d-72a058233616.png">

**Expected behavior**
Not to crash

**Version:**
 - OS w/ version: macOS Big Sur 11.3.1
 - Node version: v16.0.0
 - npm version: 7.10.0

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
![1](https://user-images.githubusercontent.com/1989620/117572379-88352a00-b0ca-11eb-98fd-2dbb4cc7385d.jpg)

**Comment by trm217** [comment]
Perhaps this issue has the same underlying problem as this [issue](https://github.com/vercel/next.js/issues/24421) opened on the next.js repository.
Running next.js with arm native Node Version 16 causes segmentation faults when trying to compress images using the squoosh library.

**Comment by surma** [comment]
I just published `@squoosh/lib` v0.3.0 which has a rebuild of all our codecs. I just tested it on my M1 with Node 16 and it worked. Can you give it another try?

I’ll close this bug, but please re-open if it’s still breaking for you!

**Comment by naisanzaa** [comment]
> I just published `@squoosh/lib` v0.3.0 which has a rebuild of all our codecs. I just tested it on my M1 with Node 16 and it worked. Can you give it another try?
> 
> I’ll close this bug, but please re-open if it’s still breaking for you!

I seem to be having a bus error on M1 still
