### ISSUE TITLE
[CLI] Limit the number of decoded images in memory

### ISSUE THREAD

**Issue by illycz** [GoogleChromeLabs/squoosh#1012]
I'm trying edit folder with approx 200 images within `npx @squoosh/cli --mozjpeg '{"quality":80}' -d . ./*.jpg` and get memory error:
`1.54MBRangeError: WebAssembly.Memory(): could not allocate memory
    at /Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:176011
    at instantiateEmscriptenWasm (/Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:153532)
    at Object.dec (/Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:378727)
    at decodeFile (/Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:520969)
    at async MessagePort.<anonymous> (/Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:493320)
Worker error:  Error [RuntimeError]: abort(RangeError: WebAssembly.Memory(): could not allocate memory). Build with -s ASSERTIONS=1 for more info.`

Terminal blinking and process never ending.

Thanks

**Comment by illycz** [comment]
Few images working as expected...

**Comment by user69nice** [comment]
> I'm trying edit folder with approx 200 images within `npx @squoosh/cli --mozjpeg '{"quality":80}' -d . ./*.jpg` and get memory error:
> `1.54MBRangeError: WebAssembly.Memory(): could not allocate memory at /Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:176011 at instantiateEmscriptenWasm (/Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:153532) at Object.dec (/Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:378727) at decodeFile (/Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:520969) at async MessagePort.<anonymous> (/Users/illy/.npm/npx/83877/lib/nodemodules/@squoosh/cli/build/index.js:7:493320) Worker error: Error [RuntimeError]: abort(RangeError: WebAssembly.Memory(): could not allocate memory). Build with -s ASSERTIONS=1 for more info.`
> 
> Terminal blinking and process never ending.
> 
> Thanks

Had the same error popping up on CLI WebAssembly.Memory(): could not allocate memory at...

Thought maybe it's my setup/system but after trying it on Windows and Linux and also updating everything possible the error was still popping up.

Squoosh stops after trying to decode about 50 to 60 images and leaves terminal blinking.

Can provide logs and more specific information if necessary but the error and steps leading to that error looked very similar to OP's.

**Comment by RReverser** [comment]
CLI should probably limit parallel execution by number of cores. /cc @surma

**Comment by a-was** [comment]
Same here.
It looks like squoosh firstly loads all images to memory and then starts processing them. I tried to squoosh about 300 images, but had to do it partially, about 30 images at a time. 
My suggestion is squoosh should load and process images one by one (maybe more, by 3 or 5?)

**Comment by surma** [comment]
> It looks like squoosh firstly loads all images to memory and then starts processing them. I tried to squoosh about 300 images, but had to do it partially, about 30 images at a time.
> My suggestion is squoosh should load and process images one by one (maybe more, by 3 or 5?)

This might very well be a problem. Your solution sounds good, in that we should not decode everything, and then compress everything, but stagger it a bit.

If anyone wants to take up this issue, the CLI is now a lot simple to contribute to (thanks @atjn!).

**Comment by atjn** [comment]
> My suggestion is squoosh should load and process images one by one (maybe more, by 3 or 5?)

In case it helps anyone get started, I do this exact thing in my project and it eliminated many of the weird bugs I was encountering with Squoosh. I use [tiny-async-pool](https://www.npmjs.com/package/tiny-async-pool) for the heavy lifting, and can recommend it, but I don't know if @surma is okay with adding another dependency.

I wrote this script to decide how many images should be processed simultaneously:
```js
// import os from "os"

const imageThreads = Math.round(
  Math.max(
    Math.min(
      os.freemem() / 8000,
      os.cpus().length / 2,
    ),
    1,
  ),
);
```
It's probably too conservative, but stability is more important for my use case. It would be interesting to see this being tweaked for a more balanced use case.

**Comment by surma** [comment]
Async pool seems small and good enough. Not sure if it’s necessary, but whoever takes this on, is welcome to use it.

**Comment by jcao219** [comment]
Another good option for controlling the amount of concurrrency when dealing with lots of tasks as promises would be https://www.npmjs.com/package/p-map

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
