### ISSUE TITLE
wasm-bindgen-rayon broke a few codecs

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#1015]
Seems that `importScripts` is broken on:

- WebPv2
- AVIF
- JPEG-XL

I guess it's the c++ codecs that use threads.

I've rolled live back.

**Comment by RReverser** [comment]
Working on this, seems to be an issue with how dynamic import works with full URL that Emscripten uses instead of AMD ID Rollup normally emits.
