### ISSUE TITLE
Onpaste: Issues when input has focus

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#102]
1. Select image using file picker.
1. Paste new image.

Pasting fails.

1. Open image (any mechanism)
1. Adjust quality.
1. Paste new image.

Pasting fails.

In both cases this fails because an `<input>` has focus, which swallows the paste. This is especially problematic since it's difficult to unfocus the input. Clicking on the canvas doesn't change focus as the mouse events are captured.

We either need to make it easier to unfocus inputs, or capture the paste even when non-text inputs are focused.

**Comment by 1valdis** [comment]
This is still an issue. I opened Squoosh and tried to paste, but nothing happened, so I went here, started creating a feature request obviously thinking it's not implemented, and then saw this. I doubt many people tap on some places of the page before trying to paste - and if I just open Squoosh and my first action is pasting, it fails.

**Comment by kosamari** [comment]
I believe this is fixed in V2.
