### ISSUE TITLE
Make use of SIMD

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#1026]
SIMD was disabled in https://github.com/GoogleChromeLabs/squoosh/pull/1025.

We should fix it when the new format gets a little more stable.

**Comment by surma** [comment]
It is (now) stable 😅  We just need to recompile our codecs with a recent Emscripten. Upgrading the Emscripten in our build image is blocked on a subsequent bug that @RReverser is working on.

**Comment by Ayan-web** [comment]
can I contribute to this issue. this will be my first PR. 
where should start from 
thank you

**Comment by RReverser** [comment]
I believe this issue was about re-enabling SIMD, and that was actually done a while ago now, so I'm going to go ahead and close it.
