### ISSUE TITLE
Images are larger after optimization by using the cli tool

### ISSUE THREAD

**Issue by axelf** [GoogleChromeLabs/squoosh#1036]
**Describe the bug**
Images are larger than before after running the cli

**To Reproduce**
1. `npx @squoosh/cli --oxipng '{}' ./original/img/*.png -d ./optimized/img`
2. enter

**Expected behavior**
All images should at least have the same size like before but not larger. Is there any reason for this behavior?

**Version:**
 - OS w/ version: 10.15.7
 - Node version: 14.17.0
 - npm version: [e.g. 6.14.13]

**Comment by surma** [comment]
If you compress an image with the default codec options (`{}`), they can get bigger. It’s just like when you take a hugely compressed JPEG into Photoshop and re-save it as a JPEG with the quality slider set to 100. The image will get bigger.

**Comment by jakearchibald** [comment]
I don't have much experience with the CLI, but does a "no overwrite if bigger" setting make sense?

**Comment by surma** [comment]
@jakearchibald Yeah, that could make sense. It’s the default behavior for the auto-optimizer already.
