### ISSUE TITLE
Evaluate Embind 

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/squoosh#104]
https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#classes

**Comment by jakearchibald** [comment]
I looked at this a little in https://github.com/GoogleChromeLabs/squoosh/compare/webp-encode-integrate...webp-encode-options.

The tricky bits were getting c++ to compile along with the c, although I got that working in the end. The next bit is figuring out the right way to get the data in and out of c++. Emscripten hates that I'm passing pointers around, so I guess I should be doing something different with c++.

**Comment by jakearchibald** [comment]
This should be evaluated too https://github.com/charto/nbind. Looks like it generates TS, which is a big win. It also looks like it might make passing memory around, but I don't fully understand it.

**Comment by surma** [comment]
I’m gonna close this for now. nbind scares me and I’d like to stick to Emscripten as that’s a team we can directly work with. (Feel free to re-open if you disagree)

**Comment by jakearchibald** [comment]
Works for me.
