### ISSUE TITLE
Feature: -o, --output-file <filename>

### ISSUE THREAD

**Issue by ericfortis** [GoogleChromeLabs/squoosh#1045]
**Is your feature request related to a problem? Please describe.**
No, it's an enhancement.

**Describe the solution you'd like**
An option such as `--output-file <filename>`

**Does other service/app have this feature?**
Yes, `tar`, `ffmpeg`, and `magick` have options or ways to specify the output filename. 

**Additional context**
This [blog post](https://blog.uidrafter.com/engineering/convert-to-avif-programmatically) shows how I script image conversions (and why that way). In my case, the `squoosh-cli` requires special handling compared to other tools. For example, I have to parse the extension and pass it as `-s <suffix>`

The following diff is not perfect, but it's a start. For example, it needs to warn when passing many input files, and notifying or documenting that it overrides `--suffix` and `--output-dir`.

Please let me know what you think.

```diff
diff --git a/cli/src/index.js b/cli/src/index.js
index 697e4f5..de117d2 100755
--- a/cli/src/index.js
+++ b/cli/src/index.js
@@ -181,7 +181,7 @@ async function processFiles(files) {
           path.basename(originalFile, path.extname(originalFile)),
       );
       for (const output of Object.values(image.encodedWith)) {
-        const outputFile = `${outputPath}.${(await output).extension}`;
+        const outputFile = program.opts().outputFile || `${outputPath}.${(await output).extension}`;
         await fsp.writeFile(outputFile, (await output).binary);
         results
           .get(image)
@@ -203,6 +203,7 @@ async function processFiles(files) {
 program
   .name('squoosh-cli')
   .arguments('<files...>')
+  .option('-o, --output-file <filename>', 'Output filename', '')
   .option('-d, --output-dir <dir>', 'Output directory', '.')
   .option('-s, --suffix <suffix>', 'Append suffix to output files', '')
   .option(
```

**Comment by surma** [comment]
(Sorry for the accidental close)

I see where you are coming from, but a couple things are not quite clear to me: How do you envision this flag to behave when there are multiple input files or multiple formats specified?

**Comment by ericfortis** [comment]
Hi Surma,

I'd ignore the `--output-files` flag. In pseudocode:
```js
let {  oFlag, dFlag, sFlag } = opts;

if (hasManyInputFiles || hasManyOutputFormats || dFlag || sFlag) {
  oFlag = false;
  console.warn('Warning: "--output-file" was ignored');
}
```

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
