### ISSUE TITLE
Memory leak when going from compress screen to home screen

### ISSUE THREAD

**Issue by suiyuex** [GoogleChromeLabs/squoosh#1048]
I don't know this is whether or not a bug
once start compress image process will greatly improve memory usage

any solution can reduce memoery usage or not?

as you can see I just opened the [website](https://squoosh.app/)
the tab take about 30mb of memory 
![image](https://user-images.githubusercontent.com/51814639/121308091-3d116f80-c933-11eb-923f-e6346fa12301.png)
When I upload a image about 1.8m, the memory is straight up, and then wait for compress done (using default options)
the memory is about 800mb
and then i close the website image editor, the memory is about 350mb usage, and cant no longer reduce
![image](https://user-images.githubusercontent.com/51814639/121308888-24558980-c934-11eb-80af-3311b55faeca.png)
this is right or not? and there is a way to solve this or not? thank you guys

**Comment by suiyuex** [comment]
Can anyone explain? thank

**Comment by jakearchibald** [comment]
> and then i close the editor

Do you mean closing the tab, or going back to the home screen?

**Comment by suiyuex** [comment]
@jakearchibald sorry, i am not clearly described, close the editor is close the image editor
this here
![image](https://user-images.githubusercontent.com/51814639/122011168-67a96f80-cdee-11eb-90f7-36133813a7ac.png)

and i want to know the memory usage is normal? thanks.

**Comment by jakearchibald** [comment]
I can recreate this by:

1. Go to squoosh.app
2. Open the red panda image
3. Click the X to go back to the homescreen
4. GOTO 2

GPU memory usage increases by 100-200mb each time.

It doesn't happen when just changing compression settings, so I suspect it's related to the creation of `<canvas>`. It could be our bug, or Chromium.

**Comment by suiyuex** [comment]
Thanks for solving my doubts

**Comment by jakearchibald** [comment]
I couldn't recreate the issue in a simple reduced way (https://static-misc-3.glitch.me/canvas-memory-test/), so my gut feeling is the memory leak is our fault rather than chrome's.

**Comment by suiyuex** [comment]
> I can recreate this by:
> 
> 1. Go to squoosh.app
> 2. Open the red panda image
> 3. Click the X to go back to the homescreen
> 4. GOTO 2
> 
> GPU memory usage increases by 100-200mb each time.
> 
> It doesn't happen when just changing compression settings, so I suspect it's related to the creation of `<canvas>`. It could be our bug, or Chromium.

the 3 step is go back to the homescreen or go back to the page root route? im confused

**Comment by jakearchibald** [comment]
"Click the X" (the one in the top-left of your screenshot)

I'm tracking down memory leaks now…

**Comment by jakearchibald** [comment]
PR https://github.com/GoogleChromeLabs/squoosh/pull/1054

**Comment by jakearchibald** [comment]
Thanks for filing this issue! It identifed issues in both Squoosh and Chrome.

**Comment by suiyuex** [comment]
I also learned a lot
