### ISSUE TITLE
@libSquoosh - small typo in readme example

### ISSUE THREAD

**Issue by alex-drocks** [GoogleChromeLabs/squoosh#1051]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
Small typo in readme:
In the example code, it is written `preprocessOptions:{//...}`
```javascript
const preprocessOptions: {
    resize: {
      enabled: true,
      width: 100,
      height: 50,
    }
  };
```

 I think it should be an equal sign. Otherwise the const declaration is wrong.
```javascript
const preprocessOptions = {
    resize: {
      enabled: true,
      width: 100,
      height: 50,
    }
  };
```

**To Reproduce**
1. Go to `libSquoosh `repo example code in the readme
2. Copy paste `preprocessOptions` example code in your javascript editor (Webstorm here)
3. See error with Linter that says ` invalid const declaration`

**Expected behavior**
valid const declaration

**Version:**
n/a

**Is your issue related to the quality of image compression?**
no

**Additional context, screenshots, screencasts**
n/a

**Comment by alex-drocks** [comment]
EDIT: noticed the same declaration in the `const encodeOptions:` example. Am I missing a new NodeJS feature for this type of const declarations?

**Comment by surma** [comment]
No, those are indeed typos (or maybe copy/paste left-overs from TS experiments). Wanna open a PR to fix ’em?

**Comment by alex-drocks** [comment]
I'm a Github noob but I could try the pull request.. would be a first.
