### ISSUE TITLE
@libSquoosh - package.json entry point wrong on Windows computer

### ISSUE THREAD

**Issue by alex-drocks** [GoogleChromeLabs/squoosh#1052]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
`Error: Cannot find module 'C:\build\index.js'. Please verify that the package.json has a valid "main" entry`

the current package.json file entry point is like so:
```javascript
 "main": "/build/index.js",
  "files": [
    "/build/*"
  ],
```

It only finds the files if I add the dot notation before the path:
```javascript
 "main": "./build/index.js",
  "files": [
    "./build/*"
  ],
```

Complete error log:
`"C:\Program Files\nodejs\node.exe" C:\Users\Alex\local-dev\finance-d\finance-d-www\fd-www-react-pwa\libSquoosh.js
internal/modules/cjs/loader.js:316
      throw err;
      ^
Error: Cannot find module 'C:\build\index.js'. Please verify that the package.json has a valid "main" entry
←[90m    at tryPackage (internal/modules/cjs/loader.js:308:19)←[39m
←[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:521:18)←[39m
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:730:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:957:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\Alex\local-dev\finance-d\finance-d-www\fd-www-react-pwa\libSquoosh.js:4:21)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1068:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:933:32)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  path: ←[32m'C:\\Users\\Alex\\local-dev\\finance-d\\finance-d-www\\fd-www-react-pwa\\node_modules\\@squoosh\\lib\\packa
ge.json'←[39m,
  requestPath: ←[32m'@squoosh/lib'←[39m
}
`

**To Reproduce**
1. Go to libSquoosh repo and follow the example code in your code editor
2. Try to run the NodeJS script on your Windows machine
3. Console throws error

**Expected behavior**
should not fail to find the package.json entry point

**Version:**
 - OS w/ version: Windows 10
 - Browser w/ version n/a
 - Node version: 14.17.0

**Is your issue related to the quality of image compression?**
no

**Additional context, screenshots, screencasts**
```javascript
//libSquoosh.js
const fs = require('fs');
const path = require("path");

const {ImagePool} = require('@squoosh/lib');
const imagePool = new ImagePool();
const imagePath = path.resolve('./_originalRawImages/1_boxmockup-windows-mac-1920w.png');
console.log({imagePath});
const image = imagePool.ingestImage(imagePath);

(async () => {
  await image.decoded; //Wait until the image is decoded before running preprocessors

  const preprocessOptions = {
    resize: {
      enabled: true,
      width: 100,
      height: 50,
    }
  };
  await image.preprocess(preprocessOptions);

  const encodeOptions = {
    //an empty object means 'use default settings'
    webp: {},
    oxipng: {}
  };
  await image.encode(encodeOptions);

  await imagePool.close();

  const newImagePath = path.resolve('./src/images/libSquoosh_boxmockup-windows-mac-1920w');

  for (const encodedImage of Object.values(image.encodedWith)) {
    const {extension, binary} = (await encodedImage);
    const absPath = `${newImagePath}.${extension}`;
    console.log({absPath});
    fs.writeFile(absPath, binary, (err) => {
      if (err) throw err;
      console.log('The file has been saved!');
    });
  }
})();
```

**Comment by surma** [comment]
This is [already fixed](https://github.com/GoogleChromeLabs/squoosh/blob/dev/libsquoosh/package.json) on `dev`, but we haven’t re-published libsquoosh as we need to fix a bug with Butteraugli first. Should be fixed soon!
