### ISSUE TITLE
[lib] New feature: Signal if an image is lossless or lossy

### ISSUE THREAD

**Issue by atjn** [GoogleChromeLabs/squoosh#1060]
I have a use case where I need to know if an input image is compressed with a lossy or lossless algorithm. Figuring this out is easy for codecs like png and jpg which only support one type, but it's not that simple when I want to test a webp or jxl image.
Ideally, I would be able to get this information directly from Squoosh.

I have build a draft implementation in Squoosh, and it seems relatively simple to add this. I am detecting lossy/lossless encoding by reading the first two chunks of every image. Please let me know if there's a smarter way to get this info :D
The signal would be added to `libSquoosh` as `Image.decoded.lossless: true | false`.

Apart from helping me out, I also think this could be very useful for Squoosh itself. Currently, Squoosh will default to encoding any image lossy, even if it's an SVG. With this signal, it should be possible to automatically toggle the lossy/lossless switch in the target encoder, matching the encoding type for the input image, resulting in much better defaults.

Adding a system to change defaults based on the input image seems so complex that it's probably better to let the core team do it (or do you disagree?), but if I can get a green light on this, I'll be happy to implement the signal :)

**Comment by atjn** [comment]
Should I interpret your silence as a "no" to this, or more of a "we don't have time right now"?

**Comment by jakearchibald** [comment]
@surma can you take a look at this?

I'm worried this isn't as straightforward as it seems, as the definition of "lossy" vs "lossless" is really vague. If you're using a PNG, but it's been reduced to 16 colours, is that a lossy image or a lossless image?

Also, it's possible to create a JPEG that's pixel-identical to the original, which means "lossless" by pretty much any definition of that term.

**Comment by atjn** [comment]
> I'm worried this isn't as straightforward as it seems, as the definition of "lossy" vs "lossless" is really vague.

That's true, but for this signal it's a clear definition of whether the encoding algorithm itself is lossy or lossless, and nothing else. This is not only the easiest classification to make, it is also the most intuitive IMO, and the correct way to do it if you want to use it to set default encoder settings.

Why is it the correct way for default encoder settings? Well, because original images that can/should be lossy compressed, are usually already saved in a lossy format, but at 100% quality, essentially making them lossless. In this case, the default encoder settings should be set to lossy encode, not lossless just because the input image was at 100% quality.
This is also true for the opposite situation. Images that cannot be lossy encoded are usually already saved in a lossless format, and so the default encoder settings should be for a lossless encode, even though the original image encoding might have some bad settings applied that stripped some data, essentially making it a lossy image.

There will obviously be edge cases, such as if someone is saving their photographs as PNGs and expecting Squoosh to lossy encode those, but that is neither a good nor a common approach, and the default settings should try to satisfy the normal/correct approaches, not the edge cases.

**Comment by atjn** [comment]
@jakearchibald I noticed you added `[lib]` to the title. I just want to make it clear that while I am implementing this for `libSquoosh` right now, the intention is that it could also be used in the webapp.

**Comment by atjn** [comment]
@surma I found a different solution to my own use case that I think works just as well. I still think this feature would be useful for Squoosh itself, so I'm happy to complete it if you want me to, but otherwise feel free to close this issue :)

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
