### ISSUE TITLE
[squoosh.app] Super high resolution (10k+?) files fail to decode.

### ISSUE THREAD

**Issue by Laesx** [GoogleChromeLabs/squoosh#1068]
Seems like super high res or really big filesize images fail to decode, I did some light testing and it seems it only happened with 10k+ resolution files.

Windows 10
Firefox 89.0.1

The one that failed first is this image specifically:
https://files.catbox.moe/34z1m7.png

**Comment by surma** [comment]
Yeah, that’s quite possible. We decode into `ImageData` using a Canvas object, which I think is size limited. I am not sure there is much we can do, except for decoding it ourselves via Wasm, but even there I worry that decoding into a ~700MB raw RGBA buffer will cause problems.

**Comment by Laesx** [comment]
Oh welp, that's a real shame. I tested in a chromium browser (edge) and it did manage to decode it, but had a really hard time encoding it and crashed the page multiple times so yeah I get where you're coming from in that it would cause problems, I will close this issue then.
