### ISSUE TITLE
No quality for png (oxipng)?

### ISSUE THREAD

**Issue by jrmyio** [GoogleChromeLabs/squoosh#1076]
I am testing this library to replace imagemin, however I cannot find a quality setting for `oxipng` and `level` does not seem to effect the image size. In the issues I found that `oxipng` replaced `optipng` which may have had a quality setting?

What would be the way to actually compress a PNG?

I did some testing with `quant`'s `numColors ` and this works:
```
   const preprocessOptions = {
                quant: {
                    // numColors: 128
                }
            };
            await image.preprocess(preprocessOptions);
```
but I am not sure if this is the prefered method to make PNG significantly smaller and wether other png libraries do the same thing (as in lowering the amount of colors) when they apply a lower quality. 

I can imagine that an image with tons of colors would need a different `numColors` setting to still look okay, so it would be great if there is a `quality` setting that takes this into account.

**Comment by surma** [comment]
PNG is lossless, so it doesn’t have a “quality”. `level` is indeed the amount of effort the compressor should put it into make the image smaller. So if you set `level` to `3`, you’ll get the smallest PNG that OxiPNG can produce at the cost of increased compression time. That being said, for some images `level` does indeed not make a difference. Does imagemin produce smaller images than OxiPNG?

**Comment by jrmyio** [comment]
> PNG is lossless, so it doesn’t have a “quality”.

What makes PNG itself be lossless? That's related to the compression library (or coded) you are using. In this case squoosh uses a **lossless** compression library, but there are also **lossy** PNG compression libraries.

> Does imagemin produce smaller images than OxiPNG?

Yep I am using `imagemin-pngquant` (https://pngquant.org/).

Using the test image from their site and using it on squoosh.app results in an image slightly higher in size (`75kb`). Trying out different levels doesn't help.

Using the same image on https://pngquant.org/ makes it `20kb`.

Looking at their site they are saying their quality setting does:
_Instructs pngquant to use the least amount of colors required to meet or exceed the max quality. If conversion results in quality below the min quality the image won't be saved (if outputting to stdout, 24-bit original will be output) and pngquant will exit with status code 99._

So it does look like their lossy compression comes from changing the amount of colors which may be replicate it with 
```
{
               quant: {
                    // numColors: 128
                }
 }
```

However, in this case we are missing a quality value that does the heavy lifting of translating #colors to a quality (1-100) value.

Since Squoosh works on codec level it might be better to just add a codec based on `pngquant` than building lossy compression on top of a lossless compressor.

**Comment by jakearchibald** [comment]
In pngquant, the colour reduction is a preprocessing step. Squoosh uses the same library that pngquant uses to reduce the colours.

I don't think we should make this a png-only thing, as it's useful for other lossless codecs too, like WebP and JXL.

**Comment by Nantris** [comment]
@surma it would be great if Squoosh supported (visually imperceptible) lossy PNG compression as some other tools do. They only save a 2-5% more in file size (in my very limited testing,) but that's roughly on par with what the lossless compression so together they're pretty potent.

**Comment by jakearchibald** [comment]
@Slapbox can you give an example of one of these tools? Are you sure it's not just palette reduction?

**Comment by jakearchibald** [comment]
I've seen tools that try and make the image more predictable for non-paletted PNG (kinda like WebP's 'slight loss'), but the results are pretty bad. However, if folks are aware of a tool that does it well, speak up, and we'll take a look.

**Comment by Nantris** [comment]
@jakearchibald for now all I can offer is the "Expert mode" on https://kraken.io. For our particular use case, which is logos/icons/other in-app media, setting a PNG quality of 80 yielded an additional 34.3% savings compared to Squoosh alone. Using their default "Lossy" option saves nothing though.

The quality level of 80 is probably not good for photos, but for our use case I can't tell a difference, and it can shave maybe an entire megabyte off of our installer size if all the images see around 30% additional savings with that method.

**Comment by jakearchibald** [comment]
Can you give me a PNG optimised with that service?

**Comment by Nantris** [comment]
@jakearchibald here's an Imgur album with before/after https://imgur.com/a/CahsJOs

For reference, I believe that before Squoosh the original file was 246kb.

**Comment by jakearchibald** [comment]
Can you share it on GitHub (just drag it into the comment field)? Imgur is recompressing it.

**Comment by Nantris** [comment]
Ah I was concerned Github would recompress so I tested on Imgur and it didn't seem to. Something, something, the best laid plans of mice and men. 

**Here are the files:**

### Squoosh + Kraken - Quality 80:

![icon-1024x1024-@5x](https://user-images.githubusercontent.com/6835891/129618765-0d42f1f6-bbc4-41ab-a855-40061d989ca6.png)


### Squoosh only:

![icon-1024x1024-@5x](https://user-images.githubusercontent.com/6835891/129618959-8c617379-f284-48cb-82ee-4c6df1512d05.png)

**Comment by jakearchibald** [comment]
Yep, this looks like palette reduction to me, which Squoosh can already do.

**Comment by jakearchibald** [comment]
Here's a version from Squoosh that's only 80kb:

![129618765-0d42f1f6-bbc4-41ab-a855-40061d989ca6 (1)](https://user-images.githubusercontent.com/93594/129619779-f10d9e70-a2d2-459c-8384-fa904aa39220.png)

**Comment by Nantris** [comment]
Ah apologies for the misunderstanding @jakearchibald. I thought the savings we were already seeing were from palette reduction, especially since other automated tools that rely on palette reduction weren't reducing the size any further.

Can you possibly point me to the docs for Squoosh or Oxipng that relate to enabling that? I'm probably overlooking some obvious source, but can't find any particular flag to enable it in the docs of either project [besides this](https://docs.rs/oxipng/5.0.0/oxipng/struct.Options.html) which implies it's enabled by default and I'm not sure how I'd translate that over to Squoosh in any case.

The commands we'd been using were:

- `squoosh-cli --oxipng '{}' *.png`
- `squoosh-cli --oxipng '{"level": 3}' *.png`

**Comment by Nantris** [comment]
Agh nevermind, `--quant`. Found it via the `squoosh-cli --help` feature, but didn't see it mentioned anywhere on the web. Thank you again for your help and sorry again about that.

**Comment by jakearchibald** [comment]
Confirmed, the version from kraken has 20 colors, whereas the original has 251.

Of course, the best way to optimise an image like this is to make it smaller. It's currently 5120x5120. A 1700x1700 version of this, encoded as AVIF (without palette reduction) is less than 8kb https://cdn.glitch.com/2f4b4e08-395c-470d-aad5-9ba01f7c4597%2Fsquoosh.avif?v=1629190647484
