### ISSUE TITLE
Typescript types for @squoosh/lib 

### ISSUE THREAD

**Issue by jrmyio** [GoogleChromeLabs/squoosh#1077]
I am trying to use `Typescript `to use `@squoosh/lib` but getting the usual error when no types are available:
```
Could not find a declaration file for module '@squoosh/lib'. '/test/squoosh/node_modules/@squoosh/lib/build/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/squoosh__lib` if it exists or add a new declaration (.d.ts) file containing `declare module '@squoosh/lib';`ts(7016)
```

Are there are no types included for this library or could I doing something wrong?

Currently using 
```
// @ts-ignore
import { ImagePool } from '@squoosh/lib';
```
as a workaround.

**Comment by surma** [comment]
Yeah, we don’t have full types for libSquoosh yet, only for some of the files. It’s an incremental migration that @ergunsh is working on :)

**Comment by hyoretsu** [comment]
Bump, trying to use this to replace [imagemin](https://github.com/imagemin/imagemin) with TypeScript, but it doesn't have types so I can't even IntelliSense what options/properties are available.

**Comment by surma** [comment]
That’s more a question of documentation than TypeScript tbh. Feel free to take a look at the options object in [`codecs.ts`](https://github.com/GoogleChromeLabs/squoosh/blob/ad5002c79cccab7291b7bbb5d9f6270087ca6d4e/libsquoosh/src/codecs.ts#L251-L427).

**Comment by hyoretsu** [comment]
Having a list of properties/arguments (that work with IntelliSense) and their types is sorta documention, but also one of the purposes of TS. Some even go as far as adding a description to everything, making it even more like a built-in documentation.

Linking to that specific object does help way more than what's currently in the docs though.

**Comment by surma** [comment]
Yeah, we know documentation is a weak point and we are working on that. Fwiw, we do link to `codecs.ts` from the README of libsquoosh.

**Comment by styfle** [comment]
@ergunsh Thoughts on this one?

I think we can do something like `tsc --declaration --emitDeclarationOnly --declarationDir build` to generate the `.d.ts` files and publish those to npm.

**Comment by ergunsh** [comment]
Totally @styfle! :)

I was a bit skeptical to expose the types before improving the type definitions for `preprocess` and `encode` functions since those take some complicated parameters and providing ts types without them felt a bit meaningless.

So, I created a PR to add the parameter types to those https://github.com/GoogleChromeLabs/squoosh/pull/1141 and created another PR to expose the types https://github.com/GoogleChromeLabs/squoosh/pull/1142
