### ISSUE TITLE
Add `image-rendering: pixelated` toggle

### ISSUE THREAD

**Issue by kosamari** [GoogleChromeLabs/squoosh#1087]
TODO: catch up with @argyleink on UI placement

**Comment by kosamari** [comment]
Please see use case rationale in #950

**Comment by argyleink** [comment]
I'm thinking:
- only show this when zooming is above 100% (nice to have)
- showing an antialiasing toggle to the left of the zoom controls

i'll find an icon and make a design comp soon 👍🏻

**Comment by argyleink** [comment]
![alias-icon](https://user-images.githubusercontent.com/1134620/130819831-ce75ba84-1330-4a76-b51a-24877abdcf5e.png)

**Comment by Vishalghyv** [comment]
Fixed by #1132
