### ISSUE TITLE
Default `--output-dir` to overwrite the old image

### ISSUE THREAD

**Issue by blimmer** [GoogleChromeLabs/squoosh#1101]
**Is your feature request related to a problem? Please describe.**
I was surprised when the CLI tool didn't overwrite the files it was optimizing. Instead, it wrote the files to the root of my directory, where I was running the command from.

In referencing the document, I see that the `--output-dir` defaults to `.`, the location where you're running the tool from.

The current behavior is as follows:

```console
> pwd
/tmp/example-repo
> ls -al assets/images
total 500
drwxr-xr-x 5 blimmer wheel    160 Jul 14 12:44 ./
drwxr-xr-x 4 blimmer wheel    128 Jul 14 12:44 ../
-rw-r--r-- 1 blimmer wheel  34292 Jul 14 09:57 1.png
-rw-r--r-- 1 blimmer wheel 248841 Jul 14 10:21 2.png
-rw-r--r-- 1 blimmer wheel 222644 Jul 14 10:24 3.png
> npx @squoosh/cli --oxipng '{"level": 2}' assets/images/*.png
npx: installed 37 in 3.498s
3/3 ✔ Squoosh results:
 assets/images/1.png: 33.49KB
  └ 1.png → 20.44KB (61.0%)
 assets/images/2.png: 243.01KB
  └ 2.png → 127.58KB (52.5%)
 assets/images/3.png: 217.43KB
  └ 3.png → 111.63KB (51.3%)
> ls -al
total 268
drwxr-xr-x  8 blimmer wheel    256 Jul 14 12:46 ./
drwxrwxrwt 13 root       wheel    416 Jul 14 12:44 ../
drwxr-xr-x 12 blimmer wheel    384 Jul 14 12:46 .git/
-rw-r--r--  1 blimmer wheel  20930 Jul 14 12:46 1.png
-rw-r--r--  1 blimmer wheel 130638 Jul 14 12:46 2.png
-rw-r--r--  1 blimmer wheel 114306 Jul 14 12:46 3.png
drwxr-xr-x  4 blimmer wheel    128 Jul 14 12:44 assets/
-rw-r--r--  1 blimmer wheel    226 Jul 14 12:44 package.json
```

**Describe the solution you'd like**

It would be great if this tool overwrote the unoptimized file by default. Considering the example from above, this is the behavior I'd expect:

```console
> pwd
/tmp/example-repo
> ls -al assets/images
total 500
drwxr-xr-x 5 blimmer wheel    160 Jul 14 12:44 ./
drwxr-xr-x 4 blimmer wheel    128 Jul 14 12:44 ../
-rw-r--r-- 1 blimmer wheel  34292 Jul 14 09:57 1.png
-rw-r--r-- 1 blimmer wheel 248841 Jul 14 10:21 2.png
-rw-r--r-- 1 blimmer wheel 222644 Jul 14 10:24 3.png
> npx @squoosh/cli --oxipng '{"level": 2}' assets/images/*.png
npx: installed 37 in 3.426s
3/3 ✔ Squoosh results:
 assets/images/1.png: 33.49KB
  └ assets/images/1.png → 20.44KB (61.0%)
 assets/images/3.png: 217.43KB
  └ assets/images/3.png → 111.63KB (51.3%)
 assets/images/2.png: 243.01KB
  └ assets/images/2.png → 127.58KB (52.5%)
```

I can get this behavior by passing `-d assets/images` (`npx @squoosh/cli -d assets/images --oxipng '{"level": 2}' assets/images/*.png`), but it would be nice if this were the default. Users who want to place the files in a different location could still override the behavior via the `-d`/`--output-dir` flag.

**Additional context**

A change to the default behavior would help support my use of [`lint-staged`](https://github.com/okonet/lint-staged) to automatically compress images at commit time. Today, I have to do something like this for my `lint-staged` configuration:

```json
{
  "lint-staged": {
    "assets/images/*.png": ["npx @squoosh/cli -d assets/images --oxipng '{\"level\": 2}']
  }
}
```

Note that I have to restrict the staged pattern to `assets/images/*.png` so I can pass the proper `-d` variable.

If the default were changed, I could simplify this to:
```json
{
  "lint-staged": {
    "*.png": ["npx @squoosh/cli --oxipng '{\"level\": 2}']
  }
}
```

This would be preferable so all `png` images committed to this repo (regardless of the directory) would be optimized.

**Does other service/app have this feature?**

- [`svgo`](https://www.npmjs.com/package/svgo):
     ```
	  > npx --no-install svgo
	  Usage: svgo [options] [INPUT...]
	  
	  ... truncated output ...
	    -o, --output <OUTPUT...>   Output file or folder (by default the same as the input), "-" for STDOUT
	 ```

- [`imageoptim`](https://imageoptim.com/mac): by default, it overwrites the file when optimizing.

**Comment by Nantris** [comment]
Would love to see this feature! I don't think it should be the default output source though, too easy to accidentally overwrite. Maybe a flag, like `--overwrite-inputs`.

**Comment by strarsis** [comment]
+1! The current default behaviour can be destructive: The original file is overwritten with the compresed one!

**Comment by webds** [comment]
who solves this problem?

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
