### ISSUE TITLE
SIGBUS/SIGSEGV memory errors when resizing plus converting in some codecs

### ISSUE THREAD

**Issue by rianadon** [GoogleChromeLabs/squoosh#1103]
**Describe the bug**
Running squoosh with both `--resize` and `--webp` produces a SIGBUS (Misaligned address error) on MacOS. I've reproduced this with multiple images and with different options.

With avif, I get SIGSEGV (Address boundary error) or SIGBUS, depending on how my OS if feeling.

However, I can use the resize options with `--mozjpeg` without any segfaults.

If I run without `--resize`, avif and webp conversion work. Both commands with resize also do work with about 10% success rate (i.e. 10% chance of no segfaults).

**To Reproduce**
So far I haven't seen a case where these steps fail:
- Open an image in squoosh
- Turn on resize and set the resize to less than 100% (resize 100% works without issue)
- Set compression to webp
- The squoosh webapp shows the result successfully. But copying the npx command & running it fails.

Precise steps to reproduce the behavior:
1. Download the panda image (open squoosh webapp, open panda example, download the uncompressed image). I've also attached it to this issue: [photo](https://user-images.githubusercontent.com/18223213/125918649-2fcfe753-6fc8-4ead-8df7-13e32b0c395a.jpg)
2. Download squoosh-cli with `npm`
2. Run `squoosh-cli --resize '{"enabled":true,"width":1000,"height":335,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --webp '{"quality":70,"target_size":0,"target_PSNR":0,"method":6,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' photo.jpg`

For avif I'm using: `squoosh-cli --resize '{"enabled":true,"width":500,"height":500.0,"method":"lanczos3","fitMethod":"stretch"}' --avif '{"cqLevel":13,"speed":2}' photo.jpg`

**The error**

```
 photo.jpg: 2.66MBfish: Job 1, 'squoosh-cli --resize '{"enabled…' terminated by signal SIGBUS (Misaligned address error)
```

**Version:**
 - OS w/ version: macOS 11.4, arm64
 - Node version: v16.4.0
 - npm version: 7.18.1

Here is the crash report if it's any help: [node_2021-07-16-014625.crash.txt](https://github.com/GoogleChromeLabs/squoosh/files/6829308/node_2021-07-16-014625.crash.txt)

**Comment by surma** [comment]
Can you do me a favor and re-try on Node v16.5? An important bug fix for Wasm on arm64 landed in the last update that caused seg faults.

**Comment by rianadon** [comment]
Silly me. That fixed it. Thanks!
