### ISSUE TITLE
squoosh cli windows conversion stuck

### ISSUE THREAD

**Issue by PetrusVermaak** [GoogleChromeLabs/squoosh#1104]
Installed on Windows 10 with following cmd: `npm i -g @squoosh/cli`
Ran `squoosh-cli --webp auto pic.png`, which created pic.webp (but it was larger than original png
Then tried `squoosh-cli --webp '{"quality":75}' pic.png`
It starts but is stuck on 1 thread, even after 30 min:
0/1 | ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (8 threads)
 pic.png: 15.66KB(node:13288) UnhandledPromiseRejectionWarning: Cannot use 'in' operator to search for 'lossless' in {quality:75}
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection0/1 / ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (8 threads)

**Comment by surma** [comment]
What is your Node version? Can you make sure you are using the latest Squoosh CLI by using `npm i -g @squoosh/cli@latest`? Does the problem still occur?

**Comment by PetrusVermaak** [comment]
Hi @surma 
My node version is v14.15.4. I ran `npm i -g @squoosh/cli@latest`, but still get the same error.

**Comment by surma** [comment]
Thanks, @PetrusVermaak.

I can’t reproduce this on MacOS or Linux. So I guess this is an issue with Windows. I don’t have a machine at hand, so if anyone wants to help here, that’d be awesome.

```
$ docker run --rm -ti -v /Users/surma/Downloads:/Downloads node:14.15.4 /bin/bash

# root@acab10b6660b:/# npm i -g @squoosh/cli
/usr/local/bin/squoosh-cli -> /usr/local/lib/node_modules/@squoosh/cli/src/index.js
/usr/local/bin/cli -> /usr/local/lib/node_modules/@squoosh/cli/src/index.js
+ @squoosh/cli@0.7.1
added 37 packages from 39 contributors in 2.815s

# root@acab10b6660b:/# squoosh-cli --webp '{"quality":75}' /Downloads/squoosh.png 
1/1 ✔ Squoosh results:
 /Downloads/squoosh.png: 72.68KB
  └ squoosh.webp → 13.79KB (19.0%)
```

**Comment by jcao219** [comment]
Windows here!

Funny, I tried first to reproduce on Powershell and there was no issue.

```
> ~\Downloads\node-v14.15.4-win-x64\node ~\Downloads\node-v14.15.4-win-x64\node_modules\@squoosh\cli\src\index.js --webp '{"quality":75}' .\heaps.png
⠋ (node:15588) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15588) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:15588) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:15588) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
1/1 ✔ Squoosh results:
 .\heaps.png: 111.55KB
  └ heaps.webp → 9.86KB (8.83%)
```

Then, I opened a regular Command Prompt and found that I could reproduce it.

The problem `TypeError: Cannot use 'in' operator to search for 'lossless' in {quality:75}`:
* does not occur in powershell (weird!)
* also occurs in node version 16.4.0
* has the full stack trace:

```
TypeError: Cannot use 'in' operator to search for 'lossless' in {quality:75}
    at Object.toWireType (C:\Users\jcao2\dev\squoosh\libsquoosh\build\index.js:1:96950)
    at Object.encode (eval at new_ (C:\Users\jcao2\dev\squoosh\libsquoosh\build\index.js:1:104602), <anonymous>:10:26)
    at encodeImage (C:\Users\jcao2\dev\squoosh\libsquoosh\build\index.js:37:73)
    at async MessagePort.<anonymous> (C:\Users\jcao2\dev\squoosh\libsquoosh\build\index.js:26:742)
```

Hmm, so further investigation showed me that using this command:

```npx @squoosh/cli --webp "{\"quality\":75}" heaps.png``` (notice the double quotes and escaping)

makes it work on Windows Command Prompt. The root issue has something to do with CLI arg parsing?

**Comment by jcao219** [comment]
It appears that in the Windows Command Prompt, single quotes are simply parsed as an ordinary character. So the command is the equivalent of doing in Powershell or even a POSIX Shell something like:  `npx @squoosh/cli --webp "'{quality:75}'" heaps.png` which reproduces the original error, `Cannot use 'in' operator to search for 'lossless' in {quality:75}`

We should do better CLI arg validation in order to prevent this source of confusion.

**Comment by PetrusVermaak** [comment]
@jcao219 PowerShell!! That worked!! Still cannot get your `npx @squoosh/cli --webp "{\"quality\":75}" heaps.png` to work on Windows cmd, but happy that I can get `squoosh-cli --webp '{"quality":75}' heaps.png` to work on PowerShell.

Sorry for asking, but how would I convert all jpg and png and output them in the same folder? I tried: `squoosh-cli --webp '{"quality":75}' ./*.*` but no go. Am new to running scripts and all that...

**Comment by PetrusVermaak** [comment]
And just a big thank you to @surma and @jcao219 for the awesome support and helping a total noob. Much appreciated!!!! :D

**Comment by jcao219** [comment]
@PetrusVermaak Wildcards are not quite working yet on Windows, see #973.

**Comment by PetrusVermaak** [comment]
For those who want to batch on Windows 10:
Finally managed to get macOS going on vmware, installed node.js from [https://nodejs.org/en/download/](url) and batch cmd `squoosh-cli --webp '{"quality":75}' ./*.*` is working!! Yea it's ugly but it works...

@surma & @jcao219 When wildcards are fixed on Windows 10, please let us know! :D

**Comment by Monkey1GIt** [comment]
I can work  on cmd of Windows 10 as @jcao219 said, using the command like:
`npx @squoosh/cli --mozjpeg "{\"quality\":80,\"baseline\":false,\"arithmetic\":false,\"progressive\":true,\"optimize_coding\":true,\"smoothing\":0,\"color_space\":3,\"quant_table\":3,\"trellis_multipass\":false,\"trellis_opt_zero\":false,\"trellis_opt_table\":false,\"trellis_loops\":1,\"auto_subsample\":true,\"chroma_subsample\":2,\"separate_chroma_quality\":false,\"chroma_quality\":75}" "C:\Users\dell\Desktop\IMG_20210729_195643.jpg"`

**Comment by shirokoweb** [comment]
On Windows:

cd the folder containing images to optimize and run the command without single quotes around config parameters (keep curling braces):
`cd C:\Path\To\Folder\`
`npx @squoosh/cli --mozjpeg {qality:30} filename.png`

@surma I tried various commands without luck for batch optimization, including wildcard *.png ;  * ;  etc. no luck. Any hint ?

**Comment by ivanshilo** [comment]
@shirokoweb for me on Windows works:
`squoosh-cli src/images/ -d dist/images --mozjpeg '{qality:30}'`

**Comment by shirokoweb** [comment]
@ivanshilo cmd works like a charm, thanks for sharing.
Only thing is I'm getting a warning message and squoosh cli gets stucked:
```
- (node:9092) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9092) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:9092) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:9092) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
30/32 / ▐▨▨▨▨╌╌╌╌╌╌▌ Decoding...
0/32 - ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (12 threads)
 src\images\ajh.png: 747.46KB
 src\images\Copy of IMG-20201127-WA0006.jpg: 144.98KB
```

**Comment by ivanshilo** [comment]
@shirokoweb Quick search shows something similar to your problem: https://stackoverflow.com/questions/50709059/maxlistenersexceededwarning-possible-eventemitter-memory-leak-detected-11-mess
By default there are maximum 10 event listeners in node.js 'event' module allowed. It sounds for me like a software issue in squoosh (either bug with unsubscribing from event or wrong initial code configuration - should be more than 10 allowed)

What happens if you process only 9 images in your folder?

**Comment by hybridherbst** [comment]
Same issue, any problem in the input (file not found, json parse error, ...) causes an UnhandledPromiseRejectionWarning and Squoosh is then in an endless loop and will never return.
Also happens for #1181 and #1171 on Windows 10.

**Comment by digiage** [comment]
> 

can you please share how?

**Comment by digiage** [comment]
> or those who want to batch on Windows 10:
> Finally managed to get macOS going on vmware, installed node.js from [https://nodejs.org/en/download/](url) and batch cmd `squoosh-cli --webp '{"quality":75}' ./*.*` is working!! Yea it's ugly but it works...

can you please share how?

**Comment by goutham05** [comment]
is still wildcards an issue using windows ? I am facing the same   @squoosh/cli@0.7.2 and node js 14.13.2 windows 11

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
