### ISSUE TITLE
AVIF multithread error & performance

### ISSUE THREAD

**Issue by chenaski** [GoogleChromeLabs/squoosh#1111]
**Describe the bug**

`@squoosh/lib@4.0.0`

- Total time: ~5s (30 images)
- Error when the number of images exceeds 34: `"WebAssembly.Memory(): could not allocate memory"`

`@squoosh/lib@0.3.1`

- Total time: ~1s (30 images)

Everything works fine if I comment these lines: https://github.com/GoogleChromeLabs/squoosh/blob/d526877147990cf71e4dc4c0ff02797e034f586e/libsquoosh/src/codecs.ts#L340-L346

**To Reproduce**

```js
const { ImagePool } = require("@squoosh/lib");

const imagePool = new ImagePool();

(async () => {
  const startTime = Date.now();

  const imagePath = "1x1.png";

  for (let i = 1; i <= 34; i++) {
    const image = imagePool.ingestImage(imagePath);

    await image.decoded;

    const encodeOptions = {
      avif: {},
    };

    await image.encode(encodeOptions);

    await image.encodedWith.avif;

    console.count("end");
  }

  const endTime = Date.now();

  console.log((endTime - startTime) / 1000);

  process.exit(0);
})();
```

**Version:**

- OS w/ version: macos 11.5 (20G71), 16 GB, 8-Core Intel Core i9
- Node version: v16.6.0
- npm version: 7.19.1

**Additional context, screenshots, screencasts**

[1x1.png](https://user-images.githubusercontent.com/30154503/127746738-5f08f1b3-632d-445d-8436-75ac87c1f0de.png)

**Comment by surma** [comment]
This is likely a dup of #1012

**Comment by chenaski** [comment]
Yes, it looks like, but in my case, I process the images one by one and I still get a memory error. And even if I found a workaround, it is still very slow on my local machine. With threads support for avif the speed should have increased, maybe the problem is specific to my working machine/os?

**Comment by surma** [comment]
> I process the images one by one and I still get a memory error.

Seems like we might have a memory leak in our AVIF encoder then. cc @RReverser 

> With threads support for avif the speed should have increased

In Node 16.4+ it should have, yeah :-/

**Comment by RReverser** [comment]
> Seems like we might have a memory leak in our AVIF encoder then. cc @RReverser
> 
> >

I'm not very familiar with libsquoosh API. Does the above snippet look correct otherwise e.g. there is no need to explicitly free `image` or remove it from the pool or anything like that?

Is this issue reproducible on squoosh.app too?

**Comment by chenaski** [comment]
I tried to disable threads in squoosh.app and the AVIF encoding time increased from 7 to 20 seconds 😕

**Comment by surma** [comment]
> I tried to disable threads in squoosh.app and the AVIF encoding time increased from 7 to 20 seconds 😕

Turns out threads are useful :D

> I'm not very familiar with libsquoosh API. Does the above snippet look correct otherwise e.g. there is no need to explicitly free image or remove it from the pool or anything like that?
> Is this issue reproducible on squoosh.app too?

The code is alright. The `image` is a copy of the compression result in the worker. The web app often kills workers. libSquoosh re-uses the same wasm instance over and over. So the PWA is working around the leak, if there is any.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
