### ISSUE TITLE
Add link rel canonical to the rendered HTML

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/squoosh#1116]
When checking the Search Console for seeing how y'all are doing, I see about 9,000 duplicated pages and when I look at the results it's because there are heaps of query strings being used to launch squoosh.  If they don't generate different output it might be worthwhile putting `<link rel="canonical" href="https://squoosh.app">` in the head element.

**Comment by surma** [comment]
cc @mikedelgaudio do you fancy adding this to your PR?

**Comment by mikedelgaudio** [comment]
@surma sounds good
