### ISSUE TITLE
Abort previous compression job

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#112]
Currently, if I change a few options, I have to wait for each of the jobs to complete. Ideally it should abort anything in progress and compress at the latest settings.

Not sure what's the best way to do this, but `AbortController` is available in some browsers, and pretty easy to polyfil.

**Comment by surma** [comment]
I don’t know if we can abort running wasm code short of `terminate()`-ing the worker it is running in

**Comment by surma** [comment]
Need to investigate how `comlink-loader` deals with that, tho ;)

**Comment by developit** [comment]
indeed.

**Comment by jakearchibald** [comment]
@surma are you happy to look at this at some point? It feels like this might need to be a comlink thing. As in, you call terminate() through some comlink API, and it rejects any unresolved promises, then terminates the worker.

Then feel free to assign to @developit to look at the comlink-loader bits.

**Comment by surma** [comment]
I’ll coordinate with @developit. Not sure where this logic belongs. Gut says `comlink-loader`

**Comment by jakearchibald** [comment]
The bit that made me think that there'd be a root comlink part is aborting (rejecting with `AbortError`) in-flight promises.
