### ISSUE TITLE
Subsample chrome by input causes processing error when changed

### ISSUE THREAD

**Issue by Vishalghyv** [GoogleChromeLabs/squoosh#1129]
**Describe the bug**
Subsample chrome by input causes processing error when value changed.

**To Reproduce**
1. Open any image in squoosh app
2. Deselect Auto subsample chroma
3. Change 'Subsample chrome by' value

**Expected behavior**
No error should be shown and Even if there is it should not be [object Object]

**Version:**
 - Ubuntu 18.04
 - Chrome and Mozilla

**Additional context, screenshots, screencasts**
![Screenshot from 2021-08-23 00-50-10](https://user-images.githubusercontent.com/43421881/130367524-379957a0-e9cb-4508-ad9b-c060e0ce3b31.png)

**Comment by jakearchibald** [comment]
I can recreate this. It only happens with subsample values of 3 or 4.

**Comment by jakearchibald** [comment]
Looks like this bug was introduced in 912c1fac0865cc708476057ccadb82c3289e7245.
