### ISSUE TITLE
Squoosh no longer works

### ISSUE THREAD

**Issue by MorganSchmiedt** [GoogleChromeLabs/squoosh#1135]
**To Reproduce**
1. Go to https://squoosh.app (page loads fine)
2. Load an image (or click on one of the demo images)
3. Page hangs

This issue occurs both on Firefox v99 and Chrome v92.
Firefox console says : `Uncaught (in promise) TypeError: this.observer is undefined [...] componentWillUnmount`
Chrome console says : `Cannot read property 'disconnect' of undefined [...] at ne.componentWillUnmount`

It might have something to do with this : https://github.com/GoogleChromeLabs/squoosh/blob/4e901c714c65987f5969af00e9570e7389503f11/src/shared/prerendered-app/Intro/SlideOnScroll/index.tsx#L45

P.S: Thanks for making such an easy-to-use tool

**Comment by jakearchibald** [comment]
Aha! This happens if you have `prefers-reduced-motion: reduce`. Thanks for reporting. Fix out soon.

**Comment by jakearchibald** [comment]
Thanks for reporting. The fix has deployed. Next time you visit Squoosh, it'll tell you there's an update available. When you press "reload", it'll give you the version with the fix. Let me know if it doesn't work.
