### ISSUE TITLE
Remove WebAssembly SIMD origin trial token

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChromeLabs/squoosh#1139]
Since WebAssembly SIMD origin trial ended, it is no longer useful to have this token in https://squoosh.app.

![image](https://user-images.githubusercontent.com/634478/131671354-1f0d0773-6aae-4634-8a1a-301c5ffdeaee.png)
*DevTools Screenshots*

Note that WebAssembly SIMD has shipped in Chrome 91 according to https://www.chromestatus.com/feature/6533147810332672

**Comment by surma** [comment]
Assigning to @RReverser. Not urgent, but we should fix this eventually.

**Comment by beaufortfrancois** [comment]
I have a quick PR for this at https://github.com/GoogleChromeLabs/squoosh/pull/1140
