### ISSUE TITLE
Create “Reset zoom” button

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/squoosh#114]

**Comment by jakearchibald** [comment]
Do we need this, given how easy it is to type 100?

**Comment by surma** [comment]
On any touch-screen device with software keyboard I’d find typing tedious.

Something we could do is similar to how android handles it: Double tap the image to set to 100%, another double tap to fit the screen.

**Comment by jakearchibald** [comment]
I don't think we need this for V1.

**Comment by kosamari** [comment]
Related to #345 let's think about larger zoom interaction for V2
