### ISSUE TITLE
libSquoosh declares a global `navigator` variable

### ISSUE THREAD

**Issue by aduh95** [GoogleChromeLabs/squoosh#1152]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**

`import "@squoosh/lib"` add a global `navigator` variable in `codecs.ts`. The issue is that some libraries assume the code is running is a web browser environment if there's a `navigator` object available on the global object.

**To Reproduce**

```sh
mkdir repro
cd repro
npm i sass @squoosh/lib
echo 'import "@squoosh/lib"; import "sass";' > test.mjs
node ./test.mjs
```

**Expected behavior**

`test.mjs` should exit with code 0.

**Actual behavior**

```
…/repro/node_modules/sass/sass.dart.js:92529
    if (ua.indexOf("DumpRenderTree") >= 0) return hooks;
           ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at …/repro/node_modules/sass/sass.dart.js:92529:12
    at Object.applyHooksTransformer (…/repro/node_modules/sass/sass.dart.js:7236:14)
    at Object.initHooks (…/repro/node_modules/sass/sass.dart.js:7216:251)
    at Object.initNativeDispatchContinue (…/repro/node_modules/sass/sass.dart.js:7182:9)
    at Object.initNativeDispatch (…/repro/node_modules/sass/sass.dart.js:7176:9)
    at Object.getNativeInterceptor (…/repro/node_modules/sass/sass.dart.js:9070:13)
    at Object.getInterceptor$x (…/repro/node_modules/sass/sass.dart.js:9326:16)
    at Object.set$render$x (…/repro/node_modules/sass/sass.dart.js:9363:16)
    at main0 (…/repro/node_modules/sass/sass.dart.js:17757:9)
    at …/repro/node_modules/sass/sass.dart.js:93924:7
```

**Version:**
 - OS w/ version: [e.g. iOS 12] N/A
 - Browser w/ version [e.g. Chrome 70] N/A
 - Node version: [e.g. 10.11.0] 16.9.1
 - npm version: [e.g. 6.4.1] 7.21.1

**Additional context, screenshots, screencasts**

It seems that Emscripten allows us to use anything for the pool size, so I suggest using something like `globalThis[Symbol.for('squoosh.navigator')].hardwareConcurrency` instead. I could also open a bug on the Sass issue tracker, but I don't think Sass is the only library that check for `globalThis.navigator` to make assumptions, and it'd be better to avoid it IMHO.

**Comment by TimvdLippe** [comment]
It seems like we can change https://github.com/GoogleChromeLabs/squoosh/blob/66ec7636675707e34e7991435b3a2df970d9ae62/codecs/cpp.Dockerfile#L7 to `-s PTHREAD_POOL_SIZE=\"globalThis[Symbol.for('squoosh.navigator')].hardwareConcurrency\" \` and that appears to work as expected. @surma WDYT?

**Comment by surma** [comment]
Seems reasonable to me.

**Comment by RReverser** [comment]
I'm not sure I understand the issue; in which circumstances the `navigator` is not defined?

**Comment by RReverser** [comment]
Ah I see - the problem is that we "polyfill" it in Node and that messes up checks in other libs?

**Comment by TimvdLippe** [comment]
The problem is that we set `PTHREAD_POOL_SIZE` to use a variable name that accidentally has a meaning in a different context (in this case web). However,`PTHREAD_POOL_SIZE` can take any string, so we could have chosen `PTHREAD_POOL_SIZE=foo.bar` and that would have worked as well. The solution then is to use a symbol to ensure uniqueness, which we can then refer to in JavaScript.

**Comment by RReverser** [comment]
> so we could have chosen `PTHREAD_POOL_SIZE=foo.bar`

Yeah but then we need to set that to number of CPUs on both Web and Node.

I can see how polyfilling navigator is bad for Node lib usecase though.

I have another suggestion: let's instead change it to

```
-s PTHREAD_POOL_SIZE='ENVIRONMENT_IS_NODE ? require("os").cpus().length : navigator.hardwareConcurrency'
```

This should work correctly in both Node and browser environments that we build for, and I've verified that the condition check and unused branch are eliminated by Closure (which we use) when we set `-s ENVIRONMENT=worker` or `-s ENVIRONMENT=node` (which we do) so it's zero-cost.

This seems like a simpler solution than setting a global symbol in each environment.

**Comment by TimvdLippe** [comment]
Yes that appears to work, thanks for the suggestion :+1: PR incoming to make that change :smile:

**Comment by Airkro** [comment]
It seems that it can't be resolved temporarily. try:

```js
await squoosh(...args);
delete globalThis.navigator;
```

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
