### ISSUE TITLE
Run batch squoosh-cli jobs based on config file

### ISSUE THREAD

**Issue by Th3S4mur41** [GoogleChromeLabs/squoosh#1153]
**Is your feature request related to a problem? Please describe.**
I'm running squoosh to batch resize, optimize and convert multiple folders of images.
Currently, I have to execute a single script for each size-format-folder combination.

Using the following folder structure as an example:
```
images
--covers
--albums
----album1
----album2
```

...and considering only 2 sizes and 2 formats, I would currently end up with the following scripts:

```
squoosh-cli --resize '{"enabled":true,"width":1920}'  --mozjpeg auto --output-dir optimized-images/covers images/covers/*
squoosh-cli --resize '{"enabled":true,"width":1920}'  --mozjpeg auto --output-dir optimized-images/albums/album1 images/albums/album1/*
squoosh-cli --resize '{"enabled":true,"width":1920}'  --mozjpeg auto --output-dir optimized-images/albums/album2 images/albums/album2/*
squoosh-cli --resize '{"enabled":true,"width":1280}' --mozjpeg auto --output-dir optimized-images/covers images/covers/*
squoosh-cli --resize '{"enabled":true,"width":1280}'  --mozjpeg auto --output-dir optimized-images/albums/album1 images/albums/album1/*
squoosh-cli --resize '{"enabled":true,"width":1280}'  --mozjpeg auto --output-dir optimized-images/albums/album2 images/albums/album2/*
squoosh-cli --resize '{"enabled":true,"width":1920}'  --webp auto --output-dir optimized-images/covers images/covers/*
squoosh-cli --resize '{"enabled":true,"width":1920}'  --webp auto --output-dir optimized-images/albums/album1 images/albums/album1/*
squoosh-cli --resize '{"enabled":true,"width":1920}'  --webp auto --output-dir optimized-images/albums/album2 images/albums/album2/*
squoosh-cli --resize '{"enabled":true,"width":1280}' --webp auto --output-dir optimized-images/covers images/covers/*
squoosh-cli --resize '{"enabled":true,"width":1280}'  --webp auto --output-dir optimized-images/albums/album1 images/albums/album1/*
squoosh-cli --resize '{"enabled":true,"width":1280}'  --webp auto --output-dir optimized-images/albums/album2 images/albums/album2/*
```

**Describe the solution you'd like**
Be able to run the squoosh-cli with settings into a `squoosh.json` config file
`squoosh-cli --config squoosh.json  images/**/*`

```
squoosh.json

{
  "output_dir": "optimized-images",
  "formats": {
    "mozjpeg": "auto",
    "webp": "auto"
  },
  "resize": [  
    {"width": 1920}, {"width": 1280}
  ]
}
```

**Does other service/app have this feature?**
[svg-sprite](https://github.com/svg-sprite/svg-sprite/blob/master/docs/command-line.md) has a great example of a config file alternative to the console parameters

The squoosh web app could even be used to generate the config file similar to the svg-sprite configurator: https://svg-sprite.github.io/svg-sprite/#json

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
