### ISSUE TITLE
Squoosh website vs CLI compression size

### ISSUE THREAD

**Issue by Paxatax** [GoogleChromeLabs/squoosh#1154]
**Describe the bug**
When I use the Squoosh app to compress an image (OxiPNG, 40 width, 30 colors, everything else default) I get an output that is about 600-700 bytes in size. If I use the CLI, doing the same thing (or what I think should do the same thing, since I use the "Copy npx command" button), I get 2kb.

`npx @squoosh/cli output/*.png --resize '{"width": 40, "method": "lanczos3" }' --quant '{"numColors":30, "dither": 1}' --oxipng '{"level": 2}' -s "-squoosh" -d output`

Is there anything I'm missing from the script, or is the CLI just not yet able to compress to the same level as the website?

**Version:**
 - OS w/ version: macOS Big Sur 11.4
 - Browser w/ version: Chrome v91.0.4472.114 
 - Node version: v14.16
 - npm version: v6.14.11

Let me know if there is any additional information needed.

Thank you very much for your time, and for creating this wonderful tool.

**Comment by AforDesign** [comment]
I can confirm I ran into the same issue.

cli-command:
`npx @squoosh/cli --quant '{"enabled":true,"zx":0,"maxNumColors":64,"dither":0}' --oxipng '{"level":3,"interlace":false}' *.png -d png8_64c`

Squoosh-cli: version ? (latest 30 May 2022, -V parameter not working)
OS: OSX 12.4 
NodeJS: 16.14.0
NPM: 8.5.5

Output via CLI is 1.5 - 3 x the size of the output of the app.
I'm using the 'copy npx command' in the header of the settings to get the cli command.

Alos, running the cli command shows the following errors:
(node:62688) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:62688) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:62688) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:62688) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by aggregate1166877** [comment]
@Paxatax @AforDesign 

Seeing as we actually need this functionality, we've forked the project. A CLI-capable version is up at https://squoosh.frostoven.com/

Do you have an example of an image that has the size discrepancy? We've not been able to reproduce it ourselves, and will be happy to have a look and see if we can find the underlying issue.

**Comment by AforDesign** [comment]
Thanks alot for picking up this great feature!
I've mailed you a set of examples.

**Comment by aggregate1166877** [comment]
> I've mailed you a set of examples.

@AforDesign No emails have come through yet. It's possible you sent it to a noreply address. Can you please mail those examples to [redacted]?

**Comment by AforDesign** [comment]
Could you check if it arrived this time?

**Comment by aggregate1166877** [comment]
@AforDesign It came through :). Will investigate next week

**Comment by aggregate1166877** [comment]
@AforDesign I've improved some of the size issues; there were multiple bugs:
* The color reduction count specified via terminal was completely ignored (for all image types).
* The interlace option specified via terminal was ignored for OxiPNG.

The image size discrepancy is not completely fixed, and I have found some personal images that are still larger in CLI when compressed via OxiPNG. But, at least for the images + command you've supplied me, all image sizes match the web UI, or are smaller.

Additionally, I've removed the annoying warnings spammed while running the application.

Seeing as `@squoosh/cli` has been retired, you'll need to uninstall that and use [@frostoven/squoosh-cli](https://www.npmjs.com/package/@frostoven/squoosh-cli). There's a manual page for it [here](https://squoosh.frostoven.com/cli/).

**Comment by TPS** [comment]
@aggregate1166877 Thanks for opening up access to @frostoven's [fork](https://github.com/frostoven/squoosh.frostoven.com).  Maybe some of the previous & new contributors can head over there & chip in? 🙇🏾‍♂️

**Comment by AforDesign** [comment]
@aggregate1166877 That's awesome! And you fixed this super fast. Thanks alot for the great work.
Somnewhere next week I will run your update on a large batch.
I will let you know if any size discrepancy occurs.

I'm especially curious how images with a lower color count then set in the parameter will be processed. That has been a big issue with many optimizers, resulting in images larger than the original.
