### ISSUE TITLE
libsquoosh: node will not exit unless ImagePool is closed.

### ISSUE THREAD

**Issue by pekeq** [GoogleChromeLabs/squoosh#1156]
Hello,

After creating an instance of ImagePool, node will not exit unless ImagePool is closed.
For example, nodejs does not terminate when it reaches the end of following code.

```javascript
import { ImagePool } from '@squoosh/lib';

const imagePool = new ImagePool();
```

```
$ node test1.mjs 
(does not terminate)
^C
$
```

node will exit normally when instance of ImagePool is closed.

```javascript
import { ImagePool } from '@squoosh/lib';

const imagePool = new ImagePool();
await imagePool.close();
```

```
$ node test2.mjs 
(terminate normally)
$
```

**Version:**
 - libsquoosh version: 0.4.0, 0.3.1
 - OS w/ version: macOS 11.5.2
 - Node version: v14.17.6, v16.9.1

**Comment by surma** [comment]
That is not really a bug. The ImagePool manages the workers and Node won’t exit if workers are still running. That’s also why every sample in the README explicitly closes the ImagePool.

At some point we might consider adding a `FinalizationRegistry` thing, but for now we are gonna keep it explicit.

**Comment by pekeq** [comment]
@surma Thank you for your reply.
I was also thinking that this behavior might be a specification(not a bug), but I wrote this issue to confirm.

My library depends on ImagePool without close()ing, so I try some workarounds. 
Thanks,
