### ISSUE TITLE
CLI could not run when the path have space.

### ISSUE THREAD

**Issue by Moderpach** [GoogleChromeLabs/squoosh#1161]
**Describe the bug**
CLI could not recognize the path correctly when there ara spaces in it, but the web edition work fine.
For example, when I command the path is  './bug 1', CLI think the path is './bug'.

```
> npx @squoosh/cli --jxl '{"effort":7,"quality":100,"progressive":false,"epf":-1,"lossyPalette":false,"decodingSpeedTier":0,"photonNoiseIso":0}' -d .\ "C:\Users\九曦\bug 1.png"

(node:11760) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'C:\Users\九曦\bug'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. Find a picture which name has spaces.
2. Use CLI to handle the picture.

**Expected behavior**
CLI can handle files which name has spaces

**Version:**
 - Windows 11
 - Node version: 14.18.0
 - npm version: 6.14.15

**Comment by hybridherbst** [comment]
Same here, e.g. when running squoosh from another directly (e.g. a batch droplet) and either the target file name or any directory in the path has spaces, squoosh will not work and instead print
```(node:22172) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat ```.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
