### ISSUE TITLE
Bus error: 10 on M1

### ISSUE THREAD

**Issue by naisanzaa** [GoogleChromeLabs/squoosh#1164]
related: https://github.com/GoogleChromeLabs/squoosh/issues/1010

**Describe the bug**
Shows error after encoding `Bus error: 10`

**To Reproduce**
```
makbuk:Clear container eric$ npx @squoosh/cli -d out --mozjpeg auto *.JPG
0/51 ⠦ ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (8 threads)
 PA175213.JPG: 4.43MB
 PA175214.JPG: 5.55MB
 PA175215.JPG: 5.93MB
 PA175216.JPG: 6.23MB
 PA175217.JPG: 6.32MB
 PA175218.JPG: 6.36MB
 PA175219.JPG: 6.40MB
 PA175212.JPG: 7.83MB
 PA175220.JPG: 8.03MB
 PA175221.JPG: 9.11MB
 PA175222.JPG: 7.53MB
 PA175223.JPG: 8.65MB
 PA175225.JPG: 5.24MB
 PA175224.JPG: 8.41MB
 PA175226.JPG: 6.93MB
 PA175227.JPG: 5.02MB
 PA175228.JPG: 6.26MB
 PA175229.JPG: 6.66MB
 PA175230.JPG: 7.06MB
 PA175231.JPG: 4.73MB
 PA175233.JPG: 7.03MB
 PA175232.JPG: 6.01MB
 PA175234.JPG: 4.99MB
 PA175235.JPG: 7.78MB
 PA175236.JPG: 8.41MB
 PA175237.JPG: 8.37MB
 PA175238.JPG: 8.28MB
 PA175239.JPG: 8.41MB
 PA175240.JPG: 8.85MB
 PA175241.JPG: 8.05MB
 PA175242.JPG: 8.46MB
 PA175243.JPG: 8.67MB
 PA175244.JPG: 8.68MB
 PA175245.JPG: 8.74MB
 PA175246.JPG: 9.21MB
 PA175247.JPG: 9.23MB
 PA175248.JPG: 8.18MB
 PA175249.JPG: 9.47MB
 PA175250.JPG: 6.61MB
 PA175251.JPG: 8.36MB
 PA175252.JPG: 8.97MB
 PA175253.JPG: 8.70MB
 PA175255.JPG: 7.18MB
 PA175256.JPG: 8.81MB
 PA175257.JPG: 8.04MB
 PA175258.JPG: 9.00MB
 PA175259.JPG: 6.86MB
 PA175260.JPG: 8.54MB
 PA175261.JPG: 6.32MB
 PA175262.JPG: 5.63MB
 PA175263.JPG: 7.80MBBus error: 10
```

**Expected behavior**

**Version:**
 - OS w/ version: 11.5.2 (20G95)
 - Node version: v16.9.1
 - npm version: 7.21.1

![PA175213](https://user-images.githubusercontent.com/58240560/137619438-d92777de-b01d-432d-b784-326c23d68c99.JPG)

**Comment by chrisui** [comment]
Also have the same error on Mac M1 Pro

```
Node v16.15.0
Model Name:	MacBook Pro
Model Identifier:	MacBookPro18,3
Chip:	Apple M1 Pro
Total Number of Cores:	10 (8 performance and 2 efficiency)
Memory:	32 GB
System Firmware Version:	7429.41.5
```

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by naisanzaa** [comment]
> Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

🫠
