### ISSUE TITLE
Pasted image from clipboard is not the same size as original

### ISSUE THREAD

**Issue by Skandar** [GoogleChromeLabs/squoosh#1178]
When image pasted from cliapboard it has not the same size as original image.

**Steps to reproduce the behavior:**
1. Copy image to clipboard.
1. Click on button "Paste".
1. Save original image.
1. Size in app not equal to the original image size.

**Expected behavior**
Pasted image has same size as origin.

**Version:**
 - OS w/ version: Ubuntu 21.04 / Windows 10
 - Browser w/ version Chrome 95 / Firefox 93
![art](https://user-images.githubusercontent.com/4959202/138333879-f27722e3-4ddb-496c-afd5-3008d797db64.jpg)

**Comment by surma** [comment]
Going via clipboard is OS-dependent. The OS can choose to deliver the copied image as a raw bitmap (or even a PNG), so that’s not really a bug in Squoosh but just the nature of clipboards.
