### ISSUE TITLE
[CLI] SyntaxError: JSON5: invalid character with verbatim command copied from squoosh.app

### ISSUE THREAD

**Issue by hybridherbst** [GoogleChromeLabs/squoosh#1181]
**Describe the bug**
Copying resize commands from squoosh.app and trying to use them results in SyntaxError and aborted processing.

**To Reproduce**
1. Go to https://squoosh.app/editor
2. Enable resize
3. Copy command
4. Open a terminal
5. Paste the command and append an image file name in that directory
6. Press Enter

**Expected behavior**
File is squooshed with those settings
Actual:
```
(node:28880) UnhandledPromiseRejectionWarning: SyntaxError: JSON5: invalid character 'l' at 1:45
    at syntaxError (C:\Users\herbst\AppData\Roaming\npm\node_modules\@squoosh\cli\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Users\herbst\AppData\Roaming\npm\node_modules\@squoosh\cli\node_modules\json5\lib\parse.js:1028:12)
    at Object.value (C:\Users\herbst\AppData\Roaming\npm\node_modules\@squoosh\cli\node_modules\json5\lib\parse.js:287:15)
    at lex (C:\Users\herbst\AppData\Roaming\npm\node_modules\@squoosh\cli\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Users\herbst\AppData\Roaming\npm\node_modules\@squoosh\cli\node_modules\json5\lib\parse.js:25:17)
    at Command.processFiles (file:///C:/Users/herbst/AppData/Roaming/npm/node_modules/@squoosh/cli/src/index.js:137:49)
(node:28880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that
```

Example command that fails (copied from squoosh.app + " file.jpg"):
```
npx @squoosh/cli --resize '{"enabled":true,"width":1024,"height":1024,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --mozjpeg '{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75} file.jpg
```

**Version:**
 - OS w/ version: [e.g. iOS 12]
 - Browser w/ version [e.g. Chrome 70]
 - Node version: [e.g. 10.11.0]
 - npm version: [e.g. 6.4.1]

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
- Original image 
- Output image from Squoosh

**Additional context, screenshots, screencasts**

**Comment by cxp108** [comment]
I got same problem when using squoosh-cli in windows.

OS : Win10
node:  16.13.0
cmd :  squoosh-cli --mozjpeg atuo 1.jpg

**Comment by surma** [comment]
Seems like there is `'` missing. I’ll take a look.

```diff
- npx @squoosh/cli --resize '{"enabled":true,"width":1024,"height":1024,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --mozjpeg '{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75} file.jpg
+ npx @squoosh/cli --resize '{"enabled":true,"width":1024,"height":1024,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --mozjpeg '{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75}' file.jpg
```

**Comment by jcao219** [comment]
If you're using the Windows Command Prompt, keep in mind that single quotes are not valid for enclosing quoted values.

It must be something like:

```'{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75}' file.jpg
+ npx @squoosh/cli --resize "{\"enabled\":true,\"width\":1024,\"height\":1024, ...
```

Single-quotes should work in Powershell, though.

**Comment by surma** [comment]
Oh that would explain it... Yeah Squoosh definitely uses single quotes. That seems easy to fix tho :)

**Comment by javahook** [comment]
I got the same error.
PS E:\temp> npx @squoosh/cli --resize '{"enabled":true,"width":1503,"height":1814,"method":"lanczos3","fitMethod":"stretch","premultiply":true}' --mozjpeg '{"quality":85,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75}' 63919g1.jpg

**Comment by DukeBJ** [comment]
~~on Windows delete keys "method":"lanczos3","fitMethod":"stretch" at JSON~~

UPD:
**OS:** windows 10
**SMD:** powershell 7.2.1
**NODE:** 14.19.3

If you have keys with string parameters, like `"method":"lanczos3"` or `"fitMethod":"stretch"`. You need to escape quotes from the key value, like `"method":\"lanczos3\"` or `"fitMethod":\"stretch\"`. It's work!

UPD2:

It's work only on squoosh-cli _(squoosh install global)_. Method `npx @squoosh/cli` dosen't work.

Example:
```
squoosh-cli -s '@2560px' -d '.\done\' --resize '{"enabled":true,"width":2560,"height":1440,"premultiply":true,"linearRGB":true,"method":\"lanczos3\", "fitMethod":\"contain\"}' --mozjpeg '{"quality":60,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75}' file-name.png
```

**IMPORTANT:**

`fitMethod: contain` doesn't work on Windows in cli mode.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
