### ISSUE TITLE
Offset is Out of Bounds

### ISSUE THREAD

**Issue by C0braCommander** [GoogleChromeLabs/squoosh#1183]
**Describe the bug**
Worked great for a few months but all of a sudden I am getting [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "offset is out of bounds".] {
  code: 'ERR_UNHANDLED_REJECTION'

**To Reproduce**
1. Go to terminal
2. Enter find . -name '.DS_Store' -type f -delete
npx @squoosh/cli --unhandled-rejections=strict --resize '{"enabled":true,"width":1000,"height":1000,"method":"lanczos3"}' --mozjpeg '{"quality":75}' "uncom" -d "com"

**Expected behavior**
It was supposed to compress the images

**Additional context, screenshots, screencasts**
![image](https://user-images.githubusercontent.com/93397788/139473624-09f9f835-45ab-434b-b45c-d787dd037a40.png)

**Comment by C0braCommander** [comment]
I solved it thank you everyone for all the help. The issue was my batch sizes were too big. You can solve this by running a bunch of small batches instead. I will be posting my solution once I get all the kinks worked out.

**Comment by kota-yata** [comment]
I got the same error. Can you elaborate what you mean by "batch size"?

**Comment by xiaotiandada** [comment]
> I solved it thank you everyone for all the help. The issue was my batch sizes were too big. You can solve this by running a bunch of small batches instead. I will be posting my solution once I get all the kinks worked out.

Suppose I have 400 files, divided into N*20 chunks.
A pool is created each time the loop is completed, and the guan dao is closed after the loop is completed
Resume execution after hibernation

``[ [20...], [20...] ]``

```js
    const imagePool = new ImagePool(cpus().length)
    // compression
    await imagePool.close()
    await sleep(5000)
```
