### ISSUE TITLE
Selfhost Squoosh

### ISSUE THREAD

**Issue by pritkr** [GoogleChromeLabs/squoosh#1186]
I am not able to access the official squoosh app from my web browser as I have Windows 7 in which Lets Encrypt certificate had expired recently and will be never updated. What I am asking for is Is there a way I can host the app in service like netlify or heroku. If yes, Please provide a short guide. Thank You in advance

**Comment by surma** [comment]
Just follow do `npm install && npm run build` and deploy the `build` folder whereever you like :)
