### ISSUE TITLE
This app on google play is legit ?

### ISSUE THREAD

**Issue by izac3d** [GoogleChromeLabs/squoosh#1189]
I found same app here

https://play.google.com/store/apps/details?id=com.vision.squoosh 

developer Nebil ali

Is it a legit copy ?

![Untitled](https://user-images.githubusercontent.com/23438535/142743686-b2821d26-2cfa-426e-bfcd-5caa81e64008.jpg)

**Comment by jakearchibald** [comment]
It is not legit.

**Comment by izac3d** [comment]
I reported the app many times but it still active !! what I can do ? I dont like to see amazing work like this used by a damn thieve

**Comment by izac3d** [comment]
If the app is not down please sue google.
