### ISSUE TITLE
Wrong units on the main website

### ISSUE THREAD

**Issue by K0-RR** [GoogleChromeLabs/squoosh#1192]
**Describe the bug**
![image](https://user-images.githubusercontent.com/43277609/143659423-ebe0ff92-2010-4597-a3e9-8621fbf9f92c.png)

I doubt You wanted to show the file sizes in milibits (mb). After checking the size of these assets I confirmed the proper unit would be Megabyte (MB)
Also, the last file's size does not even have a unit - it's just 13k (k what?) - and the size is actually 10.7 kB, not 13.

Taking this a step further I would recommend using [IEC prefixes](https://en.wikipedia.org/wiki/Binary_prefix#mebi) - eg. Mebibytes - instead of the SI ones.

**Comment by surma** [comment]
PRs welcome :)
