### ISSUE TITLE
Error: Could not load css

### ISSUE THREAD

**Issue by lx1054331851** [GoogleChromeLabs/squoosh#1204]
```javascript
src/static-build/index.tsx → .tmp/build...
[!] (plugin css) Error: Could not load css:/squoosh-dev/src/shared/prerendered-app/colors.css (imported by  initialCss): Cannot find \squoosh-dev\src\shared\prerendered-app\colors.css in pathToResult
Error: Could not load css:/squoosh-dev/src/shared/prerendered-app/colors.css (imported by  initialCss): Cannot find \squoosh-dev\src\shared\prerendered-app\colors.css in pathToResult
    at Object.load (F:\squoosh-dev\rollup.config.js:552:17)
    at F:\squoosh-dev\node_modules\rollup\dist\shared\rollup.js:18971:25
```
windows 10 x64
npm 16

**Comment by coderiy** [comment]
i have the same problem,have you solve it?

**Comment by tamilcselvan** [comment]
I have also faced the same issue. Do you have any solution to solve it?

`src/static-build/index.tsx → .tmp/build...
[!] (plugin css) Error: Could not load css:/Software/squoosh/src/shared/prerendered-app/colors.css (imported by initialCss): Cannot find \Software\squoosh\src\shared\prerendered-app\colors.css in pathToResult
Error: Could not load css:/Software/squoosh/src/shared/prerendered-app/colors.css (imported by initialCss): Cannot find \Software\squoosh\src\shared\prerendered-app\colors.css in pathToResult
    at Object.load (D:\Software\squoosh\rollup.config.js:552:17)
    at D:\Software\squoosh\node_modules\rollup\dist\shared\rollup.js:18971:25`

**Comment by zcraber** [comment]
Any solution to this?

**Comment by tamilcselvan** [comment]
Any solution?

**Comment by jakearchibald** [comment]
What's your use-case here? Does it not work if you go to squoosh.app?

**Comment by AlexZhong22c** [comment]
same problem. And I solve it by use node version of v14

**Comment by guiguicdd** [comment]
Same here

**Comment by jakearchibald** [comment]
Closing this due to lack of details.

**Comment by dillfrescott** [comment]
```
[!] (plugin css) Error: Could not load css:/Users/micro/Downloads/squoosh/src/shared/prerendered-app/colors.css (imported by initialCss): Cannot find \Users\micro\Downloads\squoosh\src\shared\prerendered-app\colors.css in pathToResult
Error: Could not load css:/Users/micro/Downloads/squoosh/src/shared/prerendered-app/colors.css (imported by initialCss): Cannot find \Users\micro\Downloads\squoosh\src\shared\prerendered-app\colors.css in pathToResult
    at Object.load (C:\Users\micro\Downloads\squoosh\rollup.config.js:552:17)
    at C:\Users\micro\Downloads\squoosh\node_modules\rollup\dist\shared\rollup.js:18971:25
```

Please open this again. I followed the steps exactly to try to build squoosh and this is what the error is.

**Comment by Wakkos** [comment]
Same here.

I cloned the repo, ran NPM INSTALL and then NPM RUN DEV and this error jumped: 

```
npx browserslist@latest --update-db
[!] (plugin css) Error: Could not load css:/Users/wakko/Documents/squoosh/src/shared/prerendered-app/colors.css (imported by initialCss): Cannot find \Users\wakko\Documents\squoosh\src\shared\prerendered-app\colors.css in pathToResult
Error: Could not load css:/Users/wakko/Documents/squoosh/src/shared/prerendered-app/colors.css (imported by initialCss): Cannot find \Users\wakko\Documents\squoosh\s    at Object.load (C:\Users\wakko\Documents\squoosh\rollup.config.js:552:17)
    at C:\Users\wakko\Documents\squoosh\node_modules\rollup\dist\shared\rollup.js:18971:25
    
  ```
  Windows 10, Node V 16.5.0

**Comment by dillfrescott** [comment]
Yeah judging by like 10 different people having the same issue there's definitely something wrong...

**Comment by antnesswcm** [comment]
> same problem. And I solve it by use node version of v14

我使用14版本(14.21.3)的nodejs成功构建了项目，谢谢

I successfully built the project using Nodejs version 14 (14.21.3). Thank you

**Comment by abhinavpatel0** [comment]
i have the same problem

**Comment by antnesswcm** [comment]
> Closing this due to lack of details.

请切换到其他版本的nodejs来尝试构建
Please switch to a different version of nodejs to try building it

such as nodejs 14

**Comment by lizhiyu-me** [comment]
> > Closing this due to lack of details.
> 
> 请切换到其他版本的nodejs来尝试构建 Please switch to a different version of nodejs to try building it
> 
> such as nodejs 14

this works

**Comment by FisherWu29** [comment]
> > Closing this due to lack of details.
> 
> 请切换到其他版本的nodejs来尝试构建 Please switch to a different version of nodejs to try building it
> 
> such as nodejs 14

works, thank u

**Comment by DEVTomatoCake** [comment]
To anyone wanting to get it working on Windows on more recent versions of Node.js, these are the steps I've taken on commit https://github.com/GoogleChromeLabs/squoosh/commit/d87eff7645c151c2f4365c2515c71f4e56ed71ca (latest at the time of writing) to get it working:
1. Open `lib\css-plugin.js` and go to line 163.
2. Replace the `const` with a `let` to allow modification:
3. Add a condition that adds the current disk's letter in front of the string if it's missing:

```diff
- const path = nomalizePath(id.slice(sourcePrefix.length));
+ let path = nomalizePath(id.slice(sourcePrefix.length));
+ if (path.startsWith("\\")) path = "C:" + path
```
Make sure to replace `C` with `D` or whatever disk that project is running on.

4. Run `npm run build`
5. Done

---

To get it running locally, *I* had to take these steps, not sure if they're really required:
1. In package.json, update the `serve` script to use the `./build` folder instead of `.tmp/build/static`:
2. Hardcode the port you want to use as Windows doesn't seem to support setting env vars like it's done in the `dev` script:

```diff
- "serve": "serve --listen=$DEV_PORT --config ../../../serve.json .tmp/build/static",
+ "serve": "serve --listen=5000 --config ../serve.json ./build",
```

3. Run `npm run serve`
4. Done
