### ISSUE TITLE
fitMethod option doesn't work at libSqoosh

### ISSUE THREAD

**Issue by ics-nishihara** [GoogleChromeLabs/squoosh#1209]
**Describe the bug**
I set fitMethod  'contain', but image doesn't crop with libSquoosh.

**To Reproduce**
```
const preprocessOptions = {
  enabled: true,
  width: 800,
  height: 300,
  fitMethod: 'contain',
}

await imagePool.preprocess(preprocessOptions)
```

**Expected behavior**
Applying fitMethod option.

**Version:**
 - OS MacOS m1
 - Node version: 16.2.0
 - npm version: 8.3.0

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
- Original image
![sample1](https://user-images.githubusercontent.com/48976682/150776774-54661175-38c9-4cbc-b187-4052b9804991.jpg)

- Output image from Squoosh
![sample1](https://user-images.githubusercontent.com/48976682/150776838-a002bb04-6e44-4f56-b8d0-2f74cd65bc24.jpg)

**Additional context, screenshots, screencasts**
Squoosh CLI also doesn't work. Will libSquoosh plan to like this?

>We are re-working the crop UI right now, so I won’t fix this right now, but once we have landed the new crop.

https://github.com/GoogleChromeLabs/squoosh/issues/921

Thank you

**Comment by cwaj400** [comment]
Just looking at this as I too have encountered this bug.

Is it the case that "fitMethod" needs to be added in ResizeOptions, line 38, as well as the relevant areas where ResizeOptions is used, such as line 191? All in file:

https://github.com/GoogleChromeLabs/squoosh/libsquoosh/src/codecs.ts

**Comment by LudovicEvrard** [comment]
Hello still have this issue. Do you have any idea when it's fix?

Thanks you,

**Comment by biosocket** [comment]
Also still having this issue.

**Comment by ivorafael** [comment]
+1

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by jaylinski** [comment]
In case this helps someone else: If you want to use `fitMethod: "contain"` in libsquoosh, you can patch the `preprocessImage()`-function in `node_modules/@squoosh/lib/build/index.js`. Here's a helper function for that:

```js
/**
 * Applies the following patches to libsquoosh:
 * * Support `fitMethod: "contain"`
 */
export async function patchLibSquoosh() {
  const fitMethodPatchFile = 'node_modules/@squoosh/lib/build/index.js';
  const fitMethodPatch = `function crop(data, sx, sy, sw, sh) {
    const inputPixels = new Uint32Array(data.data.buffer);
    // Copy within the same buffer for speed and memory efficiency.
    for (let y = 0; y < sh; y += 1) {
      const start = (y + sy) * data.width + sx;
      inputPixels.copyWithin(y * sw, start, start + sw);
    }
    return new ImageData(new Uint8ClampedArray(inputPixels.buffer.slice(0, sw * sh * 4)), sw, sh);
  }
  function getContainOffsets(sw, sh, dw, dh) {
    const currentAspect = sw / sh;
    const endAspect = dw / dh;
    if (endAspect > currentAspect) {
      const newSh = sw / endAspect;
      const newSy = (sh - newSh) / 2;
      return {
        sw,
        sh: newSh,
        sx: 0,
        sy: newSy
      };
    }
    const newSw = sh * endAspect;
    const newSx = (sw - newSw) / 2;
    return {
      sh,
      sw: newSw,
      sx: newSx,
      sy: 0
    };
  }
  async function preprocessImage({preprocessorName, options, image}) {
    const preprocessor = await preprocessors[preprocessorName].instantiate();
    const data = image.bitmap;
    let input = data;
    if (options.fitMethod === 'contain') {
      const {sx, sy, sw, sh} = getContainOffsets(data.width, data.height, options.width, options.height);
      input = crop(input, Math.round(sx), Math.round(sy), Math.round(sw), Math.round(sh));
    }
    image.bitmap = await preprocessor(Uint8Array.from(input.data), input.width, input.height, options);
    return image;
  }`;
  const data = await readFile(fitMethodPatchFile, 'utf8');
  const result = data.replace(/async function preprocessImage\({preprocessorName.+image}/, fitMethodPatch);
  await writeFile(fitMethodPatchFile, result, 'utf8');
}
```
