### ISSUE TITLE
Regression in 0.4.1: File has an unsupported format

### ISSUE THREAD

**Issue by simon-peek-poke** [GoogleChromeLabs/squoosh#1221]
**Describe the bug**
Since the latest release (0.4.1) libsquoosh has stopped recognising PNG images. This seems to happen with all PNG images and they all worked with version 0.4.0. The encode step fails with error `File has unsupported format`. This may happen with other formats but this is the only one I am currently using. It seems there are around 7 months worth of changes in the latest release so it's not easy to see where in the code the problem might have been introduced.

**To Reproduce**
1. `const img = pool.ingestImage(imagePath);`
    `await img.encode({oxipng: {}});`
2. See error "File has unsupported format"

**Expected behavior**
PNG images are processed as in version 0.4.0.

**Version:**
 - OS w/ version: Windows 10
 - Browser w/ version Node
 - Node version: 16.13.1
 - npm version: 8.3.0

**Comment by simon-peek-poke** [comment]
Just as I posted this I noticed something in the docs - the ingestImage function takes an ArrayBuffer, not a path. Reading the file first then passing this to ingestImage works as expected.

I'm not sure if this changed recently but since it was working before, the current release probably shouldn't have been a patch release as it is a breaking change.

**Comment by jakearchibald** [comment]
Thanks for the report. I've deprecated 0.4.1, and will republish once I've figured everything out.

I wasn't aware that breaking changes were made since the last publish, sorry.

**Comment by jakearchibald** [comment]
The breaking changes are from https://github.com/GoogleChromeLabs/squoosh/pull/1123.

Again, sorry about this.

**Comment by simon-peek-poke** [comment]
Thanks for looking into it. It's not too much of an issue now I know the problem and how to get around it. 

Are we expecting going forward that `ingestImage()` will continue to take an `ArrayBuffer` instead of a path?

**Comment by jakearchibald** [comment]
Yeah, I'll land the changes as 0.5.0. The idea was to keep libsquoosh as free of node APIs as possible.
