### ISSUE TITLE
@squoosh/cli crash in conversion to jxl

### ISSUE THREAD

**Issue by raid** [GoogleChromeLabs/squoosh#1222]
**Describe the bug**
Converting to JXL with cli crashes with error `JXL_CHECK: bytes_.get()`.  Input is a fully white PNG of the dimensions 4535 x 6307  Pixels (28.60 MPixels). 

```
PS C:\Temp\test\jxl slow sq> squoosh-cli.cmd --jxl "{}" .\weiß.png
⠋ (node:8188) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 25 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8188) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 25 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:8188) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 25 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:8188) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 25 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
0/1 ⠹ ▐▨▨▨▨▨╌╌╌╌╌▌ Encoding (24 threads)
 .\weiß.png: 3.53KB/src/node_modules/jxl/lib/jxl/image.cc:102: JXL_CHECK: bytes_.get()
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "unreachable".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v17.5.0
```

**To Reproduce**
1. run  `squoosh-cli.cmd --jxl "{}" .\weiß.png`

**Expected behavior**
A working conversion to jxl, like with cjxl or vips. Like the attached weiss-cjxl. 

**Version:**
 - OS w/ version: Microsoft Windows [Version 10.0.22000.527]
 - Browser w/ version: n/a
 - Node version :v17.5.0
 - npm version: 8.4.1

**Additional context, screenshots, screencasts**
![weiß](https://user-images.githubusercontent.com/231783/154778378-bd134bcd-7cd6-448e-b0f0-b926df4b1c91.png)
[weiß-cjxl.zip](https://github.com/GoogleChromeLabs/squoosh/files/8101146/weiss-cjxl.zip)

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
