### ISSUE TITLE
Unwanted Black Border

### ISSUE THREAD

**Issue by valhuber** [GoogleChromeLabs/squoosh#1233]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
On Mac, a black border is added to a clean screen shot.

(Aside - thanks so much for doing this project... it's saving my bacon on DZone)

**To Reproduce**
1. Shift command 4 on browser
2. Squoosh
3. Download

**Expected behavior**
No border

**Version:**
 - OS w/ version: MacOS 12.3.1
 - Browser w/ version Edge 99.0.1150.55
 - Node version:v14.17.4
 - npm version: 6.14.14

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
- Original image 
<img width="1260" alt="LogicDoc" src="https://user-images.githubusercontent.com/5579631/161352870-c46d3faf-ebc4-49f5-8e42-509fcc7edca0.png">

- Output image from Squoosh

![LogicDoc After](https://user-images.githubusercontent.com/5579631/161352894-567793a5-c689-4635-8ec1-58533609990e.jpg)

**Additional context, screenshots, screencasts**

**Comment by atjn** [comment]
This happens because your original PNG image has a border of transparent pixels, but JPG doesn't support transparency, so Squoosh simply transforms them into black pixels. If you choose any other compression format, you can preserve the transparent pixels. Alternatively, you can edit the original image to remove or fill the transparent areas.

**Comment by Diti** [comment]
You can take screenshots without the drop shadow on macOS by also holding the _option_ key before you click on the window. <kbd>⌘</kbd> + <kbd>⌥</kbd> + <kbd>4</kbd>. Now your JPEG images won’t get the black border.

**Comment by jakearchibald** [comment]
https://github.com/GoogleChromeLabs/squoosh/issues/1233#issuecomment-1090493239 is correct. Use a different format if you want transparency.
