### ISSUE TITLE
config "quality" setting for AVIF files doesn't affect generated file size 

### ISSUE THREAD

**Issue by yurylavrukhin** [GoogleChromeLabs/squoosh#1238]
**Before you start**

Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:
✅ 

**Describe the bug**
Squoosh CLI: quality setting doesn't affect AVIF file size output, but works with WEBP
<img width="1061" alt="Screen Shot 2022-04-23 at 20 12 15" src="https://user-images.githubusercontent.com/26966797/164896243-24b11234-f2a0-4912-a4a0-f861b011a79e.png">

**To Reproduce**
1. open terminal, make sure you have node.js installed
2. download any PNG image to your local disk on your computer
3. run squoosh CLI to this PNG image on your local computer `npx @squoosh/cli --avif '{"quality":40}' [path-to-your-image].png`, note the generated AVIF file size
4. THIS TIME QUALITY = 50, run squoosh CLI to this PNG image on your local computer `npx @squoosh/cli --avif '{"quality":50}' [path-to-your-image].png`, note the generated AVIF file size
5. expected to get a larger size with quality 50, but got the same AVIF file size

**Expected behavior**
i expected to get different size AVIF images with different `quality` setting

**Version:**
 - OS w/ version: MacOS 12.3.1 (21E258)
 - Browser w/ version -
 - Node version: 16.14.2
 - npm version: 8.5.0

**Is your issue related to the quality of image compression?**
YES
- Original image 
![js](https://user-images.githubusercontent.com/26966797/164896416-ddd4dea2-1237-4de9-a966-7a0550664b16.png)

- Output image from Squoosh
github doesn't support AVIF, i can't attach it, try to generate yourself with the command above

**Additional context, screenshots, screencasts**

**Comment by Necko1996** [comment]
Have the same issue...

**Comment by nucliweb** [comment]
The correct quality parameter for AVIF image format is `cqLevel` and the range is between [0 and 63](https://github.com/GoogleChromeLabs/squoosh/blob/dev/codecs/avif/enc/avif_enc.cpp#L9-L12).

The best way to get the config parameters is to export them with `Copy npx command` feature.

## Squoosh app


![squoosh](https://user-images.githubusercontent.com/1307927/177281488-14ee64b4-a3f9-4caa-ac58-3ea485a313db.png)

## npx command

```bash
npx @squoosh/cli --avif 
'{"cqLevel":23,
  "cqAlphaLevel":-1,
  "subsample":1,
  "tileColsLog2":0,
  "tileRowsLog2":0,
  "speed":6,
  "chromaDeltaQ":false,
  "sharpness":0,
  "denoiseLevel":0,
 "tune":0}'
```

You can see that the image has a `Quality` 40, and the `cqLevel` is 23. Is the difference between 40 and 63 (the max level)

<hr>

## Try to use these commands

To get difference sizes, try to use these commands

```bash
npx @squoosh/cli --avif '{"cqLevel":23}' [path-to-your-image].png
npx @squoosh/cli --avif '{"cqLevel":33}' [path-to-your-image].png
```

![squoosh-cli](https://user-images.githubusercontent.com/1307927/177283313-0679f181-a39c-43f7-b6a3-eb48251fdf07.png)

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
