### ISSUE TITLE
add support for node engine 18 for @squoosh/lib

### ISSUE THREAD

**Issue by pumano** [GoogleChromeLabs/squoosh#1242]
**Is your feature request related to a problem? Please describe.**
Problem when l need to use `--ignore-engines` flag for using `@squoosh/lib` with nodejs 18

**Describe the solution you'd like**
add support nodejs 18 to:

https://github.com/GoogleChromeLabs/squoosh/blob/dev/libsquoosh/package.json#L22-L24

**Does other service/app have this feature?**
Add any service you know/use that has this feature (We want to know for research)
https://github.com/bcheidemann/squoosh-webpack-plugin
**Additional context**

**Comment by dasa** [comment]
This change may be need too: https://github.com/emscripten-core/emscripten/pull/16917

**Comment by drcmda** [comment]
Can somebody confirm if this mean that when a package is published relying on squoosh it will crash the package on the client if they don't have node 14 or 16? I was about to use squoosh in a published gltf converter.

**Comment by Cyclic** [comment]
Any updates on this? Is there a workaround for now? Thank you in advance.

**Comment by donmccurdy** [comment]
Please let us know if a PR would be welcome for this issue. Thanks! 🙏

**Comment by jpchatt** [comment]
Upvote this

**Comment by devinmatte** [comment]
I filed https://github.com/GoogleChromeLabs/squoosh/issues/1265 but I suspect my issue is actually related to using Node 18

**Comment by message** [comment]
bump

**Comment by rodoabad** [comment]
Are we just thinking of updating the engine rules? No changes needed from squoosh itself?

Switching to Node 18, I get this error.

```
TypeError: Failed to parse URL from /foo/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm
    at Object.fetch (node:internal/deps/undici/undici:11118:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
```

**Comment by rodoabad** [comment]
Found the issue - https://github.com/GoogleChromeLabs/squoosh/issues/1033.

**Comment by meotimdihia** [comment]
I am getting this error too.
```
TypeError: Failed to parse URL from ......./node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm
```
Node.js 18

**Comment by chr33s** [comment]
work around for node >= 18, run `node --no-experimental-fetch ./script.js`

**Comment by xavierfoucrier** [comment]
Hello @GoogleChromeLabs team!
cc @surma @jakearchibald 😸 

Any news about `NodeJS 18` support? This is a serious issue.
I was surprised that the latest version of Squoosh was published more than a year ago..

> The v16 is now in "maintenance" mode and will be dropped 2023.
> See https://github.com/nodejs/release#release-schedule.

**Comment by limenote** [comment]
> work around for node >= 18, run `node --no-experimental-fetch ./script.js`

can you share your ./scripts.js ? or a sample code ?
thanks

**Comment by chr33s** [comment]
@limenote simply run node with the --no-experimental-fetch flag, and don't rely on the native fetch implementation.

**Comment by cristianvasquez** [comment]
but is squoosh to be supported?

**Comment by JacobWeisenburger** [comment]
running `--no-experimental-fetch` worked for me

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.

**Comment by JacobWeisenburger** [comment]
@jakearchibald
Does the [squoosh.app](https://squoosh.app/) web app support rest endpoints or some way of using it programmatically?

**Comment by websours** [comment]
@jakearchibald Can you or someone else suggest some good alternatives to @squoosh/lib?

**Comment by donmccurdy** [comment]
@websours if you need similar functionality in a library format for Node.js, I would consider [Sharp](https://sharp.pixelplumbing.com/), which is based on [libvips](https://github.com/libvips/libvips). There appears to be some [effort underway](https://github.com/kleisauke/wasm-vips) to bring libvips to WASM for web browsers as well. Since Node.js 18 is the subject of the thread here, I've confirmed that Sharp is working fine in that environment.

**Comment by JacobWeisenburger** [comment]
thanks

**Comment by xavierfoucrier** [comment]
@jakearchibald sad, but that's so reflective of the reality of open source projects right now, see project like Atom inside Github team...

Anyway, thanks a lot for letting us know! 🙏 😉

**Comment by jakearchibald** [comment]
@JacobWeisenburger 

> @jakearchibald Does the [squoosh.app](https://squoosh.app/) web app support rest endpoints or some way of using it programmatically?

It doesn't. It's entirely client side. Part of the privacy benefits is the image doesn't leave your device.

**Comment by JacobWeisenburger** [comment]
Sounds good. thanks.

**Comment by ecelliitbhu** [comment]
I'm using yarn to build my Next.js application using the command `yarn build` and getting this error. How could I run `--no-experimental-fetch ` with yarn?

**Comment by burlackoff** [comment]
> I'm using yarn to build my Next.js application using the command `yarn build` and getting this error. How could I run `--no-experimental-fetch ` with yarn?

"build": "NODE_OPTIONS=--openssl-legacy-provider NODE_OPTIONS=--no-experimental-fetch next build"

its work for me
