### ISSUE TITLE
Photographer needs help installing

### ISSUE THREAD

**Issue by CantCode4JackShit** [GoogleChromeLabs/squoosh#1257]
Hello there, I'm a photographer trying to install squoosh on a MAC via terminal and I'm getting the response below. Any assistance on pushing forward would be greatly appreciated.

LVHQWS-EDIT-503:admin rbrian$ npm i -g @squoosh/cli
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/@squoosh
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@squoosh'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@squoosh'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/@squoosh'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rbrian/.npm/_logs/2022-07-04T14_49_33_872Z-debug-0.log

**Comment by nucliweb** [comment]
Hi @CantCode4JackShit 👋🏼

The problem is that the command don't have permissions. You can see the message `permission denied`, so to install globally you need to use the root permissions.

Try to run next command in your terminal:
```
sudo npm install -g @squoosh/cli
```

And enter your system password, let me know if this command fix the problem.

**Comment by CantCode4JackShit** [comment]
> sudo npm install -g @squoosh/cli

That worked. Thank you very much! 

There is one more thing I cant figure out now.  When I'm trying to save a batch to a folder on my desktop I'm getting the message below. I'm trying to save the images to a folder on my desktop and putting in this code after the CLI command then this;

-d ‘../optimize_images *.jpg

[Error: ENOENT: no such file or directory, lstat 'optimize_images'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'optimize_images'

**Comment by nucliweb** [comment]
I'm not sure if is a typo in the comment or you have a `'` in the command.

Btw, to have more context, can you share the foldet structure, and the complete command?

**Comment by nucliweb** [comment]
I just tried this command, and works fine for me

```bash
squoosh-cli --avif auto -d ../optimized-images *.jpg
```

**Comment by CantCode4JackShit** [comment]
> ```shell
> --avif auto -d ../optimized-images *.jpg
> ```

I'm going to try it later and I'll let you know. Thanks for the assist here!

**Comment by CantCode4JackShit** [comment]
this is what i got after trying the command you sent. I was promoted for a password but not sure If it was properly installed. I'm still not able to run the action. 

Last login: Mon Jul  4 19:36:31 on ttys000
LVHQWS-EDIT-503:~ rbrian$ sudo npm install -g @squoosh/cli
Password:
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 37 packages, and audited 38 packages in 825ms

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
LVHQWS-EDIT-503:~ rbrian$

**Comment by nucliweb** [comment]
Ok, this command install the Squoosh in your system.
What is the command that you are running to compress de images?

**Comment by CantCode4JackShit** [comment]
> Ok, this command install the Squoosh in your system. What is the command that you are running to compress de images?

i nucliweb, So I did have someone of a success processing a batch today. The folder I'm attempting to batch is 41 images and only shot out 3 processed.  See my comand lines below.  I'm getting closer.

Last login: Tue Jul  5 10:15:33 on ttys000
LVHQWS-EDIT-503:ARCHITECTURE_SAMPLES rbrian$ npx @squoosh/cli --resize '{"enabled":true,"width":1920,"height":1181,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --mozjpeg '{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75}' -d ../optimized-images *.jpg
⠋ (node:2785) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2785) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:2785) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:2785) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
3/3 ✔ Squoosh results:
 Asheville_Architectural_Exterior_Photography_0001.jpg: 331.85KB
  └ ../optimized-images/Asheville_Architectural_Exterior_Photography_0001.jpg → 258.78KB (78.0%)
 REAL ESTATE INSIDER DEC01-18_RB_003.jpg: 1.15MB
  └ ../optimized-images/REAL ESTATE INSIDER DEC01-18_RB_003.jpg → 239.50KB (20.4%)
 REAL ESTATE INSIDER DEC01-18_RB_006.jpg: 1.17MB
  └ ../optimized-images/REAL ESTATE INSIDER DEC01-18_RB_006.jpg → 246.15KB (20.5%)

**Comment by nucliweb** [comment]
Can you check if the rest of the images have the extension `.jpg` or `.JPG` and not `.jpeg` or `.JPEG`?

Btw, after install `squoosh` globally, you can use the command `squoosh-cli` instead of `npx @squoosh/cli`

**Comment by rudolphos** [comment]
> photographer

@CantCode4JackShit FYI, if you ever plan to organize or search your compressed photo collection based on date taken, ISO, lens, etc parameters, you can forget about it since Squoosh removes EXIF and other metadata and there is no way to preserve it.

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
