### ISSUE TITLE
Better type checking for cleanMerge/cleanSet

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#126]
It'd be nice to enforce calling `cleanMerge<MergeObjType>(obj, keyPath, mergeObj)` and ensure that `mergeObj` is a partial of `MergeObjType`.

I couldn't get that to work in TypeScript, but maybe there's a way in TypeScript 3?

**Comment by jakearchibald** [comment]
As @developit said, https://github.com/mweststrate/immer/ is the right solution here. I wonder how big it is without the older-browser parts.

Not needed for v1 though.

**Comment by surma** [comment]
Can we close this?

**Comment by jakearchibald** [comment]
Yeah fuck it
