### ISSUE TITLE
Web library for Squoosh

### ISSUE THREAD

**Issue by radulle** [GoogleChromeLabs/squoosh#1269]
In `@squoosh/lib` description in `package.json` says `A Node library for Squoosh`.

Would having `A Web library for Squoosh` make sense?

I see there might be a need for good quality client side resize, rotate, crop and compression (WebP, MozJPEG, Avif, etc). Usage example would be resizing and compression of photos prior to uploading them to server thus reducing server load and bandwidth usage.

**Comment by Ben-Mack** [comment]
Big +1 for this, there's currently no JS image compression lib nearly as good as what Squoosh is providing. 
Related: https://github.com/GoogleChromeLabs/squoosh/issues/1084

**Comment by radulle** [comment]
Thank you for pointing this issue. I see there has been very little progress for a long time :(

There is this https://github.com/kleisauke/wasm-vips alternative library but it's size makes it unusable on web.

On a sidenote I found this good use of Squoosh codecs https://github.com/discourse/discourse/pull/13432 & https://blog.discourse.org/2021/07/faster-user-uploads-on-discourse-with-rust-webassembly-and-mozjpeg/.

**Comment by jakearchibald** [comment]
I'm happy for someone else to use the wasm codecs in this repo to make a web library, but it isn't something I have time to take on personally right now.
