### ISSUE TITLE
Image successful converted using the web app but not in the command line

### ISSUE THREAD

**Issue by cchavez** [GoogleChromeLabs/squoosh#1271]
I have some image that is converted to **webp** or **avif** in the **web app** but it get stuck in the **command line**, also in some code that I wrote the error displayed is **Unsupported color conversion request** and the application get stuck as well.

For the web app I did:
- Downloaded the latest code.
- Built the web application: `npm install`, `npm run build`.
- Ran the web app: `npm run dev`.
- Upload the image.
- Select **webp** or **avif**
- Download the image

For the command line I did:
- Downloaded the latest code.
- Built the web application.
- Built libsquoosh: `cd libsquoosh`,  `npm install`, `npm run build`.
- Built cli: `cd cli`, `npm install`.
- In the cli directory Ran the command: `node src/index.js --avif "{cqLevel: 33, cqAlphaLevel: -1, denoiseLevel: 0, tileColsLog2: 0, tileRowsLog2: 0, speed: 6, subsample: 1, chromaDeltaQ: false, sharpness: 0, tune: 0}" --output-dir /home/cchavez/Descargas/libSquoosh/ /home/cchavez/Descargas/libSquoosh/1.jpeg`
- The command line get stuck in: `0/1 ⠴ ▐╌╌╌╌╌╌╌╌╌╌▌ Decoding...`

My environment is:
 - OS: Fedora 34.
 - Node version: v16.5.0
 - npm version: 7.19.1
 - nvm version: v0.39.1

In the command line there is no error displayed but I think is the same error as in my piece of code which is **Unsupported color conversion request** and the application get stuck, the thing is that when I use the web application the same image is converted correctly, I tried to see if there additional parameter in the web app but I was not able to figure out if something is missed.

The following image works in the web app but didn't work in the command line:

![1](https://user-images.githubusercontent.com/913511/183817340-89f10c6a-84f8-47a2-aeba-774a97e09aa5.jpeg)

The following image works in the web app and in the command line with the same parameters:

![2](https://user-images.githubusercontent.com/913511/183817448-684cdcfd-b35a-4411-941e-2c25543bd808.jpeg)

**Comment by cristianvasquez** [comment]
I also get this error, `Unsupported color conversion request`, but in a Web application. 

The problem is that this error cannot be caught,  and crashes the application.

**Comment by koseki** [comment]
This will be the same problem with
 * #1043

The CMYK image causes a hang-up.

```js
const squoosh = require('@squoosh/lib');
const fs = require('fs').promises;

(async function() {
  const imagePool = new squoosh.ImagePool();
  const imageFile = await fs.readFile('cmyk.jpg');
  const image = imagePool.ingestImage(imageFile);
  console.log(await image.decoded);

  await imagePool.close();
})();
```

```console
$ npx node ./test.js
Unsupported color conversion request
^C
```

**Comment by meotimdihia** [comment]
Why don't developers care about this? Did they stop fixing problems?

**Comment by cristianvasquez** [comment]
I don't think is developed anymore...

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
