### ISSUE TITLE
Allow PinchZoom to be "controlled" via property changes

### ISSUE THREAD

**Issue by developit** [GoogleChromeLabs/squoosh#128]
right now we have to use a `componentDidUpdate()` hook to invoke `PinchZoom.setTransform({ scale })`. It would be lovely to be able to re-render `<pinch-zoom scale={newScale}>` and have it update in-place.  For property-driven changes to transform, it'd be good to assume centering (#129).

**Comment by jakearchibald** [comment]
I think we addressed this with additional methods and events. Reopen if not.
