### ISSUE TITLE
better compression ratio for png images ( preserve transparency)

### ISSUE THREAD

**Issue by GorvGoyl** [GoogleChromeLabs/squoosh#1280]
**Is your feature request related to a problem? Please describe.**
problem: I need to compress png images with output as png to preserve transparency. Squoosh tool is quite good at compressing images when the output is a jpeg but not a png.

**Describe the solution you'd like**
better compression option for png images (preserve transparency)

**Does other service/app have this feature?**
below tools compress PNGs with a much better compression ratio w/o losing quality. 
- https://compresspng.com/ 
- https://tinypng.com/

I believe squoosh can at least achieve the same compression ratio, if not better.

**Comment by surma** [comment]
Squoosh does support PNG (select “OxiPNG”!). Does that not work for you?
![Screenshot 2022-08-30 at 17 31 43](https://user-images.githubusercontent.com/234957/187491080-e778843f-d392-42f1-97a4-41e43b744ab5.png)

**Comment by jakearchibald** [comment]
WebP and AVIF also support transparency, and are supported in Squoosh.

To improve compression in PNG and lossless WebP, also use "reduce palette".

**Comment by GorvGoyl** [comment]
reduce palette did the trick!

**Comment by jakearchibald** [comment]
Cool, that's what https://compresspng.com/ and https://tinypng.com/ are doing, but Squoosh gives you more control.
