### ISSUE TITLE
Scrubber arrow svg is large and oversized on Chrome 105+

### ISSUE THREAD

**Issue by aisgbnok** [GoogleChromeLabs/squoosh#1281]
### Describe the bug

The arrows on the scrubber for comparing the side by size images is large and oversized.

### To Reproduce
1. Update to Chrome 105
1. Go to [https://squoosh.app/](https://squoosh.app/)
1. Add an image, to get to [https://squoosh.app/editor](https://squoosh.app/editor)
1. See error

### Expected behavior

Scrubber arrows should be sized correctly.

### Version:
 - OS w/ version: Windows 11 22622.586
 - Browser w/ version: Chrome 105.0.5195.54
 - Node version: 16.14.2
 - npm version: 8.5.0

### Additional context, screenshots, screencasts

![image](https://user-images.githubusercontent.com/10838153/187730091-0099bad7-3adc-49d0-93a0-370d31663823.png)

I tested this on a device running Chrome 104 and the issue was not apparent. Upon updating to Chrome 105 the arrows are now out of place and oversized. I might be able to look into this later in the week, but anyone else is free to make a PR and resolve this. Thanks. 👍

**Comment by azanatta** [comment]
We're having the same issue with 105 and svg icons displayed in flex, I've reproduced it in jsfiddle and opened a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1358807

**Comment by jakearchibald** [comment]
Thanks both. I can reproduce this issue. I'll get a fix together shortly.

**Comment by aisgbnok** [comment]
@jakearchibald, thank you for fixing this so quickly!
