### ISSUE TITLE
SyntaxError: JSON5: invalid

### ISSUE THREAD

**Issue by rawriddims** [GoogleChromeLabs/squoosh#1284]
I'm running on Windows10 PowerShell:

```
PS C:\Users\ricca\OneDrive\Desktop\TEST\5\webp\3840> npx @squoosh/cli --resize '{"enabled":true,"width":3840,"method":"lanczos3","fitMethod":"stretch","premultiply":true,"linearRGB":true}' --quant '{"enabled":true,"zx":0,"maxNumColors":30,"dither":1}' --webp '{"quality":5,"target_size":0,"target_PSNR":0,"method":6,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":10,"show_compressed":0,"preprocessing":1,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' -d './3840-optimized' 3840x2160__ImageOptim_Low_quality.jpg
0/1 \ ▐╌╌╌╌╌╌╌╌╌╌▌ Decoding...
C:\Users\ricca\AppData\Local\npm-cache\_npx\b1ab43f351106b51\node_modules\json5\lib\parse.js:1083
    const err = new SyntaxError(message)
                ^

SyntaxError: JSON5: invalid character 'l' at 1:33
    at syntaxError (C:\Users\ricca\AppData\Local\npm-cache\_npx\b1ab43f351106b51\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Users\ricca\AppData\Local\npm-cache\_npx\b1ab43f351106b51\node_modules\json5\lib\parse.js:1028:12)
    at Object.value (C:\Users\ricca\AppData\Local\npm-cache\_npx\b1ab43f351106b51\node_modules\json5\lib\parse.js:287:15)
    at lex (C:\Users\ricca\AppData\Local\npm-cache\_npx\b1ab43f351106b51\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Users\ricca\AppData\Local\npm-cache\_npx\b1ab43f351106b51\node_modules\json5\lib\parse.js:25:17)
    at Command.processFiles (file:///C:/Users/ricca/AppData/Local/npm-cache/_npx/b1ab43f351106b51/node_modules/@squoosh/cli/src/index.js:137:49) {
  lineNumber: 1,
  columnNumber: 33
}
```
Does it depend on my node_module or is my command wrong? Thanks.

**Comment by rawriddims** [comment]
If you have keys with string parameters, like "method":"lanczos3" or "fitMethod":"stretch". You need to escape quotes from the key value, like "method":\"lanczos3\" or "fitMethod":\"stretch\". As said [here](https://github.com/GoogleChromeLabs/squoosh/issues/1181#issuecomment-1177198132), and it works:

`npx @squoosh/cli --resize '{"enabled":true,"width":3840,"height":2160,"method":\"lanczos3\","fitMethod":\"stretch\","premultiply":true,"linearRGB":true}' --quant '{"enabled":true,"zx":0,"maxNumColors":40,"dither":1}' --webp '{"quality":10,"target_size":0,"target_PSNR":0,"method":6,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":10,"show_compressed":0,"preprocessing":1,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' -d './3840-optimized' 3840x2160__ImageOptim_Low_quality.jpg`

Now I have to find a way to run it in batch for different files with different sizes. Any idea?

Also a rename file value would be usefull. There's one?

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
