### ISSUE TITLE
Expose OxiPNG interlacing flag

### ISSUE THREAD

**Issue by NotWoods** [GoogleChromeLabs/squoosh#1288]
**Is your feature request related to a problem? Please describe.**
I'd like to quickly add interlacing to a PNG. Interlacing can help with perceived load times since it renders something onto the page sooner, even though the overall image becomes larger.

**Describe the solution you'd like**
OxiPNG has an existing CLI flag to add or remove interlacing from a PNG file. (The default option is to match the input file.) I'd like to add a new checkbox to the OxiPNG UI to set this flag.

**Does other service/app have this feature?**
It's exposed in Photoshop, GIMP, and Inkscape export dialogs but I'm not aware of online services that offer it

**Additional context**
https://github.com/shssoichiro/oxipng

**Comment by jakearchibald** [comment]
It's already there?

**Comment by NotWoods** [comment]
Wow, I can't see. Thanks!
