### ISSUE TITLE
Displayed file size of 'Original Image' vastly different to file size reported on file system 

### ISSUE THREAD

**Issue by benfrain** [GoogleChromeLabs/squoosh#1297]
Unsure if I am misunderstanding what 'Original Image' size should be representing. I had assumed the file size before Squoosh does anything with it?

**Describe the bug**
Displayed file size of 'Original Image' vastly different to file size reported on file system 

**To Reproduce**
1. Grab a largish jpg from your file system and paste it into Squoosh
2. Note 'Original Image' file size reported by Squoosh (my example says 805Kb)
3. Check the file size reported by the OS for said image (mine shows 181Kb)

**Expected behavior**
File sizes reported by Squoosh to broadly match those reported by the OS.

**Version:**
 - OS w/ version: [e.g. Mac 12.6.1]
 - Browser w/ version Chrome Version 107.0.5304.110
 - Node version: [16.13.2]
 - npm version: [8.1.2]

**Comment by jakearchibald** [comment]
Can you give me an example image that shows this issue?

**Comment by jakearchibald** [comment]
Ah, I see the problem:

> paste it into Squoosh

This is caused by the operating system rencoding the image when it puts it in the clipboard. If you want Squoosh to receive the file unmodified by the operating system, use the file picker or drag & drop.
