### ISSUE TITLE
Switch to DomMatrix/WebkitCSSMatrix Expose a transform matrix on the pinch-zoom

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/squoosh#130]
I had to read x, y and scale properties and work out how the transforms were applied... I believe if we expose the DOM Matrix of the transform it will be easier to reason what has happened to the image and not have to worry about how all the transforms were applied.

Thoughts from meeting... Make it readonly for now so people can't apply rotations and skews etc to the image.

**Comment by jakearchibald** [comment]
Can you go into a little more detail on why this is useful?

Right now I use an SVG matrix because it has better browser support, but I'd like to move to DOMMatrix at some point. Exposing it publicly might make that harder.

Either that, or I polyfill DOMMatrix, but that seems like a jump in complexity.

**Comment by PaulKinlan** [comment]
Yep. It's totally not needed for v1, it would be nice to add when we make
this a standalone WC

**Comment by jakearchibald** [comment]
I was against doing this because of the lack of `DOMMatrix` support, and I didn't want to expose the old SVG type. However, it looks like support is good for the Webkit version. https://caniuse.com/#feat=dommatrix

**Comment by kosamari** [comment]
@developit would you be able to move this issue to https://github.com/GoogleChromeLabs/pinch-zoom repo? I don't seem to have access to "transfer this issue [beta]" btn

**Comment by kosamari** [comment]
Closing this one since component is in separate repo
