### ISSUE TITLE
Error on Batch Convert

### ISSUE THREAD

**Issue by chrisativonne** [GoogleChromeLabs/squoosh#1304]
Using the following command to batch convert all contents of a folder from .jpg to .webp
% npx @squoosh/cli --webp auto -d squooshed2 ./

Error/message is as follows:
`(node:25186) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/deps/undici/undici:11118
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /usr/local/lib/node_modules/@squoosh/cli/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm
    at Object.fetch (node:internal/deps/undici/undici:11118:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at instantiateAsync (/usr/local/lib/node_modules/@squoosh/cli/node_modules/@squoosh/lib/build/index.js:28:11469)
      at createWasm (/usr/local/lib/node_modules/@squoosh/cli/node_modules/@squoosh/lib/build/index.js:28:12079)
      at /usr/local/lib/node_modules/@squoosh/cli/node_modules/@squoosh/lib/build/index.js:28:35216 {
    input: '/usr/local/lib/node_modules/@squoosh/cli/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.12.1`

**Comment by chrisativonne** [comment]
Updated:

Command is now:
% sudo npx @squoosh/cli --webp '{"quality":1,"target_size":0,"target_PSNR":0,"method":4,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}''./'  -d '../optimized'

Error is now:
error: missing required argument 'files'

**Comment by shatterproof** [comment]
Use Node v16 instead as a workaround, v18 is not yet supported (ran into this issue myself yesterday)

**Comment by chrisativonne** [comment]
I can't seem to get it to work with v16. Same error is:
error: missing required argument 'files'

**Comment by guarnacciaa** [comment]
I'm getting the same error right after installation:

`error: missing required argument 'files'
`

Even in Debian bullseye using:

# node --version
v12.22.12

# npm --version
7.5.2


Log:

280 timing reifyNode:node_modules/@squoosh/lib Completed in 3882ms
281 timing reify:unpack Completed in 3886ms
282 timing reify:unretire Completed in 1ms
283 timing build:queue Completed in 4ms
284 timing build:link:node_modules/@squoosh/cli Completed in 5ms
285 timing build:link:node_modules/json5 Completed in 4ms
286 timing build:link Completed in 6ms
287 timing build:deps Completed in 11ms
288 timing build Completed in 11ms
289 timing reify:build Completed in 11ms
290 timing reify:trash Completed in 0ms
291 timing reify:save Completed in 13ms
292 timing reify Completed in 9344ms
293 timing command:exec Completed in 23364ms
294 verbose stack Error: command failed
294 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
294 verbose stack     at ChildProcess.emit (events.js:314:20)
294 verbose stack     at maybeClose (internal/child_process.js:1022:16)
294 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
295 verbose pkgid squoosh@2.0.0
296 verbose cwd /root/squoosh
297 verbose Linux 5.15.60-2-pve
298 verbose argv "/usr/bin/node" "/usr/share/nodejs/npm/bin/npm-cli.js" "exec" "--" "@squoosh/cli"
299 verbose node v12.22.12
300 verbose npm  v7.5.2
301 error code 1
302 error path /root/squoosh
303 error command failed
304 error command sh -c squoosh-cli
305 verbose exit 1

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
