### ISSUE TITLE
Resize preprocessor

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#131]
Not for V1, but resizing is an important part of image optimisation, and there are multiple techniques available.

We should do bilinear, bicubic, lanczos, and one or two of the pixel-art scalers https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms.

For the comparison to work, we'd set the width/height of the image to be equal to the original, so the left/right appear the same size.

**Comment by jakearchibald** [comment]
https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/resize.c - this looks like a good place to start. `ResizeImage()`

**Comment by jakearchibald** [comment]
Some pretty amazing docs too https://www.imagemagick.org/Usage/filter/.

**Comment by jakearchibald** [comment]
I've added browser resizing, but we should add third-party resizing at some point.

**Comment by kosamari** [comment]
Closing this issue for now since V1 shipped with resize.
Adding line item for V2 for third-party resizing

**Comment by surma** [comment]
We wanna tackle this again, so reopening.

Also found this: 

https://github.com/PistonDevelopers/resize (Rust, Lanczos3 & Mitchell)

**Comment by jakearchibald** [comment]
Ohh that's very handy. Lanczos3 & Mitchell are the ones I wanted too.

**Comment by surma** [comment]
I got that Rust library working in wasm. Will PR once I have done the rest of the plumbing. 



(Yes, I got bored.)

**Comment by surma** [comment]
Jake and I are working on this on the `rust-resize` branch.

**Comment by jakearchibald** [comment]
Closed in https://github.com/GoogleChromeLabs/squoosh/pull/498
