### ISSUE TITLE
PointerTracker: Gets 'stuck' if dragged outside an iframe

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#132]
https://codepen.io/jaffathecake/pen/pZqzLw?editors=0010

This isn't needed for Squoosh.

**Comment by developit** [comment]
I think I'm seeing this when double-clicking buttons overlaid onto pinch-zoom (not sure).

**Comment by kosamari** [comment]
@developit would you be able to move this issue to https://github.com/GoogleChromeLabs/pointer-tracker repo? I don't seem to have access to "transfer this issue [beta]" btn

**Comment by kosamari** [comment]
closing this since the component is on separate repo
