### ISSUE TITLE
Site not up-to-date with the codebase

### ISSUE THREAD

**Issue by aryanpingle** [GoogleChromeLabs/squoosh#1363]
**Describe the bug**
Recent changes (since commit cd336909fc9fdf31d2ca47991d475e4e736bc752) aren't being deployed to squoosh.app

**To Reproduce**
Open [squoosh.app](https://squoosh.app) in the browser. I've tested with Chrome, Safari and Firefox - all with and without a VPN, none of which seem to be showing the latest changes/features.

**Expected behavior**
Recent changes like the [`save/import settings` buttons](https://github.com/GoogleChromeLabs/squoosh/pull/1359) and the [keyboard navigation PR](https://github.com/GoogleChromeLabs/squoosh/pull/1348) aren't visible on the site.

Most likely an issue with Netlify deploys.

**Version:**
 - OS w/ version: Windows 10
 - Browser w/ version: Chrome v111

**Comment by jakearchibald** [comment]
We deploy from a different branch. I'll review things in the next few days and merge it in.

**Comment by aryanpingle** [comment]
Oh my bad. I've run into a couple of issues with Netlify caches so I thought something went bad here lol. Closing the issue.
