### ISSUE TITLE
@squoosh/lib is failing with node v20.0.0

### ISSUE THREAD

**Issue by carlosq-ordering** [GoogleChromeLabs/squoosh#1365]
**Describe the bug**
I try to run my project with a new version of node and the packages fail when I try to install

**Expected behavior**
Install correctly my dependencies

**Version:**
 - Node version: 20.0.0

**Additional context, screenshots, screencasts**
![image](https://user-images.githubusercontent.com/77166972/234139854-3ed99c23-edc7-48dd-95b8-1124a43dd8a5.png)

**Comment by jakearchibald** [comment]
See https://www.npmjs.com/package/@squoosh/lib - the library is no longer maintained
