### ISSUE TITLE
Dragging zooms after a wheel event on right pane of two-up

### ISSUE THREAD

**Issue by developit** [GoogleChromeLabs/squoosh#137]
Steps to reproduce:

1. open the app, load an image. 
2. drag it via the left pane
3. zoom via mouse wheel over the right pane
4. drag in the right pane
5. drag in the right pane again

**Comment by jakearchibald** [comment]
I can't recreate this on https://squoosh-beta.firebaseapp.com/, can you?

**Comment by surma** [comment]
Can’t repro either

**Comment by developit** [comment]
Hmm, no. I have no idea what the UI branch would have to do with this though..

**Comment by developit** [comment]
I keep seeing this.  It seems to happen if I double-click the right side of two-up and drag on the second click (similar to the android single finger zoom gestures).

**Comment by kosamari** [comment]
@developit I know we worked on bunch before CDS, does this bug still happen to you in currently deployed version of Squoosh?

**Comment by kosamari** [comment]
I believe we don't have this issue anymore
