### ISSUE TITLE
how to start development in local 

### ISSUE THREAD

**Issue by abhinavpatel0** [GoogleChromeLabs/squoosh#1370]
i want to contribute and experiment with the code , can you please help me  on how to start development server in local

after i did npm run dev

i got this

squoosh@2.0.0 dev
DEV_PORT="${DEV_PORT:=5000}" run-p watch serve

'DEV_PORT' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zhEmail** [comment]
how to start development in local
