### ISSUE TITLE
Support paste base64 image data?

### ISSUE THREAD

**Issue by maicss** [GoogleChromeLabs/squoosh#1388]
Looks like you won't add export image as base64 string feature: https://github.com/GoogleChromeLabs/squoosh/issues/317

Any chance you can add import image from a base64 string feature? Thanks.

**Comment by surma** [comment]
Can you expand a bit on the scenario/use-case where this would be useful? I could see us maybe supporting pasting a base64 string, but I can’t quite imagine when you’d end up using that.

**Comment by maicss** [comment]
Copy&paste base64 data from source code.
This is an uncommon scenario, I'm close this issue. Sorry to bother you.
