### ISSUE TITLE
DEV_PORT' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by manishbluewebspark** [GoogleChromeLabs/squoosh#1393]
when i  am trying to run it i am getting this problem       How can i run  i run it locally      -- I am using window  server  and using node  14.10 version

> squoosh@2.0.0 dev E:\compress-image\squoosh
> DEV_PORT=5000 run-p watch serve

'DEV_PORT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! squoosh@2.0.0 dev: `DEV_PORT=5000 run-p watch serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the squoosh@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenov\AppData\Roaming\npm-cache\_logs\2024-01-01T20_58_14_365Z-debug.log

**Comment by manishbluewebspark** [comment]
![npm](https://github.com/GoogleChromeLabs/squoosh/assets/49029104/d897a0fa-aa1b-4d6a-bc85-57ba5a81106a)

**Comment by surma** [comment]
It looks like you are using PowerShell. I don’t think we support that well. Can you try with WSL?

**Comment by manishbluewebspark** [comment]
> It looks like you are using PowerShell. I don’t think we support that well. Can you try with WSL?

Yes now its working thanks very much for quick help
