### ISSUE TITLE
i have some website which  built  using  PHP so how  can i  use it there 

### ISSUE THREAD

**Issue by manishbluewebspark** [GoogleChromeLabs/squoosh#1395]
Hello  Team,
i have some website which  built  using  PHP so how  can i  use it there

**Comment by surma** [comment]
Not sure I understand what you are asking. Squoosh is an app, not a library. So you can’t use it in other apps.

**Comment by xgovernor** [comment]
@manishbluewebspark, can you elaborate on the problem that you are trying to solve?

**Comment by manishbluewebspark** [comment]
> @manishbluewebspark, can you elaborate on the problem that you are trying to solve?

i have website in php and i  want  to  implement this there so  any one do upload picture it should compressed

**Comment by surma** [comment]
Yeah this is not the scope for Squoosh. You are looking for a library like [php-vips](https://github.com/libvips/php-vips). Closing this for now.
