### ISSUE TITLE
Some styles not getting typescript definitions

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#14]
https://github.com/GoogleChromeLabs/squoosh/tree/components-merge I've started trying to merge components in here.

* `src/components/app/style.scss` - definitions generated
* `src/components/output/custom-els/PinchZoom/styles.css` - definitions generated
* `src/components/output/style.scss` - **no definitions generated**

I can't figure out why definitions are missing for that last resource. Any ideas?

**Comment by developit** [comment]
This should work as of the `prerendering` branch. The issue was that `ts-loader` was running prior to the `typings-for-css-modules-loader`.

**Comment by jakearchibald** [comment]
It isn't working in https://github.com/GoogleChromeLabs/squoosh/pull/22, which is based on preloading.

**Comment by jakearchibald** [comment]
I've uncommented the line in #22 that triggers the build error.

**Comment by jakearchibald** [comment]
https://github.com/GoogleChromeLabs/squoosh/pull/22/commits/552beb5fb8d57f1a3d890388697b763b21034a5a

**Comment by jakearchibald** [comment]
Update: It's only working if you use the import, and even then it fails the first time.
