### ISSUE TITLE
Add Support for Videos

### ISSUE THREAD

**Issue by chraebsli** [GoogleChromeLabs/squoosh#1407]
**Is your feature request related to a problem? Please describe.**
I use the compression of images a lot. Recently, I wanted to compress & resize videos too and needed to look for another provider, but none of the ones I found support offline compression and similar tools like the compression for images

**Describe the solution you'd like**
I'd be happy if there was support for different video types soon, allowing me to convert, compress & resize videos.

**Does other service/app have this feature?**
There are many video compressors, resizers & converters out there but no open source variant with all these features.

**Additional context**
\-

_Keep up the great work! Thanks!_

**Comment by kevinfarrugia** [comment]
I don't think video compression is related to squoosh as it uses completely different codects. Personally, I recommend [FFmpeg](https://ffmpeg.org/) for video compression, formats...etc.

**Comment by chraebsli** [comment]
ok thanks! ill try it
