### ISSUE TITLE
Support for Jpegli

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [GoogleChromeLabs/squoosh#1420]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Jpegli is the new JPEG encoder from Google, open source, which is very good, and that would be really good if Squoosh implemented it

**Does other service/app have this feature?**
I don't think so

**Additional context**
Squoosh is by Chrome Labs, which is by Google, so that would be a good showcase of Jpegli for Google

**Comment by surma** [comment]
Duplicate of #1408
