### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by mustafa-x** [GoogleChromeLabs/squoosh#143]
Refresh: 
It would be great to have the image still loaded if the browser was accidentally refreshed. We might need to consider "load new image ui". Maybe as a modal? So if the browser reloads we ask the user to either continue or upload new image. 

**Settings options & Webp:**
Make the accordion menu a checkbox, as it is a setting rather than an expanded menu option. 
<img width="253" alt="screen shot 2018-08-20 at 12 47 48 pm" src="https://user-images.githubusercontent.com/1212513/44338884-59d51380-a477-11e8-9918-522274d0b33b.png">

Make sure we test different number values so we don't get bugs like this. Perhaps increase the size of the bubble or decrease the font size. 
<img width="135" alt="screen shot 2018-08-20 at 12 49 36 pm" src="https://user-images.githubusercontent.com/1212513/44338973-96a10a80-a477-11e8-84cf-9ba74ea3b739.png">

Checkboxes are misaligned with the text. They need to be centered. I found setting the top margin fixes it in Chrome. Not sure about other browsers` margin-top: 1px;`
Broken;
<img width="226" alt="screen shot 2018-08-20 at 12 53 31 pm" src="https://user-images.githubusercontent.com/1212513/44339185-60b05600-a478-11e8-9550-d6c4601c33c8.png">

With CSS fix
<img width="243" alt="screen shot 2018-08-20 at 12 56 09 pm" src="https://user-images.githubusercontent.com/1212513/44339202-7160cc00-a478-11e8-8a81-7f1cacc3670a.png">

Items are not aligned to the left properly. They should all align.
<img width="70" alt="screen shot 2018-08-20 at 12 58 31 pm" src="https://user-images.githubusercontent.com/1212513/44339316-ce5c8200-a478-11e8-90e4-41741a032b92.png">

Enablize should align centrally to the arrow
<img width="255" alt="screen shot 2018-08-20 at 12 59 18 pm" src="https://user-images.githubusercontent.com/1212513/44339340-e7fdc980-a478-11e8-9620-734d89c60fd1.png">

Labels that trail for checkboxes shouldn't wrap below them.
Current
<img width="245" alt="screen shot 2018-08-20 at 1 00 04 pm" src="https://user-images.githubusercontent.com/1212513/44339659-1cbe5080-a47a-11e8-98a8-7e027bbf8665.png">

What they should look like
<img width="249" alt="screen shot 2018-08-20 at 1 07 34 pm" src="https://user-images.githubusercontent.com/1212513/44339671-2647b880-a47a-11e8-9726-75f6f2c95521.png">

For setting types that are different, use a divider line
<img width="255" alt="screen shot 2018-08-20 at 1 09 10 pm" src="https://user-images.githubusercontent.com/1212513/44339705-4bd4c200-a47a-11e8-9bf4-1825b80954d0.png">

Remove the type of compression from the title box and put the download icon at the bottom next to the file size. 
<img width="258" alt="screen shot 2018-08-20 at 1 09 47 pm" src="https://user-images.githubusercontent.com/1212513/44339738-69099080-a47a-11e8-941c-9ca2f8bc7b65.png">

Put the download here, flush right;
<img width="259" alt="screen shot 2018-08-20 at 1 10 50 pm" src="https://user-images.githubusercontent.com/1212513/44339757-7c1c6080-a47a-11e8-8550-7e7b92330058.png">

**Buttons**
Set the blue to be darker, it is quite light for the buttons. Change it to #357ca5

Zoom
Ones the image is outside of the central bounding box, it should center towards the screen. Otherwise the user has to keep dragging it in towards the centre inbetween zooms. It will take time for the users to realize their mouse controls the central point. 

I think we need an X & Y position as I lost the image. Maybe double clicking / tapping the interface should centre the image?
<img width="889" alt="screen shot 2018-08-20 at 1 15 00 pm" src="https://user-images.githubusercontent.com/1212513/44339929-2300fc80-a47b-11e8-89c4-a6f9cea86195.png">

I couldn't disable the zoom as it kept zooming with my mouse move. Not sure what was going on. It happened when I started to use the Mouse's wheel.
![weirdbug-small](https://user-images.githubusercontent.com/1212513/44340826-00241780-a47e-11e8-9d04-ecb37582a6fd.gif)

**Error**
After scrolling for ages, image seemed to disappear. 
<img width="1012" alt="screen shot 2018-08-20 at 1 37 58 pm" src="https://user-images.githubusercontent.com/1212513/44340935-53966580-a47e-11e8-8a4b-c1df16f1e45f.png">

**Comment by developit** [comment]
@mustafa-x the zoom mouse thing is a bug, still tracking down what is causing it.

**Comment by jakearchibald** [comment]
This is great! Lots to chew through.

> It would be great to have the image still loaded if the browser was accidentally refreshed. We might need to consider "load new image ui". Maybe as a modal? So if the browser reloads we ask the user to either continue or upload new image.

I'm slightly nervous about this as it means storing the image data locally. It raises some privacy questions, from a storage perspective, but also user expectation. Eg, if you encoded something private, then closed the site, then opened the site to show a colleague how the site works, would you expect to be presented with the previous, private data?

**Comment by mustafa-x** [comment]
Why not have a time limit of 5 minutes?

**Comment by mustafa-x** [comment]
Also the loading screen needs some design love, the loading text in the far top hand corner looks broken. 
<img width="1520" alt="screen shot 2018-08-20 at 2 32 38 pm" src="https://user-images.githubusercontent.com/1212513/44343506-03230600-a486-11e8-86f9-8467b79871a9.png">

**Comment by developit** [comment]
It's not broken, just has no design at all.

One note on the suggested changes - I believe the misaligned "Enable Quantization" triangle was due to your margin-top customization. It's aligned properly in the other screenshots.

**Comment by kosamari** [comment]
I think most of todo items above is addressed already or has separate issue. Closing this issue now.  Please reopen if you feel otherwise!
