### ISSUE TITLE
Pinch-zoom: Add min/max scale values

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#149]
Currently I've hard coded a min scale value to prevent it going to zero. I've also prevent the entire transform if scale is below the minimum, otherwise it causes drift as it scales around a point but then doesn't do the actual scaling.

Anyway, min/max-scale should be attributes, properties, and if something is outside the min/max it shouldn't abort the whole setting operation unless it makes sense to.

**Comment by kosamari** [comment]
@developit would you be able to move this issue to https://github.com/GoogleChromeLabs/pinch-zoom repo? I don't seem to have access to "transfer this issue [beta]" btn

**Comment by kosamari** [comment]
Closing this because it is a pinch-zoom component
