### ISSUE TITLE
Build progress bar - more trouble than it's worth?

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#15]
I feels like we're disabling useful features (like showing address and port number of dev server) because the progress bar doesn't handle it correctly.

If this isn't fixable, we should just get rid of the progress bar.

**Comment by developit** [comment]
Agreed - it actually is separate from the progress bar. I'll PR re-adding the server info.

**Comment by developit** [comment]
There's also the built-in `--progress` option, which shows a textual progress indicator and doesn't eat newlines (if the above doesn't work).

**Comment by kosamari** [comment]
@developit @jakearchibald this issue seems old. can we close it?

**Comment by jakearchibald** [comment]
Yep!
