### ISSUE TITLE
Flatten CSS

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#161]
We're using the cascade, but with CSS modules it's mostly unnecessary.

This is ok:

```scss
.foo {
  label {
    // …
  }
}
```

…although we may consider just giving the labels their own class. However, we should avoid this:

```scss
.foo {
  .bar {
    // …
  }
}
```

The benefit of the above is we can target `.bar` within `.foo`, therefore avoid affecting `.bar` outside `.foo`. But with CSS modules we don't have that problem. Class names will be renamed so we don't need to use the cascade for encapsulation.

**Comment by jakearchibald** [comment]
I did some of this in https://github.com/GoogleChromeLabs/squoosh/pull/150.

**Comment by developit** [comment]
Yes - old habit I let slip in. Generally there's not much of a reason to nest classnames here.
