### ISSUE TITLE
Review UI issues from Mustafa

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#182]
https://github.com/GoogleChromeLabs/squoosh/pull/172#issuecomment-425140127

**Comment by developit** [comment]
**toggle button:** which one,  "toggle background"?

**preloading UI:** I was thinking a spinner for each side? or we could just use a brightly coloured indeterminate progressbar hugging the top of the viewport.  I threw one together here:
http://jsfiddle.net/developit/nz1robh3/

**black buttons:** agreed. the UI with all dark buttons would resemble a darkroom, which seems pretty fitting.  For the divider, would you want to keep it blue toned, or just move it to straight gray?  we actually built it out as grey and it's manually restyled here to be blue.

**bugs:** both bugs should be gone once we land worker termination. the download bug was just a result of the earlier bug you mentioned.
