### ISSUE TITLE
Add another PNG crusher

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#237]
OptiPNG doesn't seem to do as well as AdvPNG. We should look at porting AdvPNG over.

**Comment by jakearchibald** [comment]
Candidates:

* https://github.com/google/zopfli (slow but high compression. Not sure if it switches palette modes, so may need to be run through another crusher first).
* https://github.com/shssoichiro/oxipng Multithreaded and Rust version of optipng.
* AdvPNG - Old messy project but seems to be a good trade off in terms of speed and size reduction.
* https://github.com/fhanau/Efficient-Compression-Tool scores well in https://css-ig.net/png-tools-overview, but as far as I can tell, it's just a wrapper around other tools.

**Comment by tobiasdubois** [comment]
Maybe something like pngquant (https://pngquant.org/) can be interesting for lossy PNG compression. It feels like squoosh is especially good for lossy compression since it makes it easy to compare the before and after pictures.

**Comment by jakearchibald** [comment]
@tobiasdubois the "reduce palette" preprocessor uses libquant which powers pngquant. We seperated it so you can use it with webp lossless too (you can also use it with jpeg, but there isn't a lot of point).

**Comment by tracker1** [comment]
Would love to see a quantization option with palette reduction on the output... huge benefits in many cases.

**Comment by surma** [comment]
@tracker1 Squoosh already offers that. It’s under “Reduce palette”

**Comment by RReverser** [comment]
Just to add one more compressor that isn't listed above: [`PNGWolf`](http://bjoern.hoehrmann.de/pngwolf/). Code on Github: https://github.com/hoehrmann/pngwolf.

**Comment by surma** [comment]
I think we are all quite happy with Oxi :D
