### ISSUE TITLE
Add better Readme

### ISSUE THREAD

**Issue by kosamari** [GoogleChromeLabs/squoosh#248]
Things to discuss : 
- where the app is
- how to build locally
- staging ?

**Comment by jakearchibald** [comment]
Probably not staging, but yeah the rest. We might also add a bit of detail about what data goes to our servers (basically none, aside from analytics which we'll list). Waiting to hear back from privacy on that.

**Comment by dandv** [comment]
Would help to mention dependencies. Starting from scratch on Chrome OS, I needed to `sudo apt install -y make g++`.

**Comment by dandv** [comment]
Also, precise usage instructions. The typical `npm install; npm start` failed. I had to run `npm run build` in between.

**Comment by jakearchibald** [comment]
@dandv yep. We're trying to fly a little under the radar right now until launch. The README page intentionally left blank right now.

**Comment by callaginn** [comment]
So does anyone know how to install this on Mac OS X yet? Running `npm install; npm run build` fails with the following alerts:
<img width="100%" alt="screen shot 2018-11-15 at 11 06 38 am" src="https://user-images.githubusercontent.com/2430211/48569203-b903c200-e8c6-11e8-83df-f8164226235e.png">

I should also mention that the `/Sites/squoosh/node_modules` folder is completely empty after running those two commands.

**Comment by surma** [comment]
> I should also mention that the /Sites/squoosh/node_modules folder is completely empty after running those two commands.

That’s a big indicator that something is wrong :D Your `npm install` command immediately fails, saying that `har-validator` could not be found (but it [does exist](https://www.npmjs.com/package/har-validator)). Not sure what is going on there. Which version of node and npm are you running? Are you on a protected/corporate network?

**Comment by callaginn** [comment]
I'm running node v8.11.4 and npm 6.4.1 on my local machine, outside of any corporate network.

**Comment by callaginn** [comment]
*Updates Fixed Build Issue*
This weekend's updates allowed me to finally build it locally -- albeit with a few new issues related to `index.tsx` and `styles.css`. Either way, it now works. Tested the local build with a quick image this morning.

**Comment by kosamari** [comment]
closing this issue. Thanks @surma who added more info in readme
