### ISSUE TITLE
Squoosh doesn't initialize the UI on Android browsers on Chrome OS

### ISSUE THREAD

**Issue by dandv** [GoogleChromeLabs/squoosh#260]
P0 because demo-ing opening Squoosh from Android browsers on Chorme OS at CDS.

When opening the locally-running version of squoosh, SW works if the host is `localhost`, but due to http://crbug.com/848063, we need to specify the IP of the Linux container. That's no a secure origin, so Squoosh doesn't load.

**Comment by surma** [comment]
Squoosh doesn’t fail when the ServiceWorker doesn’t load. I just tested it with an alias for localhost where SW will fail to install and squoosh keeps working fine for me. What error are you seeing?

**Comment by surma** [comment]
You reported this as an issue for Chrome OS. Please include this sort of stuff in your issues in the future. Especially when time is tight and things are labelled as “P0” it is important that we don’t spend time on guessing conditions under which an error occurred.

I don’t have mobile Chrome at my disposal right now, but Squoosh works for me on desktop Firefox with a non-secure origin.

**Comment by jakearchibald** [comment]
@dandv with Chrome Dev Summit on Monday, everything's P0 right now. Right now I'm having trouble seeing how a service worker install failure would lead to Squoosh not loading. Squoosh doesn't depend on a service worker, so without it everything should just work, but not offline.

Without detailed recreation steps there's not a lot we can do here.

**Comment by dandv** [comment]
Sorry for being insufficiently clear about the platform. I'm trying to get Squoosh to run on Chrome OS 70.0.3538.76 (Official Build) beta (64-bit), using node v10.13.0. At the moment `npm start` doesn't launch the server due to #259, but if I check out 3c757bb2b2f47eef43bad15094dcc3dfad9c1619, I can run the server.

The problem at that point is that I see the checkerboard screen in both Android Chrome Beta 71 and Android Firefox 63:

![image](https://user-images.githubusercontent.com/33569/48305386-5da88d00-e4de-11e8-9c9f-56f1b59c4572.png)

My (hasty) guess was that SW didn't load because that IP is not a secure origin, since I saw the same checkerboard screen with [Firefox 60 ESR, which that turned out to have disabled SW](https://www.fxsitecompat.com/en-CA/docs/2018/service-workers-and-push-notifications-are-disabled-on-firefox-60-esr/).

**Comment by dandv** [comment]
Managed to connect Chrome Dev Tools running on Crostini to Android Chrome Dev (thanks @smibarber). Here's what's happening when trying to load the local instance (at commit 3c757bb2b2f47eef43bad15094dcc3dfad9c1619) from the Crostini IP:

![image](https://user-images.githubusercontent.com/33569/48307392-a3764d00-e500-11e8-9b19-49cb69fa6c7e.png)

**Comment by surma** [comment]
That error is expected and does not break the app (I see it locally as well over a non-secure origin). I can not reproduce this behavior on my end with Firefox or Chrome, so not quite sure what to do.

What version are you running?

**Comment by dandv** [comment]
2ca97ef5866f66b1baaa3655f4a66427190f732a fixed it, thanks!
