### ISSUE TITLE
request for UI tweak on checkboxes that toggle adjacent form controls

### ISSUE THREAD

**Issue by SignpostMarv** [GoogleChromeLabs/squoosh#267]
If one isn't familiar with the equivalent cli tools, it's not immediately obvious that a given checkbox will activate/disable an additional option or set of options- a couple of examples:

* "Separate chroma quality" opening toggling the chroma quality slider
* "pointless spec compliance" slides up an already-enabled "Optimize Huffman table" over "Progressive rendering" rather than visually indicating the latter option has been disabled.

**Comment by kosamari** [comment]
Closing this for now since UI have changed in V2
