### ISSUE TITLE
Some UI feedback (mostly)

### ISSUE THREAD

**Issue by paperboyo** [GoogleChromeLabs/squoosh#270]
Hello,

This is absolutely amazing and the codec options surfaced are very exhaustive – thank you all!
Some random thoughts, feel free to close whenever!

1. While fluid zooming may seem cool (and being fast – even useful), there is no replacement for seeing an image at multiples of 100%, hence: a quick way to reset zoom to 100% (doubleclick on an image? on a zoom control?) and plus and minus buttons to always go back to clearly defined steps (25% both ways off 100%?) would be cool to have.

2. Being able to quickly toggle between different options to compare them visually is very important. Since results are cached (absolutely amazing), it would be great to have at least undo/redo to quickly swap between two recent settings (possibly, more). Ideally, hovering over different dropdown options would switch results, too.

3. Dragging quality sliders shouldn’t yet trigger recompress (only letting go of a drag).

4. Buggy entry fields: I cannot type  `170` into Colors entry field (typing `1` gives me `2` :). After committing `15` into Quality, I get kicked out to homepage (all in latest Firefox beta).

4. Entry fields, when clicked, should select the whole value for easy retyping.

5. Doubleclicking a separator should move it between three positions: left view, right view and middle point. There should be a keyboard shortcut for switching between first two. And maybe another one to return to middle (split) view. Rationale for one shortcut to not go through all three states, but only two is to have an unambiguous and quick way to see before/after fullscreen without being distracted by the split view.

6. [may belong to codecs’s repos, but Sqoosh could surface some control] Colour management behaviour is inconsistent. At times broken/dangerous. For PNGs, all input is converted to sRGB , but the sRGB chunk is not set (questionable, although browsers got better at assuming sRGB). For JPGs, RGB profiles are converted, while CMYK ones are a problem, again output is, at times, in sRGB, but there is not profile embedded.

 7. Can’t find where one can set matte colour in transparent>opaque scenarios.

I think more keyboard shortcuts in general would be great to have (other issues mentioned eg useful hiding of all UI).

On codec options I just have some loose and badly informed thoughts: I don’t understand revived interest in WebP, to be honest, esp. with AVIF around the corner (hopefully, it will be adopted as quickly as OpenType 1.8!). I, FWIW, often fail to see benefits vs. MozJPEG (or rather: I prefer artifacts of the latter to those of the former). Some way of controlling quality of well-compressable/low freq areas independently of badly-compressable/high freq areas would do wonders – it’s often that both WebP and MozJPEG images could be compressed much more if I could protect areas that codecs deemed more “safe” for compression. A tool like this, that works on image-by-image basis would be an excellent place to give such control (no idea if codecs actually allow it!).

Another point would be that while the breadth of options is much welcomed (not sure about “Browser…” varieties), some friendly naming could maybe help users who have no idea what all those algorithms are supposed to excel at (like me). If that would lead to simplification and removal of some controls, it may be a good idea to provide Advanced-advanced options. I just hope, someone will write a book-length blog post on various options of Swoosh, that could be linked from the Tool itself.

Sorry for the length! Thank you again!

**Comment by kosamari** [comment]
I have created smaller issues splitting this one. Thank you very much for your suggestions!
1. created #345 
2. created #344
3. We terminate stale jobs (contained in worker) so triggering recompress should not be issue too much.
4. adressed in #316
5. adressed in #316
6. created #346 
7. created #348 
8. created #347
