### ISSUE TITLE
Quality metrics

### ISSUE THREAD

**Issue by shrpne** [GoogleChromeLabs/squoosh#271]
Would be great to add some quality metrics like [ssim](https://github.com/obartra/ssim)

**Comment by kosamari** [comment]
Hi @shrpne interesting! Is it something you use in your development? (I haven't worked in a project that had quality metrics 🙈)  Would appreciate if you could share how you use metrics like ssim.

**Comment by kosamari** [comment]
We had meeting today & concluded that this is out of scope for this project.
Squoosh's goal and focus was always about "you can see👀 the difference" & we'd like to stay with that as product.
