### ISSUE TITLE
Accidental click & drag on home screen loads logo image.

### ISSUE THREAD

**Issue by GifCo** [GoogleChromeLabs/squoosh#274]
If you accidentally click and drag the logo on the home screen it will load the logo into the image comparison module.

Not sure if this is desired behavior? If not should have an `e.preventDefault()` on the logo img tag.

**Comment by surma** [comment]
That’s definitely not intended, but I can‘t click-n-drag the logo. Which browser and OS are you on?

**Comment by GifCo** [comment]
@surma Im on Win10 and I can recreate the behavior on Edge 42.17134.1.0
I could have swore it was doing the same in Chrome but I literally just updated to newest version (70.0.3538) 20min ago and I can no longer see the behavior.

**Comment by JamieFarrelly** [comment]
Same here on Windows 10 and Edge. Even adding "pointer-events: none" to the image seems to fix it.

**Comment by jakearchibald** [comment]
This sounds like a fun issue to fix. Thanks for reporting!

**Comment by JamieFarrelly** [comment]
Sorry for the multiple pull requests but I've opened a pull request to fix this #290. The sample images on the homepage had the same issue.

**Comment by kosamari** [comment]
closing the issue since PR was merged.
