### ISSUE TITLE
Smoothing selection bar creates jank

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChromeLabs/squoosh#277]
Using the smoothing option selection bar and drag it around is really janky on Chrome (on Mac). When I load the large image and grab the slider and move it around, the following performance jank happens:
![image](https://user-images.githubusercontent.com/5948271/48427091-e0b72680-e71c-11e8-907b-970aa56d80e6.png)

**Comment by surma** [comment]
Yeah. Let’s denounce range inputs. Everybody hates them.

**Comment by jakearchibald** [comment]
https://github.com/GoogleChromeLabs/squoosh/pull/394
