### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by g2ice87** [GoogleChromeLabs/squoosh#282]
Seems to be an issue with the webpack, any guidance?

$ npm run build

> squoosh@1.0.2 build C:\Squoosh\squoosh
> webpack -p

   76 modules

ERROR in ./src/codecs/processor-worker.ts (./node_modules/worker-plugin/dist/loader.js?{"name":"processor-worker"}!./src/codecs/processor-worker.ts)
Module build failed (from ./node_modules/worker-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'C:\Squoosh\squoosh\codecs\imagequant'
    at factory.create (C:\Squoosh\squoosh\node_modules\webpack\lib\Compilation.js:797:10)
    at factory (C:\Squoosh\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (C:\Squoosh\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (C:\Squoosh\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at C:\Squoosh\squoosh\node_modules\neo-async\async.js:2817:7
    at C:\Squoosh\squoosh\node_modules\neo-async\async.js:6783:13
    at normalResolver.resolve (C:\Squoosh\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn41 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:381:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:23:37)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at args (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\forEachBail.js:30:14)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn42 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:393:1)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)

**Comment by trananhmanh89** [comment]
same here

`λ npx webpack serve                                                                                          
i ｢wds｣: Project is running at http://localhost:8080/les                                                     
i ｢wds｣: webpack output is served from /                                                                     
i ｢wds｣: Content not from webpack is served from E:\laragon\www\squoosh\src                                  
i ｢wds｣: 404s will fallback to /index.html                                                                   
× ｢wdm｣:    146 modules                                                                                      
                                                                                                             
ERROR in ./src/codecs/processor-worker.ts (./node_modules/worker-plugin/dist/loader.js?{"name":"processor-wor
ker"}!./src/codecs/processor-worker.ts)                                                                      
Module build failed (from ./node_modules/worker-plugin/dist/loader.js):                                      
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'E:\laragon\www\squoosh\codecs\imagequant
'                                                                                                            
    at factory.create (E:\laragon\www\squoosh\node_modules\webpack\lib\Compilation.js:797:10)                
    at factory (E:\laragon\www\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:397:22)               
    at resolver (E:\laragon\www\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:130:21)              
    at asyncLib.parallel (E:\laragon\www\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:224:22)     
    at E:\laragon\www\squoosh\node_modules\neo-async\async.js:2817:7                                         
    at E:\laragon\www\squoosh\node_modules\neo-async\async.js:6783:13                                        
    at normalResolver.resolve (E:\laragon\www\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (E:\laragon\www\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:184:12)               
    at hook.callAsync (E:\laragon\www\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)           
    at _fn0 (eval at create (E:\laragon\www\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anon
ymous>:15:1)                                                                                                 
    at resolver.doResolve (E:\laragon\www\squoosh\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5
)                                                                                                            
    at hook.callAsync (E:\laragon\www\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)           
    at _fn0 (eval at create (E:\laragon\www\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anon
ymous>:15:1)                                                                                                 
    at hook.callAsync (E:\laragon\www\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)           
    at _fn0 (eval at create (E:\laragon\www\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anon
ymous>:12:1)                                                                                                 
    at resolver.doResolve (E:\laragon\www\squoosh\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:
42:38)                                                                                                       
i ｢wdm｣: Failed to compile.                                                                                  `

**Comment by surma** [comment]
This seems to be related worker-plugin: I’m assuming it’s assuming `/` when Windows needs `\`.

@developit You mind taking this?

@trananhmanh89 @g2ice87 Just for completeness sake: Can you give use your node and npm versions please?

**Comment by g2ice87** [comment]
$ node --version
v10.13.0

$ npm --version
6.4.1

I have tried with the most recent release as well. Thanks for checking into it @surma

**Comment by neewbee** [comment]
Fedora 29
```sh
➜  squoosh git:(master) ✗ npm -v
6.4.1
➜  squoosh git:(master) ✗ node -v
v10.12.0
```

```sh
➜  squoosh git:(master) ✗ npm run build

> squoosh@1.0.2 build /home/neewbee/demos/squoosh
> webpack -p

   76 modules

ERROR in /home/neewbee/demos/squoosh/src/codecs/generic/quality-option.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/codecs/generic/quality-option.tsx(3,24)
      TS2307: Cannot find module '../../components/Options/style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/codecs/imagequant/options.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/codecs/imagequant/options.tsx(5,24)
      TS2307: Cannot find module '../../components/Options/style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/codecs/mozjpeg/options.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/codecs/mozjpeg/options.tsx(5,24)
      TS2307: Cannot find module '../../components/Options/style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/codecs/optipng/options.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/codecs/optipng/options.tsx(6,24)
      TS2307: Cannot find module '../../components/Options/style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/codecs/resize/options.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/codecs/resize/options.tsx(6,24)
      TS2307: Cannot find module '../../components/Options/style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/codecs/webp/options.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/codecs/webp/options.tsx(5,24)
      TS2307: Cannot find module '../../components/Options/style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/App/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/App/index.tsx(4,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/Options/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/Options/index.tsx(3,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/Output/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/Output/index.tsx(5,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/Output/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/Output/index.tsx(9,29)
      TS2307: Cannot find module './custom-els/TwoUp/styles.css'.

ERROR in /home/neewbee/demos/squoosh/src/components/Output/custom-els/TwoUp/index.ts
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/Output/custom-els/TwoUp/index.ts(2,25)
      TS2307: Cannot find module './styles.css'.

ERROR in /home/neewbee/demos/squoosh/src/components/checkbox/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/checkbox/index.tsx(2,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/compress/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/compress/index.tsx(5,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/compress/custom-els/MultiPanel/index.ts
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/compress/custom-els/MultiPanel/index.ts(1,24)
      TS2307: Cannot find module './styles.css'.

ERROR in /home/neewbee/demos/squoosh/src/components/custom-els/LoadingSpinner/index.ts
./src/components/custom-els/LoadingSpinner/index.ts
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/custom-els/LoadingSpinner/index.ts(1,25)
      TS2307: Cannot find module './styles.css'.

ERROR in /home/neewbee/demos/squoosh/src/components/expander/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/expander/index.tsx(2,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/intro/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/intro/index.tsx(14,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/range/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/range/index.tsx(2,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/results/FileSize.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/results/FileSize.tsx(3,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/results/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/results/index.tsx(3,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/components/select/index.tsx
[tsl] ERROR in /home/neewbee/demos/squoosh/src/components/select/index.tsx(2,24)
      TS2307: Cannot find module './style.scss'.

ERROR in /home/neewbee/demos/squoosh/src/custom-els/RangeInput/index.ts
[tsl] ERROR in /home/neewbee/demos/squoosh/src/custom-els/RangeInput/index.ts(3,24)
      TS2307: Cannot find module './styles.css'.

ERROR in /home/neewbee/demos/squoosh/src/lib/SnackBar/index.ts
[tsl] ERROR in /home/neewbee/demos/squoosh/src/lib/SnackBar/index.ts(1,24)
      TS2307: Cannot find module './styles.css'.
Error parsing bundle asset "/home/neewbee/demos/squoosh/build/first-interaction.0aabb.js": no such file
Error parsing bundle asset "/home/neewbee/demos/squoosh/build/main-app.38ebc.js": no such file
Error parsing bundle asset "/home/neewbee/demos/squoosh/build/offliner.31821.js": no such file
Error parsing bundle asset "/home/neewbee/demos/squoosh/build/wc-polyfill.b195e.js": no such file

No bundles were parsed. Analyzer will show only original module sizes from stats file.

Webpack Bundle Analyzer saved report to /home/neewbee/demos/squoosh/build/report.html
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! squoosh@1.0.2 build: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the squoosh@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/neewbee/.npm/_logs/2018-11-15T01_29_35_024Z-debug.log
```

**Comment by developit** [comment]
Hmm - looks like it's not ignoring `fs` imports on Windows. Perhaps this line is the issue:

https://github.com/GoogleChromeLabs/squoosh/blob/0502d70cdfba54973cecc905d97b072445e3ff8d/webpack.config.js#L172

**Comment by g2ice87** [comment]
Got it to compile finally. Replacing all entries in webpack.config.js that contain '\/' like '/\/codecs\//' with '/\\codecs\\/'. Thanks for pointing me in the right direction!

Here is the config file that allowed for successful compiling on Win 10:
`const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const CleanPlugin = require('clean-webpack-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const ProgressBarPlugin = require('progress-bar-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const HtmlPlugin = require('html-webpack-plugin');
const ScriptExtHtmlPlugin = require('script-ext-html-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');
const WatchTimestampsPlugin = require('./config/watch-timestamps-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const WorkerPlugin = require('worker-plugin');
const AutoSWPlugin = require('./config/auto-sw-plugin');
const CrittersPlugin = require('critters-webpack-plugin');
const AssetTemplatePlugin = require('./config/asset-template-plugin');

function readJson (filename) {
  return JSON.parse(fs.readFileSync(filename));
}

const VERSION = readJson('./package.json').version;

module.exports = function (_, env) {
  const isProd = env.mode === 'production';
  const nodeModules = path.join(__dirname, 'node_modules');
  const componentStyleDirs = [
    path.join(__dirname, 'src/components'),
    path.join(__dirname, 'src/codecs'),
    path.join(__dirname, 'src/custom-els'),
    path.join(__dirname, 'src/lib'),
  ];

  return {
    mode: isProd ? 'production' : 'development',
    entry: {
      'first-interaction': './src/index'
    },
    devtool: isProd ? 'source-map' : 'inline-source-map',
    stats: 'minimal',
    output: {
      filename: isProd ? '[name].[chunkhash:5].js' : '[name].js',
      chunkFilename: '[name].[chunkhash:5].js',
      path: path.join(__dirname, 'build'),
      publicPath: '/',
      globalObject: 'self'
    },
    resolve: {
      extensions: ['.ts', '.tsx', '.mjs', '.js', '.scss', '.css'],
      alias: {
        style: path.join(__dirname, 'src/style')
      }
    },
    resolveLoader: {
      alias: {
        // async-component-loader returns a wrapper component that waits for the import to load before rendering:
        async: path.join(__dirname, 'config/async-component-loader')
      }
    },
    module: {
      // Disable the default JavaScript handling:
      defaultRules: [],
      rules: [
        {
          oneOf: [
            {
              test: /(\.mjs|\.esm\.js)$/i,
              type: 'javascript/esm',
              resolve: {},
              parser: {
                harmony: true,
                amd: false,
                commonjs: false,
                system: false,
                requireInclude: false,
                requireEnsure: false,
                requireContext: false,
                browserify: false,
                requireJs: false,
                node: false
              }
            },
            {
              type: 'javascript/auto',
              resolve: {},
              parser: {
                system: false,
                requireJs: false
              }
            }
          ]
        },
        {
          test: /\.(scss|sass)$/,
          loader: 'sass-loader',
          // SCSS gets preprocessed, then treated like any other CSS:
          enforce: 'pre',
          options: {
            sourceMap: true,
            includePaths: [nodeModules]
          }
        },
        {
          test: /\.(scss|sass|css)$/,
          // Only enable CSS Modules within `src/components/*`
          include: componentStyleDirs,
          use: [
            // In production, CSS is extracted to files on disk. In development, it's inlined into JS:
            isProd ? MiniCssExtractPlugin.loader : 'style-loader',
            {
              // This is a fork of css-loader that auto-generates .d.ts files for CSS module imports.
              // The result is a definition file with the exported String classname mappings.
              loader: 'typings-for-css-modules-loader',
              options: {
                modules: true,
                localIdentName: isProd ? '[hash:base64:5]' : '[local]__[hash:base64:5]',
                namedExport: true,
                camelCase: true,
                importLoaders: 1,
                sourceMap: isProd,
                sass: true
              }
            }
          ]
        },
        {
          test: /\.(scss|sass|css)$/,
          // Process non-modular CSS everywhere *except* `src/components/*`
          exclude: componentStyleDirs,
          use: [
            isProd ? MiniCssExtractPlugin.loader : 'style-loader',
            {
              loader: 'css-loader',
              options: {
                importLoaders: 1,
                sourceMap: isProd
              }
            }
          ]
        },
        {
          test: /\.tsx?$/,
          exclude: nodeModules,
          loader: 'ts-loader'
        },
        {
          // All the codec files define a global with the same name as their file name. `exports-loader` attaches those to `module.exports`.
          test: /\\codecs\\.*\.js$/,
          loader: 'exports-loader'
        },
        {
          test: /\\codecs\\.*\.wasm$/,
          // This is needed to make webpack NOT process wasm files.
          // See https://github.com/webpack/webpack/issues/6725
          type: 'javascript/auto',
          loader: 'file-loader',
          options: {
            name: '[name].[hash:5].[ext]',
          },
        },
        {
          test: /\.(png|svg|jpg|gif)$/,
          loader: 'file-loader',
          options: {
            name: '[name].[hash:5].[ext]',
          },
        }
      ]
    },
    plugins: [
      new webpack.IgnorePlugin(/(fs|crypto|path)/, /\\codecs\\/),
      // Pretty progressbar showing build progress:
      new ProgressBarPlugin({
        format: '\u001b[90m\u001b[44mBuild\u001b[49m\u001b[39m [:bar] \u001b[32m\u001b[1m:percent\u001b[22m\u001b[39m (:elapseds) \u001b[2m:msg\u001b[22m\r',
        renderThrottle: 100,
        summary: false,
        clear: true
      }),

      // Remove old files before outputting a production build:
      isProd && new CleanPlugin([
        'assets',
        '**/*.{css,js,json,html,map}'
      ], {
        root: path.join(__dirname, 'build'),
        verbose: false,
        beforeEmit: true
      }),

      new WorkerPlugin(),

      // Automatically split code into async chunks.
      // See: https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366
      isProd && new webpack.optimize.SplitChunksPlugin({}),

      // In production, extract all CSS to produce files on disk, even for
      // lazy-loaded CSS chunks. CSS for async chunks is loaded on-demand.
      // This is a modern Webpack 4 replacement for ExtractTextPlugin.
      // See: https://github.com/webpack-contrib/mini-css-extract-plugin
      // See also: https://twitter.com/wsokra/status/970253245733113856
      isProd && new MiniCssExtractPlugin({
        filename: '[name].[contenthash:5].css',
        chunkFilename: '[name].[contenthash:5].css'
      }),

      new OptimizeCssAssetsPlugin({
        cssProcessorOptions: {
          postcssReduceIdents: {
            counterStyle: false,
            gridTemplate: false,
            keyframes: false
          }
        }
      }),

      // These plugins fix infinite loop in typings-for-css-modules-loader.
      // See: https://github.com/Jimdo/typings-for-css-modules-loader/issues/35
      new webpack.WatchIgnorePlugin([
        /(c|sc|sa)ss\.d\.ts$/
      ]),
      new WatchTimestampsPlugin([
        /(c|sc|sa)ss\.d\.ts$/
      ]),

      // For now we're not doing SSR.
      new HtmlPlugin({
        filename: path.join(__dirname, 'build/index.html'),
        template: isProd ? '!!prerender-loader?string!src/index.html' : 'src/index.html',
        minify: isProd && {
          collapseWhitespace: true,
          removeScriptTypeAttributes: true,
          removeStyleLinkTypeAttributes: true,
          removeRedundantAttributes: true,
          removeComments: true
        },
        manifest: readJson('./src/manifest.json'),
        inject: 'body',
        compile: true
      }),

      new AutoSWPlugin({ version: VERSION }),

      isProd && new AssetTemplatePlugin({
        template: path.join(__dirname, '_headers.ejs'),
        filename: '_headers',
      }),

      new ScriptExtHtmlPlugin({
        inline: ['first']
      }),

      // Inline constants during build, so they can be folded by UglifyJS.
      new webpack.DefinePlugin({
        VERSION: JSON.stringify(VERSION),
        // We set node.process=false later in this config.
        // Here we make sure if (process && process.foo) still works:
        process: '{}'
      }),

      // Copying files via Webpack allows them to be served dynamically by `webpack serve`
      new CopyPlugin([
        { from: 'src/manifest.json', to: 'manifest.json' },
        { from: 'src/assets', to: 'assets' }
      ]),

      // For production builds, output module size analysis to build/report.html
      isProd && new BundleAnalyzerPlugin({
        analyzerMode: 'static',
        defaultSizes: 'gzip',
        openAnalyzer: false
      }),

      // Inline Critical CSS (for the intro screen, essentially)
      isProd && new CrittersPlugin({
        // use <link rel="stylesheet" media="not x" onload="this.media='all'"> hack to load async css:
        preload: 'media',
        // inline all styles from any stylesheet below this size:
        inlineThreshold: 2000,
        // don't bother lazy-loading non-critical stylesheets below this size, just inline the non-critical styles too:
        minimumExternalSize: 4000,
        // don't emit <noscript> external stylesheet links since the app fundamentally requires JS anyway:
        noscriptFallback: false,
        // inline the tiny data URL fonts we have for the intro screen:
        inlineFonts: true,
        // (and don't lazy load them):
        preloadFonts: false
      })
    ].filter(Boolean), // Filter out any falsey plugin array entries.

    optimization: {
      minimizer: [
        new UglifyJsPlugin({
          sourceMap: isProd,
          extractComments: {
            file: 'build/licenses.txt'
          },
          uglifyOptions: {
            compress: {
              inline: 1
            },
            mangle: {
              safari10: true
            },
            output: {
              safari10: true
            }
          }
        })
      ]
    },

    // Turn off various NodeJS environment polyfills Webpack adds to bundles.
    // They're supposed to be added only when used, but the heuristic is loose
    // (eg: existence of a variable called setImmedaite in any scope)
    node: {
      console: false,
      // Keep global, it's just an alias of window and used by many third party modules:
      global: true,
      // Turn off process to avoid bundling a nextTick implementation:
      process: false,
      // Inline __filename and __dirname values:
      __filename: 'mock',
      __dirname: 'mock',
      // Never embed a portable implementation of Node's Buffer module:
      Buffer: false,
      // Never embed a setImmediate implementation:
      setImmediate: false
    },

    devServer: {
      // Any unmatched request paths will serve static files from src/*:
      contentBase: path.join(__dirname, 'src'),
      compress: true,
      // Request paths not ending in a file extension serve index.html:
      historyApiFallback: true,
      // Suppress forwarding of Webpack logs to the browser console:
      clientLogLevel: 'none',
      // Supress the extensive stats normally printed after a dev build (since sizes are mostly useless):
      stats: 'minimal',
      // Don't embed an error overlay ("redbox") into the client bundle:
      overlay: false
    }
  };
};
`

**Comment by developit** [comment]
Makes sense to me! That plugin operates on real filesystem paths, so it bypasses wevpacks usual normalization.

**Comment by DevonJSmith** [comment]
Would modifying these lines to include both cases, such as 
`new webpack.IgnorePlugin(/(fs|crypto|path)/, /\/codecs\/|\\codecs\\/),` 
Work in order to maintain the previous functionality while still accounting for the Windows file structure?

**Comment by surma** [comment]
I think at that point I’d prefer something like

```js
const {sep} = require("fs");
new webpack.IgnorePlugin(
  /(fs|crypto|path)/,
  new RegExp(`${sep}codecs${sep}`)
)
```

**Comment by DevonJSmith** [comment]
Ah, `path.sep` would work for this, right?

```javascript
new webpack.IgnorePlugin(
  /(fs|crypto|path)/,
  new RegExp(`${path.sep}codecs${path.sep}`)
)
```

**Comment by sobujbd** [comment]
I'm also Unable to build Squoosh app on Windows 10.
Is there anyone get success?
