### ISSUE TITLE
Automatically convert to the other formats in the background

### ISSUE THREAD

**Issue by thibaultmol** [GoogleChromeLabs/squoosh#284]
I'd be nice if, in the background, it would already convert to the other formats. And then give you a view like this:
![image](https://user-images.githubusercontent.com/1010226/48468171-6dc8b100-e7eb-11e8-9847-f6fa9ef45051.png)

So you can easily see which one is the smallest for your specific image

**Comment by surma** [comment]
I totally see where you are coming from, but spinning up all these encoders would cost a significant amount of battery on mobile devices and would actually take quite a lot of time.

Additionally, the overview is not that useful considering every image format has many options to change how effective/lossy the encoding is. 

We are thinking about exposing a client-side API for squoosh, so once we have that, you could build this functionality yourself as an embedder :)
