### ISSUE TITLE
When installed on Android, pressing the back button completely exits the app, discarding all work, causing the app to start over anytime you use the Android back button. 

### ISSUE THREAD

**Issue by abqnm** [GoogleChromeLabs/squoosh#286]
This feels like I'm using a ported iOS app with this behavior. Using the Android standard navigation keys shouldn't cause the app to completely forget its place and start over, but rather just move back one page within the app, and if at the top level already, then exit the app. But exiting and forgetting all data the first time you tap the back button makes this quite unusable in a serious fashion at the moment if you're an Android user. 

Trying to remember to never use the most common navigation key used in Android just so the app doesn't forget everything you're working on does not work well on Android. The USPS Informed Delivery app—which isn't even a PWA, but rather a poorly ported iOS+web wrapper—has been this way for over 2 years, and I still can't get used to not closing the app because I forgot that I can't use the actual Android back button. At least that app saves its place when you use the back button, so re-opening the app brings you back to where you were. But this Squoosh PWA does not, so it's extremely easy to destroy your work with no way to recover. That's not good for a productivity tool.

**Comment by jakearchibald** [comment]
What do you expect the back button to do in this case? If anything, I figured it'd go back to the main screen, so you'd still be losing your settings.

**Comment by abqnm** [comment]
I expect it to go back to the previous page, like the back navigation key is supposed to in every Android app. 

PWAs should follow the same navigation structure as the OS they're used on, so the back navigation key should step back one view within the app, and then if on the top level view, THEN it should exit the app. Having it just exit the app and discard everything without any sort of warning is just a really terrible UX. 

Breaking the standard Android navigation structure is a big reason why PWAs are not extremely popular, and loathed nearly as much as terrible web wrappers before them, and they make for an incredibly disjointed experience using multiple navigation schemas that don't agree with the underlying OS.

**Comment by surma** [comment]
“previous page” — do you mean the landing screen with the squoosh logo?

So:

1. Open app, get landing screen (the one with the logo)
2. Load an image
3. Do a couple of settings and compression jobs
4. Press back button
5. Be back on landing screen

Is that the behavior that you’d expect? (I think I’d agree with that and it could be solved with a simple `pushState()` when an image is loaded.)

**Comment by jakearchibald** [comment]
> the back navigation key should step back one view within the app

Given that Squoosh only has two views, you mean "go back from the compression screen to the home screen" then? 

That would also lose your compression settings.

**Comment by abqnm** [comment]
@surma, yes, that is what would be expected.

@jakearchibald, yes, that's correct. I realize it is losing changes still when using the software back button (which could be addressed by adding a warning before discarding the changes), but the real point is not the specific actions with just this PWA, but a significant issue with all PWAs, web wrappers, and ported iOS apps—inconsistent navigation. I don't care that the app only has two views, it needs to respect the system navigation and not treat the Android navigation back key as an instruction to terminate the application, unless it's at the top level view. It should respect the system navigation actions, and if there's a hardware/OS level back button, it needs to use the hierarchy for how that back button steps back through views. It doesn't quit a native app if not at the top level view, so it shouldn't do it in PWAs either.

**Comment by jakearchibald** [comment]
> point is not the specific actions with just this PWA, but a significant issue with all PWAs

Issues filed under https://github.com/GoogleChromeLabs/squoosh/issues are intended to be specific to Squoosh, not all PWAs.

Filed https://github.com/GoogleChromeLabs/squoosh/issues/288 to cover the Squoosh-specific case.
