### ISSUE TITLE
Browser back button should go from compression screen back to home screen

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#288]
Uh oh it's `pushState` time.

**Comment by fstanis** [comment]
Does it also make sense to serialize the compression options in the URL somehow (e.g. `https://squoosh.app/compress?left_codec=original&right_codec=MozJPEG&right_quality=40&right_etc=...`? This could solve the aforementioned issue of losing them when going back.

Not sure what to do with the loaded image though. Some ideas:

- Save last used to cache, load from cache
- Load second view without image and ask the user to drag and drop it [again]
- Add third view, asking the user to drag and drop image to proceed
