### ISSUE TITLE
Copyright & Fair Use Policies

### ISSUE THREAD

**Issue by pawseytj** [GoogleChromeLabs/squoosh#293]
Please add details on Copyright & Fair Use Policies for use of squoosh?  Eg. Can I freely use squoosh to reduce image sizes for images I own & add those reduced size images to a website?

**Comment by sachk** [comment]
squoosh is really good for figuring out settings, but it's not a compressor in itself, and other programs are more suited to mass compressing a bunch of files especially for web use.

**Comment by kosamari** [comment]
Thanks for your suggestion! We'll discuss this after little break/traveling back from CDS this week :)

**Comment by kosamari** [comment]
web app links to github which has sufficient license info
