### ISSUE TITLE
Issue template ?

### ISSUE THREAD

**Issue by kosamari** [GoogleChromeLabs/squoosh#296]
Now that we are getting contributions and questions 😌 shall we have issue templates?

**Comment by surma** [comment]
I’m gonna create one to cover some basics. Everyone in the team should feel free to add stuff or make suggestions here.

**Comment by surma** [comment]
I think we should also add a `FAQ.md` or maybe re-enable the wiki with an FAQ for stuff like “I can haz batch?”
