### ISSUE TITLE
Create config component

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#30]
It'll need:

* A drop-down select, to select the codec.
* Toggles.
* Range sliders (eg "quality").

This will be a good point for us to review and test the material design implementation, and decide if the off-the-shelf solution is good enough.

No need hooking the form up to anything until https://github.com/GoogleChromeLabs/squoosh/issues/25 is complete, then we can look at how to define configs for each codec.

**Comment by jakearchibald** [comment]
Since @surma has started merging in the codecs, this can now involve looking at the actual options the codec provides, and creating a realistic form.

**Comment by surma** [comment]
Should we figure out some kind of self-description per codec? 

Like `getOptions()` and that returns some sort of JSON that describes the available options from which when then generate the options panel?

**Comment by developit** [comment]
@surma either that or just have components that implement each codec's settings so we can customize as-needed. Not sure about you but every time I've done form generation from a schema, I've always ended up regretting it, haha.

**Comment by jakearchibald** [comment]
I've also experienced the schema-form-generation pain. However, the form should be 'close' to the codec, so we remember to update one if we update the other.

**Comment by jakearchibald** [comment]
I think this is done in terms of its own issue. We'll create additional issues per codec.
