### ISSUE TITLE
batch optimize 

### ISSUE THREAD

**Issue by andrejarh** [GoogleChromeLabs/squoosh#300]
Not really an issue, just a question?

Is it possible to optimize a whole folder in terminal using local node install? 
Are there any dev docs available?

**Comment by kosamari** [comment]
thanks for the question! Currently the app does not batch(folder) processing.

As for using it on terminal, this app is a GUI app built on top of codecs compressors (WebP, OptiPNG, MozJPEG) so you may experiment the options with Squoosh > process them using existing program on command line.
