### ISSUE TITLE
Using it for website development

### ISSUE THREAD

**Issue by dpramani** [GoogleChromeLabs/squoosh#302]
Are there any API documentations available for this ? What are my options for using this for website development ? 

Thanks

**Comment by kosamari** [comment]
Hi ya @dpramani Sqoosh is an application to test and experiment with efficient codec like MozJPEG, WebP, OptiPNG. We basically exposed things you can do with those codecs on command line and put  UI on top. 

We thought it would be used to experiment with codec/option setting, then you can take that to put it into your build process (like batch converting images on deploy).

Does this answer your question? :)
