### ISSUE TITLE
Drag image from another tab

### ISSUE THREAD

**Issue by seguri** [GoogleChromeLabs/squoosh#310]
It would make the process faster if it worked by dragging an image from another tab.
Test: Open a tab with squoosh; open another tab with amazon and choose a random item from the store, just to access its description; open the big image of that item and drag it to the squoosh tab. Result: squoosh compresses the dragged image

**Comment by kosamari** [comment]
Hey @seguri thanks for suggestion - can you help me understand "make the process faster" bit? 
We had assumption that while you are say, developing website, you'd have raw asset on local folder, and never really thought of asset living in different tab. What's your work flow like? (trying understand it so we can design best interaction)

Thanks!

**Comment by seguri** [comment]
Hi @kosamari, the flow I'm thinking to is the one I described in the second line of my opening post as "Test". Should I reformulate it?
@jakearchibald myabe on Monday I can learn how browser interpret dragged images. At the moment I can't help you

**Comment by surma** [comment]
@seguri I think, currently, if you drag-and-drop an image from another page all we get is the URL. We can’t read, let alone compress that image as it’s most likely blocked by CORS.

**Comment by jakearchibald** [comment]
https://static-misc.glitch.me/drop-test/ - little demo that logs whatever you drop on the page.

Yeah, unfortunately the browser only gives us the URL.

I'm going to close this, but hopefully Share Target V2 can give us what we need to implement something similar. https://bugs.chromium.org/p/chromium/issues/detail?id=885313

**Comment by jespertheend** [comment]
I guess you could host a [CORS proxy](
https://github.com/Rob--W/cors-anywhere) but that kind of takes away the whole point of an app like this doesn’t it.

**Comment by jakearchibald** [comment]
Yeah, I don't want to get into the maintenance, cost, & legal issues of that.

**Comment by seguri** [comment]
I sometimes drop images from a tab to another tab opened on images.google.com. Do you know how that feature works?

**Comment by jakearchibald** [comment]
I guess a server component downloads the image.
