### ISSUE TITLE
Numbers cannot start with 1 when editing colors for OptiPNG

### ISSUE THREAD

**Issue by motss** [GoogleChromeLabs/squoosh#316]
Steps to reproduce:
1. In `Compress` mode, switch to `OptiPNG`.
2. Toggle to check on `Reduce palette` checkbox.
3. Focus on or click the `input[type=number]` element of `Colors:`
4. And type `17` and see the value 'jumps' to `27` instead.

Because of the input validation that only allows a minimum value of `2`, this breaks the final value when user tries to enter anything starts with `1` but less than `2`.

**Comment by RobertUsg** [comment]
Thanks for the info. Good job

**Comment by pepelsbey** [comment]
Yes please, I have to type 26 and then fix 2 to 1 way too often.
