### ISSUE TITLE
Image to base64 data uri string option

### ISSUE THREAD

**Issue by eobeda** [GoogleChromeLabs/squoosh#317]
**New Feature:** An option to "save" the image in a data url format would be nice. From comments on other services that just do that, support for HTML tags and CSS usage of the output appears to be an additional desire as well.
--Ed

**Comment by kosamari** [comment]
@eobeda thanks for the suggestion. Can you link to other service that does base64 encoding as export? Would love to look at UI design.

**Comment by kosamari** [comment]
Thanks for your suggestion @eobeda! we've had V2 meeting today & concluded that this is out of scope for squoosh project. Perhaps something that can be layered on top as micro tool.
