### ISSUE TITLE
Image size rises from 159kB to 673kB when the lossless option is checked

### ISSUE THREAD

**Issue by chiamakaikeanyi** [GoogleChromeLabs/squoosh#321]
**The Bug**
Image size rises from 159kB to 673kB when the lossless option is checked. 

**To Reproduce**
1. Launch the app and upload an image
2. Take note of the compression rate. 
3. Select the lossless option

**Expected behavior**
The original image size is 159kB. It will be cool to have the new image size less than the original size irrespective of the option chosen (Lossy or Lossless).

**Version:**
 - OS w/ version: [macOS High Sierra 10.13.6]
 - Browser w/ version [Chrome 70.0.3538.77]

**Original Image**
<img width="1200" alt="original" src="https://user-images.githubusercontent.com/22685689/48688665-7c3a1280-ebc7-11e8-9ea7-c72545bc759e.png">

**Lossy Image**
<img width="1440" alt="lossy" src="https://user-images.githubusercontent.com/22685689/48688673-80fec680-ebc7-11e8-958e-a3ed443f6ce2.png">

**Lossless Image**
<img width="1440" alt="lossless" src="https://user-images.githubusercontent.com/22685689/48688677-84924d80-ebc7-11e8-9b7c-ee518ee2afed.png">

**Comment by chiamakaikeanyi** [comment]
**The Bug**
Image size rises from 159kB to 673kB when the lossless option is checked. 

**To Reproduce**
1. Launch the app and upload an image
2. Take note of the compression rate. 
3. Select the lossless option

**Expected behavior**
The original image size is 159kB. It will be cool to have the new image size less than the original size irrespective of the option chosen (Lossy or Lossless).

**Version:**
 - OS w/ version: [macOS High Sierra 10.13.6]
 - Browser w/ version [Chrome 70.0.3538.77]

**Original Image**
<img width="1200" alt="original" src="https://user-images.githubusercontent.com/22685689/48688665-7c3a1280-ebc7-11e8-9ea7-c72545bc759e.png">

**Lossy Image**
<img width="1440" alt="lossy" src="https://user-images.githubusercontent.com/22685689/48688673-80fec680-ebc7-11e8-958e-a3ed443f6ce2.png">

**Lossless Image**
<img width="1440" alt="lossless" src="https://user-images.githubusercontent.com/22685689/48688677-84924d80-ebc7-11e8-9b7c-ee518ee2afed.png">

**Comment by jakearchibald** [comment]
Unfortunately this is how image compression works.

If you take a lossy image (I'm pretty certain the original is lossy) and compress it in a lossless format, you'll get an exact copy of the lossy image, including the lossy artifacts.

Lossless compressions naturally take up more bytes than lossy ones, else they'd be no point in lossy compressions.
