### ISSUE TITLE
Add support to animated webp

### ISSUE THREAD

**Issue by bkizzy** [GoogleChromeLabs/squoosh#325]
1. Upload animated webp
2. Apply squoosh compression
3. Download webp

result: Only 1st frame of animated webp is preserved.

expected result: Entire webp is downloaded

**Comment by surma** [comment]
Yeah, we don’t support animation at all currently.

Not sure if we are ever gonna fix that considering the amount of work we’d have to go through to decode and show animated formats via wasm.

**Comment by kosamari** [comment]
Hi @bkizzy thanks for the feature suggestion! We had meeting today & concluded that this is nice-to-have-but-not-now feature. 

We think this will be great addition but a lot to sort out (both UX & tech). We'll keep this issue open but probably not be able to get to it in foreseeable future.

**Comment by afanjul** [comment]
+1

**Comment by jakearchibald** [comment]
We might consider this once https://github.com/shssoichiro/oxipng/issues/79 (or a similar tool) supports it

**Comment by surma** [comment]
I don’t think we will support animations any time soon for either WebP, AVIF or JPEG-XL.
