### ISSUE TITLE
4k compression

### ISSUE THREAD

**Issue by Zoiberg1984** [GoogleChromeLabs/squoosh#335]
When trying to compress 4k images in 100% quality, an error occurs.
When using a local copy of the site, a message appears about the lack of memory.
if you use the web version with an internet connection, you receive this error message:

Processing error (type=mozjpeg): Error: ExitStatus: Program terminated with exit(1) Error at https://squoosh.app/process-mozjpeg-enc.d4eb5.worker.js:1:29707 at e (https://squoosh.app/process-mozjpeg-enc.d4eb5.worker.js:1:102) at new Promise (<anonymous>) at t (https://squoosh.app/process-mozjpeg-enc.d4eb5.worker.js:1:78) at c (https://squoosh.app/process-mozjpeg-enc.d4eb5.worker.js:1:403) at Object.mozjpegEncode (https://squoosh.app/processor-worker.a760a.worker.js:1:5395)

**Comment by kosamari** [comment]
Hi @Zoiberg1984 could you please add original file that result in error?

**Comment by kosamari** [comment]
probably related to #298

**Comment by kosamari** [comment]
let's track large photo issue with #298
