### ISSUE TITLE
OptiPNG isn't optimal

### ISSUE THREAD

**Issue by i-fail** [GoogleChromeLabs/squoosh#336]
OptiPNG is okay, but you can do better. I keep track of lossless PNG optimizers here:
https://olegkikin.com/png_optimizers/
Pingo and PNGOut and ZopfliPNG are the best so far.

**Comment by kosamari** [comment]
Hi @i-fail we welcome PR to add more codecs. Please see https://github.com/GoogleChromeLabs/squoosh/tree/master/codecs for more.

**Comment by jakearchibald** [comment]
Yeah, I'd like to add zopfli & advcomp. My preference would be advcomp because it's fast, but the project is a bit of a mess and didn't turn out easy to compile.

**Comment by jakearchibald** [comment]
It looks like a wrapper around existing tools like zopflipng & optipng, or am I missing something original there?

**Comment by jakearchibald** [comment]
Merging into #237
