### ISSUE TITLE
(security) flatmap-stream was removed

### ISSUE THREAD

**Issue by DanielRuf** [GoogleChromeLabs/squoosh#339]
`flatmap-stream` was completely removed due to security reasons.

See https://github.com/dominictarr/event-stream/issues/116 and https://www.npmjs.com/package/flatmap-stream

So there will be issues.

```
npm view flatmap-stream 
npm ERR! code E404
npm ERR! 404 Unpublished by npm-support on 2018-11-26T17:18:17.658Z
npm ERR! 404 
npm ERR! 404  'flatmap-stream' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/druf/.npm/_logs/2018-11-27T08_46_23_549Z-debug.log
```

**Comment by jakearchibald** [comment]
Thanks for the heads-up.

Just in case: this isn't a security threat to Squoosh. The malicious code targeted a particular Electron (native) app.

Although the compromised flatmap-stream is in our dependency chain, it's part of our build system, and has no negative impact on the code running on squoosh.app.

Today we'll find the dependency that's using it, and update/remove it.

We should also consider adding a content security policy to protect user data in case we ever do become compromised by something like this, and Travis should ensure a particular policy is set as part of its tests.

**Comment by DanielRuf** [comment]
> We should also consider adding a content security policy to protect user data in case we ever do become compromised by something like this, and Travis should ensure a particular policy is set as part of its tests.

Exactly. Unfortunately so far no AV vendor detects the files. Would be interested to see solutions for such cases.

Not sure if Skantek would have helped here: https://twitter.com/pmarquees/status/1035497062614401024

https://medium.com/adyen/skantek-securing-nodejs-at-adyen-f944283ce7c9

**Comment by jakearchibald** [comment]
> Sure, but it is completely wiped now on npmjs.

I get it. I just wanted to make it clear to anyone else reading the thread that the code running on https://squoosh.app (which was built before the module was wiped from NPM) is not compromised.

**Comment by DanielRuf** [comment]
Pinning to `event-stream: "3.3.4"` might be a temporary solution.

**Comment by jakearchibald** [comment]
Fixed in https://github.com/GoogleChromeLabs/squoosh/pull/340

**Comment by jakearchibald** [comment]
Thanks for reporting, @DanielRuf!

**Comment by DanielRuf** [comment]
Thanks too for the fast reaction. 👍 
Not yet sure if I provide issues and PRs for more projects (like I did with cli-table2 - https://github.com/cli-table/cli-table3/issues/17 ).

Because there are much more (and probably many private ones and not published on npmjs too).

https://www.npmjs.com/package/event-stream?activeTab=dependents

At least GitHub is sending notifications to all affected repo owners.
