### ISSUE TITLE
Hey is it possible to add videos support too ?

### ISSUE THREAD

**Issue by Kayo99** [GoogleChromeLabs/squoosh#343]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
just to convert videos to correct format like MPEG and WEBM and OGV.

**Does other service/app have this feature?**
i dont know

**Comment by kosamari** [comment]
hi @Kayo99 thanks for the suggestion! Squoosh is focused on image files and we consider videos are out of scope.
