### ISSUE TITLE
Add better interaction for split bar

### ISSUE THREAD

**Issue by kosamari** [GoogleChromeLabs/squoosh#346]
Splitting from issue #270

-------

Doubleclicking a separator should move it between three positions: left view, right view and middle point. There should be a keyboard shortcut for switching between first two. And maybe another one to return to middle (split) view. Rationale for one shortcut to not go through all three states, but only two is to have an unambiguous and quick way to see before/after fullscreen without being distracted by the split view.

**Comment by jonsneyers** [comment]
+1 on having a keyboard button (or I guess an easy to tap button on mobile) to toggle between the two images. If you want to very carefully compare two images, that's the best way (avoids the slider from interfering with your motion detection).

A button to temporarily show the original would also be nice, to make it easier to do 3-way comparisons between codec1, codec2 and original.
