### ISSUE TITLE
Add ability to sett matte color for transparent/opaque image

### ISSUE THREAD

**Issue by kosamari** [GoogleChromeLabs/squoosh#347]
Splitting from issue #270

--------

Can’t find where one can set matte colour in transparent>opaque scenarios.

**Comment by kosamari** [comment]
We should discuss if we want to support this feature.

**Comment by jakearchibald** [comment]
Hmm doesn't it make more sense as a preprocessor?

**Comment by jakearchibald** [comment]
Eg, I might want to compare the size of a jpeg with a close-enough background to transparent PNG.

**Comment by surma** [comment]
Rolling into #736
