### ISSUE TITLE
JPEG Image Preview Too Far to the Right

### ISSUE THREAD

**Issue by vicks1008** [GoogleChromeLabs/squoosh#359]
After a .jpeg image is resized to be smaller, the image preview (right side) goes far off to the right and cannot be seen properly.

**To Reproduce**
1. Drag & drop an image from your computer's Finder/File Explorer and drop onto the squoosh browser window.
2. Click on 'Resize' and resize the image width to 1080px.
3. Change format to 'Browser JPEG'.
4. Drag the "image previewer" to the left to see the right side of the image is too far off the screen.

What should happen is for the image preview on the right side to stay put and not move away from the rest of the image.

 - MacOS Mojave 10.14.1, MacBook Pro (Retina, 15-inch, Early 2013)
 - Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)

Video reproducing the issue can be found on this [Google Drive link](https://goo.gl/sgMZK4).

**Comment by jakearchibald** [comment]
Thanks for the detailed report. I'll take a look.

**Comment by jakearchibald** [comment]
I can reproduce something similar to this. Investigating…

**Comment by jakearchibald** [comment]
This is a regression that happened in the rotate PR. The pinch-zoom target is losing `flex-shrink: 0`. Should be a quick fix.

**Comment by jakearchibald** [comment]
Yeah, it's kinda obvious looking at https://github.com/GoogleChromeLabs/squoosh/pull/322/files#diff-e3ab5d0fa21a380d44a9cecb40bead88 now. My bad. Fix incoming…

**Comment by jakearchibald** [comment]
https://github.com/GoogleChromeLabs/squoosh/pull/360

**Comment by jakearchibald** [comment]
@vicks1008 thanks for spotting this! The fix is deploying now & should be available in a couple of minutes.
