### ISSUE TITLE
Move image encoder off-thread

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/squoosh#36]

**Comment by developit** [comment]
I ended up toying with workers when trying to get the options UI set up, but moved on to other things. Here's my sloppy commit if it contains anything potentially useful:
https://github.com/GoogleChromeLabs/squoosh/compare/options...worker-encode

**Comment by jakearchibald** [comment]
Is this done?

**Comment by surma** [comment]
Yeah, comlink-loader got merged with #39
