### ISSUE TITLE
WebP encoder: can't use_sharp_yuv

### ISSUE THREAD

**Issue by Ser-Gen** [GoogleChromeLabs/squoosh#392]
`use_sharp_yuv` option is not affects an image.

**To Reproduce**
I use checkbox in app.
Also download codec from this repo.
Any combinations of settings can't force encoder to use sharp subsampling.

**Expected behavior**
Colors of output image should be close to source.

**Versions**
OS: win 10
Browsers: Chrome Canary 72.0.3623.0, FF Developer 65.0b4

**Source**

![unilever](https://user-images.githubusercontent.com/1856145/50077753-5586f000-01f6-11e9-8a58-aac601e2f3d3.png)

**Output of Squoosh**

![unilever squoosh-sharp-yuv](https://user-images.githubusercontent.com/1856145/50077801-73eceb80-01f6-11e9-88d4-dd08f82f6c46.png)

**For comparison** — result of command

```
cwebp -sharp_yuv unilever.png -o unilever.cwebp-sharp-yuv.webp
```

![unilever cwebp-sharp-yuv](https://user-images.githubusercontent.com/1856145/50077719-39834e80-01f6-11e9-8dc6-49e0bf0ba53c.png)

**Comment by jakearchibald** [comment]
Here's a fix https://github.com/GoogleChromeLabs/squoosh/pull/393.

Going to check with the webp folks before deploying, as I'm not sure what `use_argb` is for.

**Comment by jakearchibald** [comment]
@Ser-Gen thanks for reporting this. Hopefully we can deploy the fix today.
