### ISSUE TITLE
Add support for the Web Share Target API - Level 2

### ISSUE THREAD

**Issue by tomayac** [GoogleChromeLabs/squoosh#401]
[Squoosh](https://squoosh.app/) would be an ideal candidate to explore the [Web Share Target API - Level 2](https://wicg.github.io/web-share-target/level-2/). This would allow Squoosh to act as a share target for any to-be-squooshed image files.

**Comment by surma** [comment]
We are already working on that :D

https://github.com/GoogleChromeLabs/squoosh/tree/share-target?files=1

**Comment by jakearchibald** [comment]
Blocked on https://bugs.chromium.org/p/chromium/issues/detail?id=916070 right now, but aside from that we're close to having something demoable.

**Comment by jakearchibald** [comment]
https://github.com/GoogleChromeLabs/squoosh/pull/469
