### ISSUE TITLE
Document codec build dependencies

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#41]
I'm guessing it's `automake` and `docker` for mozjpeg?

**Comment by surma** [comment]
Correct. After #37, I’m hoping that `docker` will be the only dependency.

(Side note: I think I might end up committing the wasm modules after all because the testing story just gets unwieldy. Running docker within docker and stuff.. eugh)

**Comment by jakearchibald** [comment]
Yeah, I think the complexity of the wasm build means it's the best way forward.
