### ISSUE TITLE
Quality bar bug

### ISSUE THREAD

**Issue by k79e** [GoogleChromeLabs/squoosh#417]
When using mozjpeg with 
subsample chroma set to 1 (seems this is not necessary)
Quantization set to flat
Then quality bar bug appears!!!
Slide it to 90 watch file size then slide it to 91 92 ... 100
You can see file size just don't change between some quality.
90-92 file size is all same as 90
93-95 from 92-93 file size increase but stop from 93-95
96-100 file size just increase from 95-96 but 96-100 is same.
These 3 range is a 3 different quality. But it should be 10.
The file size should change on every different quality.

**Comment by surma** [comment]
I don't think it's a bug. We pass the quality number straight to mozjpeg. Changing the quality setting will not always change resulting file size.

**Comment by kxmp** [comment]
> I don't think it's a bug. We pass the quality number straight to mozjpeg. Changing the quality setting will not always change resulting file size.

If size is same then the content should be different.
I checked the hash of two file and they are same.

**Comment by surma** [comment]
I tried to reproduce this with your image and I can’t. I get different file sizes for every quality setting between 90 and 100.

In terms of file size I don’t think that is a bug. Consider this image (yes, that’s a black square):
![carbon 18](https://user-images.githubusercontent.com/234957/50533825-79a0d600-0b00-11e9-9010-8af1f6f23965.png)

Literally all quality settings between 0 and 69 yield the same image file size when using MozJPEG. 

They do however yield different files (as in different hashes) for me.

**Comment by kxmp** [comment]
> ......
> They do however yield different files (as in different hashes) for me.

Have you set the Quality in advanced settings to flat.
I used your black picture and got same hash from 90-92

**Comment by surma** [comment]
Oh you mean the quantizer settings. Sorry I missed that.

Well, I think that could still be expected behavior, but I think we might indeed have a bug: [We seem to be ignoring the quantizer setting unless it is unset](https://github.com/GoogleChromeLabs/squoosh/blob/6fbdc65ad0d50b442565ccb1a005756711db78d5/codecs/mozjpeg_enc/mozjpeg_enc.cpp#L128-L130).

@jakearchibald WDYT?
