### ISSUE TITLE
User Presets

### ISSUE THREAD

**Issue by rmtsrc** [GoogleChromeLabs/squoosh#430]
Would be nice to have user customisable and savable presets so that I can quickly pick between my favorite settings, allowing faster batch editing. Presumably, this would also need a way to title, edit and delete presets. Similar to #78.

P.S. Keep up the good work! 👍

**Comment by jakearchibald** [comment]
Yeah, this is a good idea. Thanks for the suggestion (and long time no speak)!

**Comment by tracker1** [comment]
Agreed on the presets... maybe a first path using localStorage, then an option to use something like Google Drive and/or dropbox for persistance?

**Comment by romainmenke** [comment]
Maybe also as a query  param? This makes it easy to save a preset as a bookmark, or send a preset to other people.

**Comment by chris-kruining** [comment]
by extension it would also be awesome to be able to batch convert in the UI, like open 10 images for example and convert all of them to webp with the same settings
