### ISSUE TITLE
Drag and drop file loading

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#45]
This feature will be available on all screens of the app, not just the intro screen.

There should be some kind of drop indicator, but we shouldn't worry too much about the specific design yet.

**Comment by PaulKinlan** [comment]
I'll be taking this one. Likely going to make a web component out of it, that accepts drops and does all the magic... innit.

**Comment by surma** [comment]
Unexpected Paul Kinlan in bagging area.

**Comment by PaulKinlan** [comment]
I'm a sucker for dragndrop.... silos innit

**Comment by PaulKinlan** [comment]
also, I need to learn typescript and preact and stuff.

**Comment by PaulKinlan** [comment]
@jakearchibald @surma do we use ShadowDOM and slots etc?

**Comment by jakearchibald** [comment]
How I see `<file-drop>` working:

Applies a class to itself once it detects file(s) over it.

Fires enter and exit events.

Fires drop event. That event should have a `files` property.

The web component shouldn't have any design. Users should use the change in class name to apply visual changes.

Avoid shadow DOM. We're sticking to the stuff that can be easily pollyfilled.

**Comment by PaulKinlan** [comment]
ok cool..

So I was thinking something like
Note will change to 'file-drop' more explicit.

```
 <drop-target
    bindTo='some dom select'
    fileType='image/*'
  >
    <some content that will appear as an overlay />
  </drop-target>
```

**Comment by jakearchibald** [comment]
I wouldn't bother with `bindTo`. The element itself is the drop target.

Instead of `fileType` go with `accepts` and try to be compatible with https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Limiting_accepted_file_types.

**Comment by surma** [comment]
> Applies a class to itself once it detects file(s) over it.

Not an attribute? (also why is [`:drop`](https://css4-selectors.com/selector/css4/drop-pseudo-class/) still not implemented anywhere?)

**Comment by PaulKinlan** [comment]
You know, we could just make the <input type=file> 100% of the screen size and just use the default system drop target for file inputs...

**Comment by jakearchibald** [comment]
@PaulKinlan that would catch clicks too, which we don't want

**Comment by jakearchibald** [comment]
@surma 

> Not an attribute?

Attributes aren't really used for state. In a perfect world we would define a pseudo-class for this (which part will eventually give us), so a class feels like the next best thing.

**Comment by PaulKinlan** [comment]
true.

**Comment by PaulKinlan** [comment]
re: bindTo - I was thinking of having the element watch for events on developer defined targets vs this element ultimately being a fullscreen (documentElement), that being said, I'm going to start simple.

**Comment by jakearchibald** [comment]
@PaulKinlan I went the same way initially, but events can be easily used to change the appearance of the different element.

For Squoosh, I imagine `<drop-target>` will be the root element, with everything else inside it.

**Comment by PaulKinlan** [comment]
Issues so far before I even get to testing my code....

* Unable to build the codecs it seems - that it's error with autoconf 'configure.ac:23: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.'  cc @surma 
* Unable to get webpack to, well, pack via npm run build. It just comes back with a 'Couldn't parse bundle asset "/home/paulkinlan/squoosh/build/main.08649.js".' @developit

**Comment by surma** [comment]
If you are on master, you shouldn’t need to build the codecs, the build artifacts are commited, as mozjpeg is non-trivial to build (and I haven’t put _everything_ into docker yet).

`npm i && npm run build` is all you need.

**Comment by PaulKinlan** [comment]
hmm - @jakearchibald said to fork from Options branch ;)

**Comment by PaulKinlan** [comment]
I'll bring in the master branch...

**Comment by jakearchibald** [comment]
Combine the two 😄

**Comment by surma** [comment]
Well, alternatively just pull the .js and the .wasm from master and remove `npm run build:codecs` or whatever from the build steps 😄

**Comment by PaulKinlan** [comment]
It turns out npm run start - starts, and seems to have Js, but it errors on the CLI like crazy about being unable to compile.
