### ISSUE TITLE
Generic notification component

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#46]
Something we can display errors in, such as image encode/decode errors.

A material snackbar would do https://material.io/design/components/snackbars.html#anatomy.

**Comment by developit** [comment]
do we want this one to be a web component?

**Comment by jakearchibald** [comment]
Initially I thought this would just be a preact thing, since the problem is mostly state management and events. But yeah, I guess it could be a custom element. A bit messy without shadow dom though.

**Comment by developit** [comment]
Could just use this:
https://material.preactjs.com/component/snackbar

**Comment by jakearchibald** [comment]
Our snackbar will need to be able to contain buttons. Eg "New version available [refresh]".
