### ISSUE TITLE
Can't reach the web

### ISSUE THREAD

**Issue by TomasSestak** [GoogleChromeLabs/squoosh#460]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
Can't connect to the web
This site can’t be reached.
squoosh.app’s server IP address could not be found.

**Expected behavior**
to connect

**Version:**
macOS Mojave
Version 10.14.3

**Additional context, screenshots, screencasts**
It works on other devices on the same connection. It doesn't work on my laptop using diffrent wifis or browsers.

**Comment by surma** [comment]
It works for me.

Is there any chance this is related to your ISP or your device's setup?

**Comment by jakearchibald** [comment]
@TomasSestak What browser were you using?

**Comment by TomasSestak** [comment]
Safari, Firefox, Chrome, also in private windows. It has to do something with my Mac because as I stated before it works on my phone or other devices even on the same network

**Comment by jakearchibald** [comment]
Can you access http://www.spritecow.com/?

**Comment by TomasSestak** [comment]
> Can you access http://www.spritecow.com/?

yes, I can

**Comment by jakearchibald** [comment]
Hm, so they're both hosted on Netlify, so it's not that.

**Comment by surma** [comment]
Could it be the TLD?

@TomasSestak Can you reach https://web.dev?

**Comment by TomasSestak** [comment]
> Could it be the TLD?
> 
> @TomasSestak Can you reach https://web.dev?

Yes, I can

**Comment by TomasSestak** [comment]
> Could it be the TLD?
> 
> @TomasSestak Can you reach https://web.dev?

you might be right, https://get.app/ doesn't work for me

**Comment by TomasSestak** [comment]
Does anybody know how to fix it?

**Comment by jakearchibald** [comment]
Have you checked your hosts file for things that might block .app?

**Comment by TomasSestak** [comment]
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
192.168.99.100	local.test


this is all I have there.
![safari](https://user-images.githubusercontent.com/27310585/52824759-30a9de80-30ba-11e9-94cd-5250a6cfd5b0.png)
this showed up in Safari, but I can't seem to reproduce it

**Comment by TomasSestak** [comment]
<img width="554" alt="screenshot 2019-02-15 at 01 08 24" src="https://user-images.githubusercontent.com/27310585/52825873-c47da980-30be-11e9-92aa-9d9e614b8527.png">

It might be from laravel valet I used to use, but I cant't find any records :/

**Comment by TomasSestak** [comment]
I found it in etc/resolver, file called app, deleted, works now, thank you for help

**Comment by surma** [comment]
Glad you figured it out!
