### ISSUE TITLE
Need support for Lossy Compression of PNG like pngquant since OptiPNG isn't sufficient. 

### ISSUE THREAD

**Issue by mvishnu071194** [GoogleChromeLabs/squoosh#466]
* Compression tools like pngquant compresses the png image to maximum extend compromising the quality, though the comprised quality is sufficient for most website viewing than the compression made by OptiPNG

* Integrating tool like pngquant which uses quantisation technique for compression will serve better compressed png images.

**Comment by jakearchibald** [comment]
We already use libimagequant (which is a the quantisation library used by pngquant). Access it using the "Reduce palette" setting.

![screenshot 2019-02-18 at 11 42 14](https://user-images.githubusercontent.com/93594/52948838-7ee90700-3372-11e9-8275-974ff1fa292a.png)

**Comment by mvishnu071194** [comment]
Thanks. This worked well.
