### ISSUE TITLE
Image size info

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#48]
For each image, some human readable information on the size vs the original size.

**Comment by jakearchibald** [comment]
This is mostly done, just haven't hooked up the % yet.

**Comment by sendilkumarn** [comment]
I would like to take a crack at this one. It would it be better if we show it something like this on both the sides. 

<img width="789" alt="screen shot 2018-07-06 at 23 46 27" src="https://user-images.githubusercontent.com/12471122/42401630-da6ad094-8176-11e8-8d68-fa0e9a48917b.png">

**Comment by jakearchibald** [comment]
We're waiting to figure out the design of this (the implementation is easy). Something like your screenshot doesn't quite work as it isn't clear what the % is of.

We're throwing around "85% of original" in a design.

**Comment by sendilkumarn** [comment]
Yeah agree it is kinda confusing (but it is just the % difference between left/right and viceversa) , but do you think it would be better to say `85% of left image` rather than `original`.

**Comment by jakearchibald** [comment]
I think it should be "% of original" rather than % of left/right, else one just ends up being 1/x of the other, which isn't as useful.
