### ISSUE TITLE
Rotation change doesn't work on Safari.

### ISSUE THREAD

**Issue by alisaitbilgi** [GoogleChromeLabs/squoosh#493]
Since [WebAssembly.instantiateStreaming](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming) method has no support on Safari, changing the rotation of an image on Safari causes an error being thrown.

**Steps to reproduce the behavior:**
1. Open the app in Safari browser.
2. Select an image.
3. Click rotation-change button.

**Versions:**
 - OS version: MacOS 10.14.3
 - Browser version: Safari 12.0.3
 - Node version: 10.15.1
 - npm version: 6.4.1

**Screen-shot:**

<img width="1438" alt="screen shot 2019-03-04 at 16 13 05" src="https://user-images.githubusercontent.com/11788821/53736155-f7cf7f00-3e99-11e9-8c0f-034fd7dda631.png">

**Comment by surma** [comment]
Wait, `instantiateStreaming` is _not_ in Safari??! I thought all browsers shipped that. That’s on oversight by me then! Thanks for flagging.
