### ISSUE TITLE
[Question] rotation UX

### ISSUE THREAD

**Issue by frlinw** [GoogleChromeLabs/squoosh#500]
**Is your feature request related to a problem? Please describe.**
When you rotate an image, the original image and the compressed one can be out-of-sync for a short delay.

**Describe the solution you'd like**
Fake the rotation with css for an instant feeling until the rotation is done then reset the css rotation and replace non rotated image with rotated one ?

**Comment by jakearchibald** [comment]
I'll take this on. I think I introduced this bug when I debounced the inputs.
