### ISSUE TITLE
Use packtracker.io for bundle size reporting

### ISSUE THREAD

**Issue by jondavidjohn** [GoogleChromeLabs/squoosh#502]
Hi!

This is a really neat project and in particular does a lot of interesting webpack configuration around asset optimization!  Would you have any interest in reporting asset size changes to your pull requests, and maybe even set javascript and css asset budgets that can fail any PR that exceeds them?

Also thinking this might help be a guard against unanticipated size gain due to automatically bumping dependencies with something like @renovate[bot] 

https://packtracker.io

I'd be super interested in seeing how usage in a more sophisticated setup like this might look.  If you're interested let me know how I can be of any help.

**Comment by jakearchibald** [comment]
Our CI script already provides size diffs, but I'm not against trying something else.

**Comment by jondavidjohn** [comment]
Cool! You can see an example of what the PR Checks would look like here.

https://github.com/jondavidjohn/squoosh/pull/1

And the type of view available in our app

https://app.packtracker.io/organizations/2/projects/114?branch=packtracker-example-branch

and I can send a PR with the configuration, all you'd need to do is sign up and create a project on https://packtracker.io and set a project token in an environment variable in your CI process. 👍

**Comment by jondavidjohn** [comment]
Also, you'll need to grant the app access to the repo under the "GitHub Checks" tab.
