### ISSUE TITLE
Resize in linear RGB

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#509]
https://www.nayuki.io/page/srgb-transform-library - these look useful

**Comment by jakearchibald** [comment]
Shipped

**Comment by nayuki** [comment]
For reference:
* Commit https://github.com/GoogleChromeLabs/squoosh/pull/510/commits/d9f1190620c8c349419fa9b3ef1c994175852c6a
* Pull request https://github.com/GoogleChromeLabs/squoosh/pull/510
