### ISSUE TITLE
Update webp modules to libwebp 1.0.0

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/squoosh#51]
They released v1.0.0 of libwebp end of April. We should update.

**Comment by jakearchibald** [comment]
I'm really interested to see how easy this is, as it'll indicate how much of a PITA this project will be to maintain 😄

**Comment by surma** [comment]
A quick test while writing the decoder seemed to imply no API changes. So it should just be a matter of bumping the version number.

I’ll test this once #50 has landed.

**Comment by surma** [comment]
That being said, if it works, it’s okay for us to pin these kind of dependencies to a version that works,  unless we are missing out on crucial features/fixes

**Comment by jakearchibald** [comment]
Agreed, but it'd be nice to stay reasonably up to date. I don't keep SVGOMG as up to date as I'd like because integration is a bit of a ballache.
