### ISSUE TITLE
Overlay "Working..." on Updating Image

### ISSUE THREAD

**Issue by AnthumChris** [GoogleChromeLabs/squoosh#516]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that the "working..." status appears in bottom right of screen, hidden in my peripheral vision.

**Describe the solution you'd like**
Would love to stare at the image on the right as it processes and quickly see the "working..." nearby so that I can immediately know when processing is done and the right image is updated.

**Does other service/app have this feature?**
Async content regions (e.g. 300px widget box) show spinners over the respective content area to be updated.  

**Additional context**
More of a neurological slowness on my end, but by the time my eyes dash from the right image to the  bottom-right "working..." message, I sometimes miss the visual image change that occurs when processing completes.  Would be great to keep my eyes focused on the image and easily see when "working..." disappears peripherally.

**Comment by kosamari** [comment]
Even though it wasn't solved with overlay, I believe V2 design made a lot clear when the image is processing, closing this now.
