### ISSUE TITLE
Sqoosh removes all EXIF information

### ISSUE THREAD

**Issue by chaostimothy** [GoogleChromeLabs/squoosh#553]
**Describe the bug**
Uploading a JPG file containing EXIF information (e.g. Drone image) and compressing to the same file format (i.e. JPG) using Sqoosh (on both MozJPEG or Browser JPEG compression) removes all EXIF information.

**To Reproduce**
1. Have a drone JPG image containing EXIF data
2. Using Sqoosh, convert it to MozJPG or Browser JPG
3. Save/download
4. See that EXIF data is now gone

**Expected behavior**
EXIF data should remain

**Version:**
 - OS w/ version: Mac OS X Mojave 10.14.2 (18C54)
 - Browser w/ version Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
- Original image 
![image](https://user-images.githubusercontent.com/47413313/56337333-47ae9f00-61d7-11e9-8637-8629dcfb0074.jpg)

- Output image from Squoosh

![image (1)](https://user-images.githubusercontent.com/47413313/56337382-93f9df00-61d7-11e9-9d1b-b6d4537ff07d.jpg)

**Comment by jakearchibald** [comment]
This is deliberate right now. Squoosh is about making images as small as they can be, so non-visual data is discarded.

We might consider adding options for this in future, but it isn't our priority right now.

**Comment by drveresh** [comment]
I too recommend(@chaostimothy) this feature for not removing EXIF data.  Technically, it may be a simple option or flag to decide whether to keep or delete EXIF data.  At least please keep the basic(may take < 200 bytes) EXIF data like dates, geolocation, camera name/type etc, because these are used by mobile devices and apps to create photo albums, location-based collection, maps and more.

I hope you @jakearchibald consider these and take an extra step to offer this essential feature as well.

**Comment by jakearchibald** [comment]
If it's as simple as you say it is then please submit a PR.

**Comment by drveresh** [comment]
@jakearchibald , I mean, from website/UI, we need a single input(`checkbox[name=deleteExif]`), Exif[true/false], and in the backend, we need to read this single parameter and decide to delete exif data, maybe, `if(deleteExif) { deleteExifData() }`

It is about adding basic and more value for this product.  I would try sending a PR.

**Comment by jakearchibald** [comment]
Not all input/output configurations support exif, so I don't think it's as simple as you think (where would this option go?). But, I'll happily review any PR you submit.

**Comment by WORMSS** [comment]
Just to note, there is already the "compressor specific settings" under the quality slider.
With such things as mozJPEG saying "show advanced settings", and WebP having additionally "Presenter transparent data". 

That seems like it would be the place to put it. If the compressor allows Exif, it goes there, if it doesn't, then there is no option.

**Comment by prguru** [comment]
I´m also missing an option to keep EXIF-data. Any plans to add that important feature for copyright issues?

**Comment by kosamari** [comment]
Closing this issue for now. 
With V2 release and libSquoosh release, we've been consistent with removing EXIF data, and I'd say no-EXIF output is the direction we chose for this project.

**Comment by rudolphos** [comment]
I've been using Squoosh for some time, compressing lots of jpegs with EXIF (never really checked whether it's still there), but now knowing that EXIF is purposefully still removed without an option to enable it I'm kind of disappointed. Gonna have to use XnView converter...

**Comment by b4imetu** [comment]
> Closing this issue for now. With V2 release and libSquoosh release, we've been consistent with removing EXIF data, and I'd say no-EXIF output is the direction we chose for this project.

In light of Android's official definition of [Motion Photo Format](https://developer.android.com/media/platform/motion-photo-format#motion-photo), many people are requesting that the image itself be compressed while maintaining the Camera XMP metadata, which describes how to display the still image file and video file contents, and the Container XMP metadata, which describes how to locate the video file contents.

For HDR images, many people must also keep [HDR Gain map metadata](https://developer.android.com/media/platform/hdr-image-format#HDR_gain_map_metadata)
