### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by roygrubb** [GoogleChromeLabs/squoosh#577]
Doesn't work in mobile (iOS, anyway).
fineuploader handles this well, but I don't know how well that library would fit in with your implementation.

**Comment by jakearchibald** [comment]
Can you describe how it doesn't work?

**Comment by roygrubb** [comment]
Apologies - your question made me go and search for drag and drop on iPad, and I found it was possible. I thought it wasn't.  

It's worth mentioning what fine-uploader does on iPad, which I think is more intuitive:
- touch the upload area
- a popup offers: Take Photo or Video / Photo Library / Browse
- touching Photo Library shows the usual iOS panel from which one or more images can be selected, and pressing 'Done' loads them into the upload area for processing.
iPad drag and drop works with this as well.

**Comment by kasusa** [comment]
it is just not useable.if you have a iphone just try it.
canyou make a app of squoosh?

**Comment by jakearchibald** [comment]
Can you describe how it isn't usable?

**Comment by jakearchibald** [comment]
Closing until further details are provided
