### ISSUE TITLE
Show Exiff data

### ISSUE THREAD

**Issue by thibaultmol** [GoogleChromeLabs/squoosh#585]
**Is your feature request related to a problem? Please describe.**
It isn't

**Describe the solution you'd like**
When opening a file, there could be a button somewhere to 'show Exiff data'

**Does other service/app have this feature?**
Websites like this exist http://exif.regex.info/exif.cgi but it isn't HTTPS (I know there are https versions out there, but this is the first one that comes on Google).

**Additional context**
I sometimes want to check exiff data while on my chromebook and don't want to upload my file to some 3rd party server, I think it's very much doable to have this be done fully locally

EDIT: I know this doesn't really fit with Squoosh's concept of being 'just a compression tool'. But I feel like nobody else has tried porting the C code for extracting Exiff data to a webapp

**Comment by kosamari** [comment]
Closing this as out of bound for the purpose of web app. I agree this is a good web app idea!
