### ISSUE TITLE
Agree on code style & fix linting

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#59]
At the start we agreed to semistandard, but it seems like nobody particularly likes it, especially the rule that requires a space between a function name and `()`.

Is anyone using a set of linting rules for this project right now? Might make a good starting point. @developit it looks like you're using one, care to share?

**Comment by surma** [comment]
FWIW, I have good experiences with `prettier`. We could just have it format the stuff for us. There’s a couple things that some mighty not like (like double quotes over single quotes), but at least you can just write your code however you like and prettier fixes it.

**Comment by developit** [comment]
I'd like to try Prettier as well. I wasn't using any special configuration, just the eslint VSCode plugin and the [rules from our package.json](https://github.com/GoogleChromeLabs/squoosh/blob/79dfe399789860119345a4df505c34815b13b9cf/package.json#L13-L32).

**Comment by surma** [comment]
FWIW, `tslint` has _some_ fixing functionality, which can now be run with `npm run lintfix`.

Can this be closed now that #62 has landed?

**Comment by jakearchibald** [comment]
Yep, done!
