### ISSUE TITLE
When JS is disabled no message is displayed

### ISSUE THREAD

**Issue by lucacasonato** [GoogleChromeLabs/squoosh#593]
**Describe the bug**
When opening the page in any browser and disabling JS, the page does not react. It just displays everything like normal but does not respond to any clicks (obviously).

**To Reproduce**
1. Go to squoosh
2. Disable JS
3. Reload page

**Expected behavior**
Display a message or screen that JS is needed to use Squoosh.

**Version:**
 - OS w/ version: any
 - Browser w/ version any
 - Node version: n/a
 - npm version:  n/a

**Comment by kosamari** [comment]
probably render message on the same position as error dialogue
