### ISSUE TITLE
PNG image causes an error message and won't compress to WEBP

### ISSUE THREAD

**Issue by jake74** [GoogleChromeLabs/squoosh#594]
I've created a fairly large PNG (1920x475px) of which the content is mostly transparent/alpha channel. Created in Photoshop and exported as a 24-bit PNG using the 'Save for Web' option.

Uploading to Squoosh.app works ok (drag and drop) and OptiPNG works for reducing the palette, but changing the compression option to WEBP causes the 'working' spinner to twirl for a 20-30 seconds, then an error message to appear—

'Processing error (type=webp): Error: float unrepresentable in integer range'

Nothing further happens. The spinner keeps spinning.
I cannot download a compressed Webp image.

Repeatable every time I've tried to upload in two different browsers. 

On one occasion, after 3 or 4 minutes, I could change compression options, but the image size was much larger than the original image uploaded.

MacOS 10.14.5
Chrome 74.0.3729.157 64-bit / Opera 60.0.3255.95

Attachment: footer-smoke.png image that causes the error
![footer-smoke](https://user-images.githubusercontent.com/870128/57974667-0404ac00-79b4-11e9-8c6c-c28f95815aab.png)

**Comment by SignpostMarv** [comment]
Same issue on Win10 Version 74.0.3729.157 (Official Build) (64-bit)

Issue only appears to occur when using lossy mode, lossless and lossless w/ slight loss both behave as expected.

w/ console error:
> index.tsx:470 RuntimeError: float unrepresentable in integer range
    at wasm-function[211]:26
    at wasm-function[571]:51
    at wasm-function[581]:125
    at wasm-function[585]:187
    at wasm-function[719]:384
    at wasm-function[725]:920
    at wasm-function[368]:37
    at wasm-function[395]:727
    at wasm-function[807]:173
    at wasm-function[427]:113

**Comment by surma** [comment]
This seems to work fine in v2 :)

**Comment by chsWeb** [comment]
I am experiencing this problem when attempting to optimize a WPBP image saved from Photoshop and also PNG images saved from Photoshop.

**Comment by surma** [comment]
Can you share an image that causes a crash?
