### ISSUE TITLE
file-drop element improvements

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/squoosh#60]
There are a number of improvements that we can make to the file-drop element that are not directly related to the needs of the app. (see https://github.com/GoogleChromeLabs/squoosh/pull/56 for more context)

* [ ] Add enter and leave events
* [ ] Add .files support to ondrop (filter...)
* [ ] Add valid/in-valid events that map to the css class changes.

**Comment by jakearchibald** [comment]
Marking as V1, as I think the element needs to support these things to be useful externally.
