### ISSUE TITLE
request for umbrella issue to track present/planned/rejected image formats

### ISSUE THREAD

**Issue by SignpostMarv** [GoogleChromeLabs/squoosh#608]
**Is your feature request related to a problem? Please describe.**
I (and likely others also) are curious about image format support in squoosh

**Describe the solution you'd like**
1) A pinned umbrella issue/roadmap intended to track:
    * which issues/pull requests/branches are being used for planned support
    * rejected formats, with a summary of their reason and initial issue where appropriate (i.e. #324 for HEIF)
2) track the image formats listed on caniuse.com [git repo](https://github.com/Fyrd/caniuse/search?q=image+format&unscoped_q=image+format) / [web search](https://caniuse.com/#search=image%20format)

**Does other service/app have this feature?**
umbrella issues/roadmaps are a pretty common thing.

**Additional context**
supplementary planned/rejected info for subformats, i.e. apng <> gif, gif > [webm](https://github.com/GoogleChromeLabs/webm-wasm) etc.

**Comment by surma** [comment]
Yeah, I’m not opposed. We could also use the GitHub Wiki for this purpose.

@jakearchibald WDYT?

**Comment by jakearchibald** [comment]
Is https://github.com/GoogleChromeLabs/squoosh/projects/3 the thing we're talking about? I guess we'd need a rejected column.

**Comment by surma** [comment]
OOoooh! Yes it is. Closing this then.
