### ISSUE TITLE
What should happen if we drop multiple images in to the page?

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/squoosh#61]
Right now, if we drop multiple images on to the page the app will find the first image in the FileList object and it will open that. 

I think the user's expectations would that it the app should handle multiple files 'somehow'.

Here are a couple of potential solutions:

* Keep it as it is.
* Show a selector with a list of all valid image files, letting the user select only one.
* For each image, open up a new instance of squoosh (I think it's classed as a user gesture) and push the image into that new instance.

**Comment by jakearchibald** [comment]
I'm fine with picking the first item for V1. We can revisit this if/when we have batch processing.

**Comment by kosamari** [comment]
closing this issue for now.
