### ISSUE TITLE
Use favicon to indicate when work is happening/is done

### ISSUE THREAD

**Issue by Rich-Harris** [GoogleChromeLabs/squoosh#644]
**Is your feature request related to a problem? Please describe.**

When dealing with large images, it can take a little while for things to happen. I can either stare at the tab while it's crunching, or switch over to a different tab with a plan to return a bit later, which I will often forget to do for minutes at a time.

**Describe the solution you'd like**

It'd be nice if the favicon changed to something that indicated that it was working, then later changed to something indicating it was done (a checkmark?) so i can goof around on twitter but still see when it's finished.

**Does other service/app have this feature?**

None spring to mind

**Comment by jakearchibald** [comment]
Would it be enough to prepend ⏳ to the document title? That would also work for Safari.

**Comment by Rich-Harris** [comment]
Oh, Safari, you really are the runt of the litter.

Changing the title definitely gets us most of the way there. Personally I tend to have 30+ tabs open so that I can't see titles, only favicons, but that's on me. I'd say that's a decent plan.

**Comment by Rich-Harris** [comment]
(would be happy to try and rustle up a PR given a nudge in the right direction, btw)

**Comment by surma** [comment]
Go for it! I think you’d go about it by changing `document.title` in our (pretty huge) `<Compress>` component in the area where we handle the compression jobs and workers.

Let me know if you need more details than that :)

**Comment by jakearchibald** [comment]
https://github.com/GoogleChromeLabs/squoosh/blob/master/src/components/compress/index.tsx#L55

Unfortunately we currently track loading in three places. One for each side, and another overall "loading" for when we're loading/decoding/processing the image.

I guess you'll want to check all three of these in one of the post-update callbacks, and include the ⏳ in the title if any are true.

**Comment by Avi98** [comment]
Hi, is it still open can I work on this?
