### ISSUE TITLE
TIF cannot be opened

### ISSUE THREAD

**Issue by evayde** [GoogleChromeLabs/squoosh#687]
**Describe the bug**
Uploading a .TIF results in an error: “Invalid Image”

**To Reproduce**
1. Go to squoosh.app
2. Click on upload image
3. Take one of these http://www.fileformat.info/format/tiff/sample/ 
4. See the error

**Expected behavior**
Expecting this to work same as JPEG and PNG.

**Version:**
 - OS w/ version: iOS 12
 - Browser w/ version Edge Chromium 77

**Comment by aaronth07** [comment]
Same issue.

**Comment by jakearchibald** [comment]
Right now we only support whatever the browser supports, plus WebP & AVIF, so it's kinda expected that this doesn't work. We might one day add support for TIFF.
