### ISSUE TITLE
Compile with closure flag results in smaller js

### ISSUE THREAD

**Issue by kasperkamperman** [GoogleChromeLabs/squoosh#696]
Is there a reason that mozjpeg was not compiled with the closure flag? It results for me in a JS file that is about 21kb instead of 44kb. I had no problems in running the code.

In build.sh
...
```
emcc \
  --bind \
  --closure 1 \
  ${OPTIMIZE} \
```
...

**Comment by surma** [comment]
Interesting! I didn't even know about that flag. I should add that to most of your build script.s

**Comment by kripken** [comment]
I read the optipng Makefile now and had the same idea! Building with `--closure 1` it shrinks the JS from 108K to 46K. I opened #728, if that makes sense, then other codecs might benefit too.

**Comment by surma** [comment]
Shipped!
