### ISSUE TITLE
Help / example running mozjpeg in a worker (comlink)

### ISSUE THREAD

**Issue by kasperkamperman** [GoogleChromeLabs/squoosh#697]
I'm trying to understand all the concepts regarding WebWorkers in combination with encoding. 

As far as I understand in the example.html in the specific code folder (for example mozjpeg_enc) the encoding doesn't happen in a webworker. 

How would I import the "mozjpeg_enc.js" in a worker.js and run that? 

I looked for some information on comlink and found an article that shows it with ffmpeg (https://dev.to/chromiumdev/running-ffmpeg-with-wasm-in-a-web-worker-5gb5). 

```
importScripts("https://cdn.jsdelivr.net/npm/comlinkjs@3.0.2/umd/comlink.js");
importScripts("mozjpeg_enc.js");
Comlink.expose(mozjpeg_enc);
```

This gives me the error "TypeError: undefined is not an Object. (evaluating 'prop in endpoint')"

Probably I overlook something really basic, hopefully, someone can give me a hint. 
A small example or link to some resources would help really much. 

In the "complex js-heavy web apps" talk some code is shown however it seems psuedo JS code, because I can't find it anywhere:
https://youtu.be/ipNW6lJHVEs?t=1215

**Comment by surma** [comment]
Yeah, this should work. Not sure why it doesn't. Can you put your demo in a Glitch or something?
