### ISSUE TITLE
Transparency on PNG when converted to MozJPEG gets turned to black. Can we change it to white instead?

### ISSUE THREAD

**Issue by samson132** [GoogleChromeLabs/squoosh#699]
**Is your feature request related to a problem? Please describe.**
Many more websites use white as a background than black, converting to WebP is a solution but not currently supported widely. 

**Describe the solution you'd like**
Change transparency which is converted into black into white.

**Does other service/app have this feature?**
Not sure

**Additional context**
N/A

**Comment by ferrisbuellers** [comment]
I'd prefer to be able to specify the background colour for image formats that don't support transparency.

**Comment by pepelsbey** [comment]
Yes please, simple HEX input would be great. Something similar to Photoshop’s Matte option in Save for Web that mixes alpha transparency with the color of choice:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/105274/74132477-b4c47280-4bf7-11ea-9fc2-8e119a7e9b1c.png">

**Comment by pepelsbey** [comment]
I believe it’s close enough to #347 to be closed as a duplicate.

**Comment by surma** [comment]
Rolling into #736
