### ISSUE TITLE
Infinite Zoom Problem

### ISSUE THREAD

**Issue by andreazorzi** [GoogleChromeLabs/squoosh#700]
**Describe the bug**
It is possible to zoom in until it reaches infinity, and when it comes up we can no longer zoom out.
Then if you try to click on the - or + button, it becomes NaN

**To Reproduce**
- Zoom in until it reaches infinity
- Then click on the - or + button and it becomes NaN

**Expected behavior**
Perhaps it would be better to set a maximum zoom limit

**Comment by ramyrgab** [comment]
I want to take this up

**Comment by kosamari** [comment]
moving this to #1091 1091
