### ISSUE TITLE
Feature Request: AVIF support

### ISSUE THREAD

**Issue by aduh95** [GoogleChromeLabs/squoosh#702]
**Is your feature request related to a problem? Please describe.**

[AV1 Image File Format](https://aomediacodec.github.io/av1-avif/) is stable for a few months now, I think it would be nice to have it in Squoosh. It's a royalty-free format that claims to be more efficient than previous image compression formats.

**Describe the solution you'd like**

Implement [libavif](https://github.com/AOMediaCodec/libavif) in WASM.

**Does other service/app have this feature?**

We might want to get inspiration from [avif.js](https://www.npmjs.com/package/avif.js) (licensed under [CCO](https://github.com/Kagami/avif.js/blob/master/COPYING)).

**Additional context**

* [Chromium ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=960620)
* [Firefox ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1443863)
* [AV1-AVIF wiki](https://github.com/AOMediaCodec/av1-avif/wiki) (which lists other implementations)

**Comment by atjn** [comment]
AVIF support is set to go live in Chromium in 22 days: https://caniuse.com/#feat=avif

I would really like to already support it on my websites, but i don't have any viable tool for running and tweaking the encoder. Hoping Squoosh will add support soon :)

Tracking PR as of now: #722

**Comment by mathiasbynens** [comment]
#722 landed, and so did #791! 🥳  What else is needed to close this issue? UI work?

**Comment by jakearchibald** [comment]
We're doing an overhaul of Squoosh in terms of build and UI. We're targeting Chrome Dev Summit for launching this and many other exciting features.

**Comment by jakearchibald** [comment]
Actually, we've had a rethink, we might get this out earlier.

**Comment by jakearchibald** [comment]
Landed in 0934c6c00f6ec7be9f5f4e7593a9a2e2fd83b394!

We've got more work to do here in terms of performance. Also, the codec has 4:2:0 and 4:0:0 modes, but I've disabled them for now because they were chucking out files that couldn't (sometimes) be decoded.
