### ISSUE TITLE
SVG doesn't load image tag images

### ISSUE THREAD

**Issue by Lergin** [GoogleChromeLabs/squoosh#703]
**Describe the bug**
When loading an SVG image that uses the \<image\> tag to use additional images within the SVG image these do not show up.

**To Reproduce**
1. Open Squoosh
2. Upload an SVG image with the \<image\> tag for example:
```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" version="1.1" xml:space="preserve">
    <g class="main">
        <g>
            <image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://squoosh.app/icon-demo-logo.4bfd6.png"/>
        </g>
        <g>
            <text x="20" y="35" class="small">Test</text>
        </g>
    </g>
</svg>
```
4. The included image does not appear

**Expected behavior**
The included image should be visible in the same way as if the SVG image is opened directly in the browser

**Version:**
 - OS w/ version: Windows 10
 - Browser w/ version Chrome 77

Update: It does work if the link to the image is a data URL

**Comment by surma** [comment]
Yeah, we can't read back pixels from a canvas that contains pixels from another origin (cross-origin violation), so this won't ever work. It's WAI.

Data URLs will work, yes :)
