### ISSUE TITLE
Processing error (type=png): Error: unreachable

### ISSUE THREAD

**Issue by alfaodin** [GoogleChromeLabs/squoosh#711]
**Describe the bug**
Tried to reduce to a half the size of an image, the image was a png.

**To Reproduce**
1. Drag and drop the image
2. Click on OptiPNG
3. Click on Resize
4. Click on presets
5. Click on 50%
6. An Error is shown

**Expected behavior**
Reduce by a half.

**Version:**
 - Windows 10 Pro
 - Versión 78.0.3904.70 (Build oficial) (64 bits)

- Original image:
![FGZ_Atlas_Southamptom](https://user-images.githubusercontent.com/8097675/67955063-fb99d980-fbbf-11e9-9546-9bc5fb8cea77.png)

**Image error**

![Error](https://user-images.githubusercontent.com/8097675/67955814-23d60800-fbc1-11e9-9756-649ca864dd4d.jpg)

**Adicional Console output**
VM14:37 RuntimeError: unreachable
    at wasm-function[70]:0x3a48
    at wasm-function[25]:0x3633
    at wasm-function[31]:0x37b5
    at wasm-function[54]:0x39dc
    at wasm-function[28]:0x371f
    at wasm-function[22]:0x34ec
    at wasm-function[23]:0x355e
    at wasm-function[1]:0x15a5
    at s (https://squoosh.app/process-resize.44cbe.worker.js:1:220)
    at o (https://squoosh.app/process-resize.44cbe.worker.js:1:1099)

**Comment by carbonology** [comment]
Been getting this issue a lot when trying to resize, not only with OptiPNG but with MozJPG as well

**Comment by Rocinante89** [comment]
getting it with webp too

**Comment by soraryu** [comment]
This is happening more and more.
![image](https://user-images.githubusercontent.com/2693840/76808262-75390980-67e7-11ea-8994-9ce431499a12.png)
@surma?

**Comment by dnnp2011** [comment]
I'm also getting this error frequently.
Squoosh has been practically useless for PNG images lately.

Here's my console output:

<img width="698" alt="Screen Shot 2020-06-30 at 1 53 22 PM" src="https://user-images.githubusercontent.com/20608595/86160021-2f275d80-bad9-11ea-849c-8c5aed47612b.png">

**Comment by hybridherbst** [comment]
This is still happening, a lot.
Easy to reproduce too: add any PNG image, change "Resize" to 50%, see error.
@surma any idea? There's also the more recent #758 with the same problem.

**Comment by jakearchibald** [comment]
@hybridherbst that seems like another issue. Filed https://github.com/GoogleChromeLabs/squoosh/issues/782

**Comment by jakearchibald** [comment]
No, it isn't another issue, apologies, but I'll continue to investigate it in the other ticket.

**Comment by jakearchibald** [comment]
Thanks to everyone who reported this! It's now fixed.

**Comment by hybridherbst** [comment]
Thank you! Does this also close #758?

**Comment by surma** [comment]
Ah yes, thank you

**Comment by JNavas2** [comment]
I'm still seeing this error on Android when I try to resize images taken with the camera.

![Screenshot_20210415-130927](https://user-images.githubusercontent.com/14850792/114932098-f3e9e700-9deb-11eb-86bc-b4dd9ef5790b.png)
