### ISSUE TITLE
Codec to consider: JPEG XL

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/squoosh#721]
I searched within this repo and GitHub returned no results, so... here's an issue about the JPEG XL codec :)

More info about this codec: https://jpeg.org/jpegxl/

JS/Wasm demo: https://libwebpjs.appspot.com/jpegxl/

**Comment by jakearchibald** [comment]
Isn't this really licencey and patenty?

**Comment by surma** [comment]
I am working on this now. To be clear, JPEG X**R** is patenty, JPEG X**L** is royalty-free and open source.

**Comment by cctse** [comment]
I found a cool project, https://github.com/imager-io/imager，it's really impressive in some cases

**Comment by surma** [comment]
Shipped!
