### ISSUE TITLE
Add support for brunsli

### ISSUE THREAD

**Issue by goyuix** [GoogleChromeLabs/squoosh#731]
From their README: 

Brunsli is a lossless JPEG repacking library. Brunsli allows for a 22% decrease in file size while allowing the original JPEG to be recovered byte-by-byte.

https://github.com/google/brunsli

**Comment by jakearchibald** [comment]
This is becoming part of jpegxl, so we're focusing on that instead https://github.com/GoogleChromeLabs/squoosh/pull/723
