### ISSUE TITLE
Show used command for compressing images

### ISSUE THREAD

**Issue by dehghani-mehdi** [GoogleChromeLabs/squoosh#732]
Squoosh is a GUI on top of some tools (mozjpeg, ...). in order to use this tools, you should run them and pass some argument, e.g: `optipng input.png -o 3 -out output.png`.

It would be great to show which command do you run (based on user settings) to generate the output.

**Comment by surma** [comment]
This is not quite feasible, sadly. We try to use the libraries behind those tools and there isn’t always a clear 1:1 mapping from the options we expose to CLI parameters.
