### ISSUE TITLE
Add Support for HEIF / HEIC

### ISSUE THREAD

**Issue by seventhmoon** [GoogleChromeLabs/squoosh#733]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Android and iOS are supporting HEIF / HEIC. It is good if we could have squoosh to support this image format.

**Does other service/app have this feature?**
Android OS, iOS

**Additional context**
https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

**Comment by jakearchibald** [comment]
Unfortunately those formats come with a licence fee, so we can't add them to the app.

**Comment by fgeierst** [comment]
> Note however that Nokia also grants its patents on a royalty-free basis for non-commercial purposes.
 from: https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format#Patent_licensing

Does that help?

**Comment by hyunbinseo** [comment]
Any plans on supporting HEIF, HEIC? It's been 5 years.

Similar issue was closed as dupe, and this issue seems to be a dead end.

- https://github.com/GoogleChromeLabs/squoosh/issues/1360

At least, could this issue be kept opened? I thought it was resolved, but it was not.

**Comment by jakearchibald** [comment]
https://github.com/GoogleChromeLabs/squoosh/issues/733#issuecomment-596927199 still applies.

@fgeierst linked to https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format#Patent_licensing:

> HEIF itself is a container that may not be subject to additional royalty fees for commercial ISOBMFF licensees. Nokia also grants its patents on a royalty-free basis for non-commercial purposes.[[81]](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format#cite_note-nokiaheiflicense-81) When containing images and image sequences encoded in a particular format (e.g., HEVC or AVC) its use becomes subject to the licensing of patents on the coding format.

I assume, when people are referring to HEIF / HEIC, they're actually referring to HEVC within the container, which "becomes subject to the licensing of patents on the coding format".
