### ISSUE TITLE
Dilation for conversion of transparent PNGs to JPG

### ISSUE THREAD

**Issue by soraryu** [GoogleChromeLabs/squoosh#735]
**Is your feature request related to a problem? Please describe.**
A common usecase for Squoosh for me is reducing 3D model textures for web usage, e.g. for use in GLB files.
Commonly, these look like this:
![MeshHolder_0DiffuseMap](https://user-images.githubusercontent.com/2693840/77011235-b22e0900-696b-11ea-9c42-ab83900b0e8e.png)

Now, when converting those to JPEG, transparent areas get replaced by black.
It would be great if there was a "dilation" feature that dilates the non-transparent areas, as is commonly done to avoid mipmapping issues.

**Describe the solution you'd like**
The result would look similar to this for the above input:
![MeshHolder_0DiffuseMap-dilated](https://user-images.githubusercontent.com/2693840/77013137-b9571600-696f-11ea-948a-bdc67d7eba4f.png)

**Comment by surma** [comment]
Oh interesting! Do you know of any library that does this?

**Comment by surma** [comment]
Rolling into #736
