### ISSUE TITLE
Should we really be optimising for size?

### ISSUE THREAD

**Issue by RReverser** [GoogleChromeLabs/squoosh#745]
So far, it seems that we have been optimising all codecs for size rather than speed. While this is understandable in some situations, I'm feeling a bit sceptical about its usefulness for the Squoosh scenario.

Sure, it saves some time when loading Wasm codec for the first time, but arguably user is going to spend way more time actually tweaking params and compressing images, so in the summary they are probably going to lose more time waiting for compression results produced by unoptimised code than they saved on that initial loading.

Same applies, even in greater extent, to low-end devices. While many of these might be on slow networks and save time while loading codecs, they're going to spend even more time in compression afterwards ~~, and absence of a full-blown optimizing compiler on mobile will make unoptimized Wasm disproportionally even slower~~.

As such, I'd argue that we should recompile codecs and target speed in Emscripten and Rust instead for future additions. Thoughts?

**Comment by surma** [comment]
I did a spread sheet when we were originally working on Squoosh back comparing `-Os`, `-Oz`, and `-O3`. IIRC the result was that `-Os` was equally fast as `-O3` (with an occasional slight regression) while being a _tiny_ bit smaller than `-O3`. `-Oz` was unproportionally slower for tiny size savings over `-Os`. So that’s why we ended up using `-Os`. 

That being said, I am happy to revisit that decision. Let the number speak!

**Comment by RReverser** [comment]
@surma Do you still have that spreadsheet around by any chance? Would love to take a look at least at the previous numbers for now.

**Comment by RReverser** [comment]
Also, did you test on desktop only or on mobile as well? Difference in compilers likely matters a lot.

**Comment by RReverser** [comment]
Well this was disappointing given the time it took to collect comprehensive measurements, but at least now we know for sure :) https://docs.google.com/spreadsheets/d/1VpN2fFYh07VbC55_XBZjAp9yK0Kejr3Z3auyE4MDdoY/edit?usp=sharing

<table>
  <tr>
    <th></th>
    <th>Mozjpeg</th>
    <th>OxiPNG #2</th>
    <th>OxiPNG #6</th>
    <th>WebP #4</th>
    <th>WebP #6</th>
  </tr>
  <tr>
    <td>Chrome Desktop (-Os, ms)</td>
    <td>253</td>
    <td>3,195</td>
    <td>6,633</td>
    <td>650</td>
    <td>3,483</td>
  </tr>
  <tr>
    <td>Chrome Desktop (-O3, ms)</td>
    <td>210</td>
    <td>2,668</td>
    <td>6,461</td>
    <td>638</td>
    <td>3,413</td>
  </tr>
  <tr>
    <td>Chrome Desktop (diff, ms)</td>
    <td>-44</td>
    <td>-527</td>
    <td>-172</td>
    <td>-12</td>
    <td>-70</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Firefox Desktop (-Os, ms)</td>
    <td>252</td>
    <td>3,198</td>
    <td>8,023</td>
    <td>560</td>
    <td>3,419</td>
  </tr>
  <tr>
    <td>Firefox Desktop (-O3, ms)</td>
    <td>259</td>
    <td>3,169</td>
    <td>7,904</td>
    <td>600</td>
    <td>3,458</td>
  </tr>
  <tr>
    <td>Firefox Desktop (diff, ms)</td>
    <td>7</td>
    <td>-29</td>
    <td>-119</td>
    <td>40</td>
    <td>39</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Chrome Android (-Os, ms)</td>
    <td>848</td>
    <td>11,430</td>
    <td>26,894</td>
    <td>2,515</td>
    <td>13,521</td>
  </tr>
  <tr>
    <td>Chrome Android (-O3, ms)</td>
    <td>851</td>
    <td>11,409</td>
    <td>27,082</td>
    <td>2,470</td>
    <td>13,542</td>
  </tr>
  <tr>
    <td>Chrome Android (diff, ms)</td>
    <td>2</td>
    <td>-21</td>
    <td>189</td>
    <td>-46</td>
    <td>21</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Firefox Android (-Os, ms)</td>
    <td>1,005</td>
    <td>11,940</td>
    <td>28,131</td>
    <td>2,682</td>
    <td>14,916</td>
  </tr>
  <tr>
    <td>Firefox Android (-O3, ms)</td>
    <td>1,006</td>
    <td>11,926</td>
    <td>28,078</td>
    <td>2,683</td>
    <td>14,928</td>
  </tr>
  <tr>
    <td>Chrome Desktop (diff, ms)</td>
    <td>0</td>
    <td>-14</td>
    <td>-53</td>
    <td>1</td>
    <td>12</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Wasm+gz size (-Os, b)</td>
    <td>52,907</td>
    <td colspan="2">142,819</td>
    <td colspan="2">79,918</td>
  </tr>
  <tr>
    <td>Wasm+gz size (-O3, b)</td>
    <td>57,819</td>
    <td colspan="2">166,975</td>
    <td colspan="2">101,741</td>
  </tr>
  <tr>
    <td>Wasm+gz size (diff, b)</td>
    <td>4,912</td>
    <td colspan="2">24,156</td>
    <td colspan="2">21,823</td>
  </tr>
</table>

I'll close this issue for now but we can revisit again in the future if engine pipelines change.
