### ISSUE TITLE
Integrate WebP

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#75]
This is a little more involved than MozJPEG, as some browsers will need the decoder too.

* [x] WASM the decoder.
* [ ] Integrate the decoder & enable the encoder for all browsers.

When integrating the decoder, it should be done in a reusable way, so we can do a similar thing for FLIF & AV1.

**Comment by surma** [comment]
WebP decoder is already on master :)

**Comment by jakearchibald** [comment]
I'm going to take on integrating the encoder
