### ISSUE TITLE
[Selenium] Image sizes don't change

### ISSUE THREAD

**Issue by ghost** [GoogleChromeLabs/squoosh#762]
Chrome Version 83.0.4103.97 (Official Build) (64-bit)

Image sizes don't change. That is the size of original image is here to stay.
Please, have a look at the video.

https://yadi.sk/i/jbzBZchNZpdNTg

I did change the images' widths. But in the the result widths and hights are those of the original image.

Well, I used Selenium. But this may be not the problem. But why the width and height didn't change may be a bug.

**Comment by surma** [comment]
My hunch is that no `change` or `input` events are being emitted from the size controls because you are changing the value via Selenium. So the engine doesn’t pick up on the new values.

**Comment by ghost** [comment]
I can't agree with you.

Please, look at another video: https://yadi.sk/i/mghO4M8sCN_GEA

I put a breakpoint preventing from downloading by Selenium. Then I downloaded the image manually.

First of all. As you can see, there was more than enough time for the engine to change the size.
Secondly, the user was invited to download the image (no spinning placeholder anymore).
Thirdly, I pressed the button manyally.

Even if we suppose that there was not enough time for the engine, isn't it itself a bug? Why should a program let a user download a file if it is not ready yet?

**Comment by kosamari** [comment]
Hey ya - with release of libSquoosh, you can now run squoosh programatically. Closing this for now.
