### ISSUE TITLE
Spatial spelt wrong

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/squoosh#766]
https://github.com/GoogleChromeLabs/squoosh/blob/3a5c0aa30cfa7158c36c03d7b5c02fcd38f430af/src/codecs/webp/options.tsx#L273

**Comment by filiptronicek** [comment]
For reference: https://www.dictionary.com/browse/spatial

**Comment by jakearchibald** [comment]
Fixed in https://github.com/GoogleChromeLabs/squoosh/pull/768
