### ISSUE TITLE
Style typings don't seem to regenerate on Windows

### ISSUE THREAD

**Issue by RReverser** [GoogleChromeLabs/squoosh#774]
Posting from https://github.com/GoogleChromeLabs/squoosh/pull/764#issuecomment-654990788 for separate tracking:

> This change seems to fail the build for me:
> 
> ```
> [tsl] ERROR in C:\src\squoosh\src\components\intro\index.tsx(197,26)
>       TS2339: Property 'installButton' does not exist on type '{ readonly "intro": string; readonly "logoContainer": string; readonly "logoSizer": string; readonly "logo": string; readonly "openImageGuide": string; readonly "selectButton": string; readonly "hide": string; ... 11 more ...; readonly "relatedLinks": string; }'.
> ```
> 
> Do I need to regenerate types somehow?

> FWIW I can also see that `src\components\intro\style.scss.d.ts`, which is git-ignored and so, I assume, autogenerated, doesn't contain that property.
> 
> @jakearchibald Is there some command I need to run to regenerate it?

> Hmm I wonder if this is yet another "Webpack regexes and Windows" problem like a bunch of others I've seen before. Could be some pattern in config still not matching the styles due to `\` or something like that...

> Found [/config/add-css-types.js@`dev`](https://github.com/GoogleChromeLabs/squoosh/blob/dev/config/add-css-types.js?rgh-link-date=2020-07-07T17%3A11%3A27Z), although still not sure how to force regeneration...

**Comment by RReverser** [comment]
I've just added Windows to Travis config, so you can see TypeScript failures on CI here: https://travis-ci.org/github/GoogleChromeLabs/squoosh/jobs/706156583

**Comment by surma** [comment]
Can we close this?

**Comment by RReverser** [comment]
Probably, yeah.
