### ISSUE TITLE
Remember settings on tab sleep/crash

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#78]
When the user changes settings for a codec, these should be saved somewhere. When they select that codec later, those settings should be restored.

Because of this, we probably want a "reset" button.

Settings should be remembered for each side of the screen. So side * codec.

The codec selected on each side should be remembered between page loads too.

**Comment by jakearchibald** [comment]
This gets really tricky when it comes to multiple tabs. Which settings are remembered? Tab A, or tab B? I guess it would be whichever's changed last. Or could you end up with the left settings from A, and the right settings from B?

This makes me wonder if we should only remember settings using session storage.

**Comment by kosamari** [comment]
Probably this is part of "save user defined setting" idea we've been discussing.
