### ISSUE TITLE
"unreachable"

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#782]
1. https://squoosh.app/
2. Open "device screen" image.
3. Activate resize.
4. Reduce size by 1px (many other values produce the same effect)
5. Error "mozjpeg unreachable".

This happens with other codecs too.

**Comment by jakearchibald** [comment]
This was introduced in 68177b7590b08427868f077f4e12656e6d62894e

**Comment by jakearchibald** [comment]
cc @RReverser - I'm digging into this, but since it's part of the Rust/wasm stuff it might be beyond me

**Comment by jakearchibald** [comment]
Ok, the issue is in the "Linear RGB" codepath. If that's disabled, it works fine.

**Comment by jakearchibald** [comment]
Bug reports of this (https://github.com/GoogleChromeLabs/squoosh/issues/711) mention that it only happens when importing PNG images, which suggests to me that it's caused by alpha values other than 255.

**Comment by jakearchibald** [comment]
I'm no longer sure the bug was introduced by 68177b7, but that's when the wasm was built after the breakage.

**Comment by jakearchibald** [comment]
The bug appears to be in `|v| (LINEAR_TO_SRGB_LUT[v as usize] * 255.0) as u8`

**Comment by jakearchibald** [comment]
Oh, ok, the bug only happens with both Premultiply _and_ Linear RGB, so the issue is that `|v, a| (v as f32) * 255.0 / (a as f32).clamp(0.0, 255.0)` is generating something that `|v| (LINEAR_TO_SRGB_LUT[v as usize] * 255.0) as u8` cannot handle. And the problem is when alpha is 0.

**Comment by JNavas2** [comment]
I'm still seeing this error on Android when I try to resize images taken with the camera.

![Screenshot_20210415-130927](https://user-images.githubusercontent.com/14850792/114932098-f3e9e700-9deb-11eb-86bc-b4dd9ef5790b.png)

**Comment by RReverser** [comment]
@JNavas2 `unreachable` is a generic Wasm failure might have a lot of potential causes. It's best if you open a new issue with specific repro steps.

**Comment by JNavas2** [comment]
New Issue #988
