### ISSUE TITLE
Open to a new logo?

### ISSUE THREAD

**Issue by jkvyff** [GoogleChromeLabs/squoosh#789]
**Is your feature request related to a problem? Please describe.**
Often if I recommend Squoosh to a friend, they make a comment on the initial logo of the hand how it looks a bit strange as well as having slight graphical errors.
At least it is nicer logo than Tinypng's panda always looking at my soul.

**Describe the solution you'd like**
I can or someone else can make a logo that has a bit more polish to replace the hand logo.

**Does other service/app have this feature?**
Squoosh's logo stands out to me and people I have talked to as an uncomfortable logo out of apps I use regularly, though I realize this may not be the common experience.

**Additional context**
<img width="608" alt="Screen Shot 2020-07-30 at 7 22 32 PM" src="https://user-images.githubusercontent.com/8835646/88993174-0c37c700-d29a-11ea-8330-b0e762484ee9.png">

**Comment by una** [comment]
Thanks for bringing this up! We're actively looking into updating and rebranding our product, and will have an update for you in the coming months.
