### ISSUE TITLE
scaling option for preview

### ISSUE THREAD

**Issue by BuyMyMojo** [GoogleChromeLabs/squoosh#795]
**Is your feature request related to a problem? Please describe.**
An option to change the scaling method in the preview window such as nearest neighbour

**Describe the solution you'd like**
possibly another button next to the scale percent that reveals a drop down menu of the different methods

**Does other service/app have this feature?**
no specifics I can think of

**Comment by surma** [comment]
We already provide a plethora of scaling methods in the “resize” section :)

![photo_jpg_-_Squoosh_and_Paul_Kinlan_-_Chat](https://user-images.githubusercontent.com/234957/89634021-9ab0d780-d89c-11ea-8375-5fd90bc7e1fb.jpg)

**Comment by jakearchibald** [comment]
I think the request here is different. It means using nearest neighbour in the preview, regardless of the resize method.

Fwiw, I wanted this originally, but I think browsers struggled with it. Eg I filed https://bugs.chromium.org/p/chromium/issues/detail?id=843615 at the time.

**Comment by jakearchibald** [comment]
Safari still fails some of those cases, but Chrome seems good now.

**Comment by BuyMyMojo** [comment]
yeah I'm referring to what Jake here said

**Comment by BuyMyMojo** [comment]
Added in #1132
