### ISSUE TITLE
Codec license clarification

### ISSUE THREAD

**Issue by jfoz** [GoogleChromeLabs/squoosh#796]
I noticed that Squoosh is being distributed under the Apache 2.0 license (seemingly in entirety?) but also includes codecs compiled from various projects that are often distributed under other licenses. For example, mozjpeg seems to be licensed under IJG, 3-clause BSD, and zlib: https://github.com/mozilla/mozjpeg/blob/master/LICENSE.md

Is it intended that these codecs have been re-licensed as Apache 2.0, or should it be assumed that the licenses of the codecs are still per the projects they were compiled from? If it's the latter, could the appropriate licenses be added to each of the codecs?

**Comment by surma** [comment]
Hey @jfoz,

thanks for filing this, seems like we lost track of the LICENSE files at some point in time. Just to be clear: We are not re-licensing any 3rd party code. I’ll re-add LICENSE files to the codecs soon.

**Comment by jfoz** [comment]
Thank you @surma 

For the time being, would it be possible to clarify how Squoosh contributions to the codecs should be credited when using the wasm codecs directly from Squoosh?

**Comment by surma** [comment]
All of Squoosh is under Apache-2.0 The codecs are under their original licenses. I just added `LICENSE.codec.md` to each codec and updated the `README`s in d4f8b7f.


Closing this. If there’s any more questions, feel free to ask.
