### ISSUE TITLE
Can't handle APNG file

### ISSUE THREAD

**Issue by ChengRui24** [GoogleChromeLabs/squoosh#799]
upload an APNG file, whatever i choose the OxiPNG or Browser PNG, the Output file is not animated

**Comment by surma** [comment]
Yeah, Squoosh has no support for animations. The UI currently very much canvas-based, so animation is already a technical challenge. But to _properly_ support animated formats, our UI would have to change a lot, where we would really need to offer a timeline scrubber and similar things so you could really inspect what is happening.

All in all, we are focusing on static images and don’t plan to add support for animated formats.
