### ISSUE TITLE
[offline/SW] Make worky offline

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#80]
Later in the project, we need to add a service worker to make the whole offline thing happen.

#77 needs to be considered along with this, as it'll involve a code-update flow that may be out of step with updating the main app.

**Comment by kosamari** [comment]
Question: assuming we'll use workbox or similar and not roll our own ya?

**Comment by jakearchibald** [comment]
Ended up rolling my own. Wasn't exactly the plan, but with the deadline looming I didn't have time to learn workbox.

**Comment by jakearchibald** [comment]
In addition to https://github.com/GoogleChromeLabs/squoosh/pull/234, I'm going to:

* [ ] Alert the user when the app is first available offline.
* [ ] Auto-reload the app if an update is installed before the user interacts.
* [ ] Otherwise, alert the user to the update.
* [ ] Create a changelog.
* [ ] Show the user the changelog the first time they load a particular version. The changelog will be the difference between the version they have now and the previous version they saw.

**Comment by kosamari** [comment]
re-tagging this for V2

**Comment by kosamari** [comment]
closing this as clean up. let's add new issues about better offline support
