### ISSUE TITLE
Reconsider if `ImageData` as the return type of decoders is a good idea

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/squoosh#803]
`ImageData` is not a thing in Node. It’s easy to shim, but not sure if we want to stick to it anyway.

cc @RReverser

**Comment by RReverser** [comment]
What is the alternative? If it's a custom class (like RawImage), then it seems it might as well be an ImageData shim.

**Comment by surma** [comment]
My main gripe with the current approach is that C++ code assumes a global names `ImageData` exists. Having to stick things onto `globalThis` just feels icky. But maybe it is the least terrible solution.

**Comment by RReverser** [comment]
Leaving for visibility: one more option that might be cleaner than both sticking a class on `globalThis` or exposing custom C++ class, is using an Emscripten preamble (e.g. via `--js-library`) to define custom module-scoped `ImageData` variable only in Node.js, and use global otherwise.
