### ISSUE TITLE
AVIF size bigger than PNG

### ISSUE THREAD

**Issue by nucliweb** [GoogleChromeLabs/squoosh#810]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
The AVIF file size is bigger than PNG format.

**To Reproduce**
1. Load this image in Squoosh
![Dctjpeg](https://user-images.githubusercontent.com/1307927/91342421-4df55800-e7db-11ea-92a1-8343407d5afc.png)
2. Convert to AVIF format

**Expected behavior**
An AVIF file smaller than the original

**Version:**
 - OS w/ version: macOS Catalina 10.15.6
 - Browser w/ version Version 84.0.4147.135 (Official Build) (64-bit)

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
- Original image 
![Dctjpeg](https://user-images.githubusercontent.com/1307927/91342671-a88eb400-e7db-11ea-91c3-70ecaf636c43.png)

- Output image from Squoosh _(Zipped, because GitHub don't upload AVIF files 🙈 )_

[Dctjpeg.avif.zip](https://github.com/GoogleChromeLabs/squoosh/files/5131630/Dctjpeg.avif.zip)

**Additional context, screenshots, screencasts**

<img width="1239" alt="squoosh" src="https://user-images.githubusercontent.com/1307927/91343054-3bc7e980-e7dc-11ea-871e-525e30b05cb2.png">

**Comment by jakearchibald** [comment]
> **Expected behavior**
> An AVIF file smaller than the original

This shouldn't be an expectation. Different formats are better at different things. PNG is optimised for low numbers of colours and repeating patterns. WebP's lossless mode is even better - it can get this image down to 1.66k.
