### ISSUE TITLE
"Browser JPEG" preset issue

### ISSUE THREAD

**Issue by GregBoss** [GoogleChromeLabs/squoosh#816]
"Browser JPEG" preset gives us an excellent balance of quality and compression, but unfortunately it makes the images "Baseline", even if uploaded file was "Progressive". I guess we should make "Progressive" images for the Web, as a best practise.

**Comment by jakearchibald** [comment]
Browser JPEG uses the JPEG encoder built into the browser. Therefore, it's different from browser to browser, and we have no control over it.

MozJPEG generally produces much higher quality files for the size, and offers more configuration.
