### ISSUE TITLE
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): ...

### ISSUE THREAD

**Issue by cctse** [GoogleChromeLabs/squoosh#826]
**Describe the bug**
```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected 127128 bytes, fell off end @+1242). Build with -s ASSERTIONS=1 for more info.
    at rn (https://squoosh.app/process-mozjpeg-enc.e4b15.worker.js:1:4867)
    at https://squoosh.app/process-mozjpeg-enc.e4b15.worker.js:1:19415
rn @ process-mozjpeg-enc.e4b15.worker.js:sourcemap:1
(anonymous) @ process-mozjpeg-enc.e4b15.worker.js:sourcemap:1
```

**To Reproduce**
1. open https://squoosh.app/
2. drop an image, not work; select format, not work
3. open debug then see the RuntimeError

**Expected behavior**

**Version:**
 - OS w/ version: Mac 10.15.6 (19G2021)
 - Browser w/ version [e.g. Chrome 85.0.4183.102]

**Comment by surma** [comment]
I can’t reproduce that at all :(

Can you try using Squoosh in incognito mode?

**Comment by cctse** [comment]
it work well on Firefox Developer Edition.  chrome and safari both run into err after I update squoosh to latest version last night. I'm not sure if this error is caused by the update or my poor network.

squoosh app also didn't work, attachment is the app log
[squoosh.app-1600085662274.log](https://github.com/GoogleChromeLabs/squoosh/files/5218461/squoosh.app-1600085662274.log)

**Comment by FrankKai** [comment]
Chrome can't work，but **Firefox** works well.
