### ISSUE TITLE
Jpeg xl new version

### ISSUE THREAD

**Issue by fabiorug** [GoogleChromeLabs/squoosh#836]
I clicked report a buf from the squoosh.app

https://gitlab.com/wg1/jpeg-xl/-/commit/4d70bd58fbcb758b61446aba447fedd9177a00c9
It has as far I understood from the code native experimental WASM support even for Ubuntu 20.04
**I would like if this commit will get added to Squoosh**
*if you have permission from the original author*

**Comment by surma** [comment]
We are actively working on JPEG-XL.
