### ISSUE TITLE
squoosh can not be under Apache 2.0 license as long as it uses imagequant (GPL3)

### ISSUE THREAD

**Issue by dtugend** [GoogleChromeLabs/squoosh#842]
The imagequant library used is under GPL3.

Squuosh is very likely to be considered a derviative work as defined by GPL3.

**[However, GPLv3 software cannot be included in Apache projects.](http://www.apache.org/licenses/GPL-compatibility.html)**

**Comment by surma** [comment]
Thank you. Please contact external-opensource-licensing@google.com if you would like to discuss.

**Comment by dtugend** [comment]
Thank you for your reply. To me this sounds like Google / you are hiding behind your legal team instead of doing the right thing and fixing the issue. We all know it's difficult to enforce GPL3 legally, even though the right thing would be to aknowledge the problem and remove the library or replace it with something else or obtain a proper different license from the original authors.

**Comment by dtugend** [comment]
I asked the author what he thinks.

Seems it's fine with him.

The main problem is the way squoosh is displayed on GitHub, which is somewhat misleading, since one might think it applies to whole project, since the codecs are stored in same repo (e.g. not as package / submodule).
![grafik](https://user-images.githubusercontent.com/3610128/98980561-08644380-251d-11eb-8e9e-f764786f145b.png)

Since it's fine with the author I aplogoize for the noise caused.
