### ISSUE TITLE
Reopening Feature Request #301 - Request for Batch File Uploads to Squoosh.ai for optimising multiple Images

### ISSUE THREAD

**Issue by BurgundyWillow** [GoogleChromeLabs/squoosh#843]
**Is your feature request related to a problem? Please describe.**
The feature request is related to #301 , and since it has been 2 years since the issue request was opened, I opened a new request referencing that. I am sorry if that is not as per forum rules. I have never opened an issue before.

**Describe the solution you'd like**
There need not be any major UI changes. the drag and drop can literally just say drop and drop files instead of the singular file. The backend may perform optimisations to the images in a loop, for a start. Changing image parameters individually could follow after the fact.

**Does other service/app have this feature?**
jpeg.io, GIMP, etc. provide this feature, through plugins. This has been discussed in #301

**Comment by surma** [comment]
We are working on batch processing, as said in #301.
