### ISSUE TITLE
"Copy image" from compressed side preview does'nt copy the real compressed image.

### ISSUE THREAD

**Issue by nonobio** [GoogleChromeLabs/squoosh#860]
Hello :)

**Describe the bug**
"Copy image" from compressed side preview does'nt copy the real compressed image.

**To Reproduce**
1. Open an image
2. Compress it with settings
3. Right click on compressed side preview
4. "Copy image"
5. Paste image somewhere, for instance a new mail in Gmail
6. The file copied and pasted seems to be a png file bigger than the original

**Expected behavior**
I would like to be able to just copy the resulting file, without having to save it as a real file.

**Version:**
 - OS w/ version: Windows 10
 - Browser w/ version 87.0.4280.66 (Build officiel) (64 bits)

Maybe what i want isn't possible ? It seems that a lot of compression application need to save the resulting file before to use it...

Thanks :)

**Comment by jakearchibald** [comment]
Unfortunately this isn't possible for a few reasons:

- Browsers will use PNG when copying an image to clipboard via right-click menus.
- Clipboard APIs will [sanitise](https://w3c.github.io/clipboard-apis/#dom-clipboard-write) input data. In practice this means converting images to PNG.
- The other side needs to support the format in the clipboard, and I believe most apps will look for PNG or another lossless bitmap format if it's available in the clipboard.

**Comment by nonobio** [comment]
Thans a lot for your clear explanations :)
