### ISSUE TITLE
feat: copy cli command

### ISSUE THREAD

**Issue by mathe42** [GoogleChromeLabs/squoosh#862]
**Is your feature request related to a problem? Please describe.**
I want to apply some config to multiple images. So I want to try it out in sqoosh and then apply to 20 or more images,

**Describe the solution you'd like**
I don't need a browser solution. Just a button "copy cli command" wich copy the current config as a command that I can run in a terminal would be nice. I can then add it in my own scripts.

**Does other service/app have this feature?**
Don't know.

**Additional context**
Nothing

**Comment by surma** [comment]
Shipped!

**Comment by mathe42** [comment]
Nice! Love it :D

**Comment by magic-akari** [comment]
This feature has gone. Can we add it back in?

**Comment by jakearchibald** [comment]
The CLI has been deprecated https://www.npmjs.com/package/@squoosh/cli
