### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by WorfKlingon** [GoogleChromeLabs/squoosh#867]
I clone the repository
version: 58a6abffbb3e908deb2804119246c34c3948742b
Follow the instructions:

> npm install
> npm run build

but when i do;

> rpm start

I have this error:

> ❯ npm start
> npm ERR! missing script: start
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\worf_\AppData\Local\npm-cache\_logs\2020-12-03T03_59_23_140Z-debug.log

the log is here: 
[2020-12-03T03_59_23_140Z-debug.log](https://github.com/GoogleChromeLabs/squoosh/files/5633604/2020-12-03T03_59_23_140Z-debug.log)

**Comment by jakearchibald** [comment]
If you're wanting to develop the site locally, it's `npm run dev`

**Comment by WorfKlingon** [comment]
thanks, its' work
But i can't convert any jpg image to avif image. I have 'processing error: Error: Encoding error' display in the browser
where can found error log messages, please?

or can run dev with optional tags to see what happend

**Comment by WorfKlingon** [comment]
> If you're wanting to develop the site locally, it's `npm run dev`

In my opinion it's usefull to include your remark in the readme.md to run locally the server for testing

**Comment by surma** [comment]
We haven’t actually updated the README for since our v2 work. You are kinda using a work-in-progress right now :D

**Comment by WorfKlingon** [comment]
Yes I have see that with your new big upgrade version. ;-)
Very beautifull UI 👍
