### ISSUE TITLE
Support for the FLIF codec

### ISSUE THREAD

**Issue by BuyMyMojo** [GoogleChromeLabs/squoosh#868]
Is it possible to integrate the FLIF codec [https://flif.info/](https://flif.info/)

This is the graph they supplied on their website:
![image](https://user-images.githubusercontent.com/46948241/100995415-d8eca800-35ab-11eb-841a-85b65c48fc45.png)

**Comment by surma** [comment]
FLIF is merged into and superseded by JPEG-XL. [This talk](https://www.youtube.com/watch?v=t63DBrQCUWc) has a lot of interesting info.

**Comment by BuyMyMojo** [comment]
I'll give it a watch then, thanks!
