### ISSUE TITLE
WebP quality broken in `dev` branch

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#873]
Since WebP was update, the quality has gone really bad. I haven't dug into it, but maybe they changed how their quality setting works and we didn't update UI/bindings to cater for it?

**Comment by jakearchibald** [comment]
It's happening in both the simd version and the regular version.

**Comment by RReverser** [comment]
I haven't heard of any changes here, but maybe? Can you send them an email?

**Comment by jakearchibald** [comment]
What do you want in the email, just a link to this issue?

**Comment by RReverser** [comment]
I guess yeah, you can just ask on our existing email thread with WebP folks if there were any changes to the quality param / value. I'm pretty sure I didn't change anything on the binding side that would affect it, so it must be an upstream change.

**Comment by RReverser** [comment]
(just came to the computer) Oh yeah, it does look pretty bad in terms of details in comparison with prod. I still don't see anything in https://github.com/GoogleChromeLabs/squoosh/pull/851 that would explain it, aside from the version bump - the only quality changes were in WebP2 (speed -> effort).

However, if this becomes time-sensitive and no solution is found, we can simply revert the WebP1 part of that PR (we'll lose SIMD on WebP1 but that's probably fine).

**Comment by RReverser** [comment]
Actually, as one more alternative, we can try to build against my fork with SIMD patches - https://github.com/RReverser/libwebp/commits/emscripten-simd - that branch contains Emscripten SIMD fixes on top of the version we used before (1.1.0) while the one in #851 uses upstream version with those fixes merged on top of master.

**Comment by RReverser** [comment]
I'm tempted to jump in, but it's a weekend, gotta try and keep work separate 😅 I'll be back on Tuesday if nobody fixes it before.

**Comment by jakearchibald** [comment]
I've done some bisecting, and 990018f is where it goes bad.

**Comment by RReverser** [comment]
> 
> 
> I've done some bisecting, and [990018f](https://github.com/GoogleChromeLabs/squoosh/commit/990018f758829405f377923af2ccd4fc537ca694) is where it goes bad.

Yes, that's what I meant by an upstream change (and, correspondingly, fix suggested in https://github.com/GoogleChromeLabs/squoosh/issues/873#issuecomment-739339565 which would revert it).
