### ISSUE TITLE
The sources of encoder was still updated before compiling

### ISSUE THREAD

**Issue by WorfKlingon** [GoogleChromeLabs/squoosh#874]
Fot example, i want to test the latest source git of AVIF encoder. Do the squoosh script do that when i rebuilt squoosh project?

**Comment by jakearchibald** [comment]
No. The build file is at https://github.com/GoogleChromeLabs/squoosh/blob/dev/codecs/avif/Makefile#L1. Note that you need both AVIF and AOM.

Last time I tried to update AOM to a later git commit, the quality was pretty broken.

Good luck!

**Comment by WorfKlingon** [comment]
is it easy to have a branch that get the latests commit from encoder to compile it and test it?

**Comment by surma** [comment]
For AVIF, all you need to do is change the commit hash in the line that @jakearchibald linked to. 
All other codecs follow a similar pattern.

**Comment by WorfKlingon** [comment]
thanks :-) I will try now

**Comment by WorfKlingon** [comment]
Following the recommendations of @jakearchibald , i do theses updates in the makefile (on local):

```
# CODEC_URL = https://github.com/AOMediaCodec/libavif/archive/31d7c6d1e32cf467ac24fb8c7a76c4902a4c00db.tar.gz
CODEC_URL = https://github.com/AOMediaCodec/libavif/archive/e937c5b9a42f3c238c8934e6e1b1df7b9369003c.tar.gz
CODEC_PACKAGE = node_modules/libavif.tar.gz

# LIBAOM_URL = https://aomedia.googlesource.com/aom/+archive/v2.0.0.tar.gz
LIBAOM_URL = https://aomedia.googlesource.com/aom/+archive/refs/heads/master.tar.gz

```
Doing that I try to synchronize both sources with git masters
Is it right?

Another question: where can i found the libavif dll and the aomenc.exe used by the local server?

**Comment by surma** [comment]
> Is it right?

Yes, now you only need to run `npm run build` in the codec folder (make sure you have Docker set up).

> Another question: where can i found the libavif dll and the aomenc.exe used by the local server?

All image compression happens in the browser via WebAssembly. The site is fully static and has no server components.
