### ISSUE TITLE
Use .mjs for JavaScript modules

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/squoosh#88]
Squoosh is mostly using TypeScript (`.ts`), but it also uses `.js` for https://github.com/GoogleChromeLabs/squoosh/blob/master/src/lib/fix-pmc.js despite it being a module.

Let's [follow our own advice](https://developers.google.com/web/fundamentals/primers/modules#mjs) and use `.mjs` to denote JS modules as opposed to classic scripts.

If this is a problem for our current toolchain, it would be good to identify the problem and raise it upstream.

**Comment by developit** [comment]
Grabbing this since it's a quick change.

**Comment by mathiasbynens** [comment]
Thanks Jason!

Hmm, https://github.com/webpack/webpack/blob/7aa1efb70e038b720b902b8b27094e4e02a7e4b8/lib/WebpackOptionsDefaulter.js#L313 seems to support `.mjs` already. But then there’s https://github.com/webpack/webpack/blob/master/lib/DelegatedModuleFactoryPlugin.js#L18 which doesn’t have `.mjs`. I’m not familiar with this part of the webpack code base, but I’ll take a look.

**Comment by mathiasbynens** [comment]
Follow-up: https://github.com/webpack/webpack/pull/7691 landed in webpack. \o/

**Comment by frank-dspeed** [comment]
maybe you want to also put some fresh comments on https://github.com/microsoft/TypeScript/issues/27957 as they simply ignore it :( when you want to use type checking via typescript .mjs will not get recognized as module

**Comment by frank-dspeed** [comment]
and maybe you should consider my suggestion to turn all files into .js then marking the package in package.json as type: module and use typescript with checkJs: true flag and use JSDOC annotations you can then still type check while working with nativ modules till they accept .mjs
