### ISSUE TITLE
Homepage text logo uses deprecated svg font

### ISSUE THREAD

**Issue by floogulinc** [GoogleChromeLabs/squoosh#895]
The logo with text (https://github.com/GoogleChromeLabs/squoosh/blob/dev/src/shared/prerendered-app/Intro/imgs/logo-with-text.svg) uses the svg `<font>` tag to define the `GoogleSans-Bold` font for the "squoosh" text.

This feature is [deprecated/obsolete](https://caniuse.com/mdn-svg_elements_font) and unsupported in most browsers, leading to inconsistent display of the logo:

| Chrome Windows | Chrome macOS | Safari macOS | Chrome Android |
|---|---|---|---|
| ![image](https://user-images.githubusercontent.com/1300395/101695987-0073c280-3a3b-11eb-93d9-345776bf72bd.png) | ![image](https://user-images.githubusercontent.com/1300395/101696114-36b14200-3a3b-11eb-84f3-a6753a1b1b12.png) | ![image](https://user-images.githubusercontent.com/1300395/101696336-990a4280-3a3b-11eb-9384-c45e04fedda8.png) | ![image](https://user-images.githubusercontent.com/1300395/101696383-a9bab880-3a3b-11eb-99a2-7e41447fd5dc.png) |

This text should be converted into paths to be consistent across devices.

**Comment by jakearchibald** [comment]
I'm not seeing the failure you're seeing in macOS. What version of Chrome are you using?

**Comment by jakearchibald** [comment]
I see the issue in Firefox though. Will fix. Thanks.
