### ISSUE TITLE
[CLI] No effect from --optimizer-butteraugli-target flag.

### ISSUE THREAD

**Issue by donmccurdy** [GoogleChromeLabs/squoosh#898]
**Describe the bug**

When running WebP compression with the CLI, I'm getting identical output (and pretty aggressive compression) regardless of the chosen `--optimizer-butteraugli-target` flag. I'm currently using that flag as my main way of tuning quality, and it seemed to work OK in v0.3.1, but in v0.6.0 it has no effect in my tests. 

**To Reproduce**
1. Input:  

<details>
<summary>Avocado.png</summary>

![Avocado](https://user-images.githubusercontent.com/1848368/101726685-dc7aa600-3a67-11eb-81a3-487fad3df28a.png)

</details>

2. Compress with `squoosh-cli --webp "{}" --optimizer-butteraugli-target 1.4 --max-optimizer-rounds 6 --output-dir ~/Desktop ~/Desktop/Avocado.png`
3. Compress with `squoosh-cli --webp "{}" --optimizer-butteraugli-target 0.0001 --max-optimizer-rounds 6 --output-dir ~/Desktop ~/Desktop/Avocado.png`
4. Output is identical (visually and in size) and significantly lower quality than the original.

[Archive.zip](https://github.com/GoogleChromeLabs/squoosh/files/5670545/Archive.zip)

**Expected behavior**

Low values of `--optimizer-butteraugli-target` should produce greater quality and lower compression.

**Version:**
 - OS w/ version: macOS 10.15.7
 - Node version: v14.14.0
 - npm version: v6.14.8

**Is your issue related to the quality of image compression?**

[Archive.zip](https://github.com/GoogleChromeLabs/squoosh/files/5670553/Archive.zip)

**Comment by surma** [comment]
`--optimizer-butteraugli-target` is only in effect when you use the auto-optimizer. Use `--webp "auto"`.

Definitely something where the docs need to improve :) And the CLI should probably warn if you set the butteraugli target and it won’t be used.

**Comment by donmccurdy** [comment]
Thanks! Yep, that's my mistake, and makes perfect sense.

**Comment by donmccurdy** [comment]
Hm, I'm still not sure I'm getting expected results though. For a couple different target distances...

```
❯ squoosh-cli --webp auto --optimizer-butteraugli-target 1.4 --max-optimizer-rounds 6 --output-dir ~/Desktop ~/Desktop/Avocado.png
1/1 ✔ Squoosh results:
 /Users/donmccurdy/Desktop/Avocado.png: 3.01MB
  └ .webp → 12.95KB (0.420%) using --webp '{quality:98.4375}'


❯ squoosh-cli --webp auto --optimizer-butteraugli-target 0.14 --max-optimizer-rounds 6 --output-dir ~/Desktop ~/Desktop/Avocado.png
1/1 ✔ Squoosh results:
 /Users/donmccurdy/Desktop/Avocado.png: 3.01MB
  └ .webp → 12.95KB (0.420%) using --webp '{quality:98.4375}'


❯ squoosh-cli --webp auto --optimizer-butteraugli-target 14.0 --max-optimizer-rounds 6 --output-dir ~/Desktop ~/Desktop/Avocado.png
1/1 ✔ Squoosh results:
 /Users/donmccurdy/Desktop/Avocado.png: 3.01MB
  └ .webp → 12.95KB (0.420%) using --webp '{quality:98.4375}'
```

...the output is unchanged, and pretty noticeably lower quality than the original. Maybe one of my options isn't getting passed through correctly here?

**Comment by surma** [comment]
hm, yeah something is going wrong here
