### ISSUE TITLE
WASM zopfli-png

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/squoosh#9]
https://github.com/subzey/zopfli-png

**Comment by tobiasdubois** [comment]
Why not zopflipng: https://github.com/google/zopfli

**Comment by surma** [comment]
The repo linked by @jakearchibald is literally zopfli but applied to PNGs.

It kinda applies to all PNG codecs, so it’s something that we’d have to re-think in terms of UI, but we definitely want to ship it.

**Comment by tobiasdubois** [comment]
What I meant was that there is already a zopflipng tool inside the official zopfli git. It is the tool I use, it compresses very well, but is very slow.

**Comment by jakearchibald** [comment]
Yeah, I probably meant to link to the Google one.

**Comment by jakearchibald** [comment]
Merging into #237
