### ISSUE TITLE
[CLI] Add better usage documentation in README (and link to it from CLI)

### ISSUE THREAD

**Issue by ganoipho6** [GoogleChromeLabs/squoosh#900]
**Is your feature request related to a problem? Please describe.**
I use Squoosh image compression very often. It helps me optimize quality with the most reasonable amount of usage. I am trying to apply it to my image directory but the lines of CLI code seem beyond my usability. I inserted the URL even changed or set my directory path but it is not working !!

**Describe the solution you'd like**
Please help me as well as many others by sharing the formula that you have run successfully.

demo: squoosh-cli --jxl ... then what's next?

**Does other service/app have this feature?**
The mass editing feature will help a lot for me as well as many people wishing to process photos with the quantity of 20-100 or more.

Thanks ALL !

**Comment by adrienpicard** [comment]
Can't seem to make it work either, using npx or after installing the package. I do get results but the file isn't saved on disk. I've tried with both the suffix and output directory options with no success.


```
~ npx @squoosh/cli test.jpg
0/0 ✔ Squoosh results:
 test.jpg: 236.22KB
```

**Comment by ganoipho6** [comment]
> Can't seem to make it work either, using npx or after installing the package. I do get results but the file isn't saved on disk. I've tried with both the suffix and output directory options with no success.
> 
> ```
> ~ npx @squoosh/cli test.jpg
> 0/0 ✔ Squoosh results:
>  test.jpg: 236.22KB
> ```

I have also tried and had problems like yours. The test.jpg file is not available. I try to replace it with an image link taken from the website or the link to the image in a folder on my hard drive, it not work.

**Comment by adrienpicard** [comment]
Ok so you must specify an encoder for it to work. These should work:

`npx @squoosh/cli --mozjpeg {} test.jpg`
`npx @squoosh/cli --mozjpeg {quality:80} test.jpg`

@surma Would be great to add the MozJPEG option that's missing in the ReadMe 😌

**Comment by ganoipho6** [comment]
@adrienpicard 

> Ok, vì vậy bạn phải chỉ định một bộ mã hóa để nó hoạt động. Những điều này sẽ hoạt động:
> 
> `npx @squoosh/cli --mozjpeg {} test.jpg`
> `npx @squoosh/cli --mozjpeg {quality:80} test.jpg`
> 

How can I use it with multiple photos in one folder?

I am trying to run it with lots of files, have you tested successfully with a multi-image folder?

**Comment by adrienpicard** [comment]
@ganoipho6 yes just use a wildcard this works fine `npx @squoosh/cli --mozjpeg {} ./*.jpg`

**Comment by ganoipho6** [comment]
> @ganoipho6 yes just use a wildcard this works fine `npx @squoosh/cli --mozjpeg {} ./*.jpg`
@adrienpicard 
![image](https://user-images.githubusercontent.com/15613348/101759991-ddb1de80-3b0c-11eb-88d3-59dc1d88d0a2.png)

I have tried with my directory. It doesn't seem to be working. I was thinking that I would have to find a way to make a list of filenames and then create a bash script file that looks like this. https://stackoverflow.com/questions/7290758/bash-script-read-all-the-files-in-directory

You can double-check the code or provide a screenshot that it works. My computer may be having problems.

**Comment by surma** [comment]
@ganoipho6 I think there is currently trouble with the CLI on Windows. @RReverser reported something similar. We’ll look into it!

**Comment by surma** [comment]
And regarding flags: Yes we need better documentation, but the main use-case for now is to use the “Copy CLI command” button in the web app to generate the flags for you.

![photo_jpg_-_Squoosh](https://user-images.githubusercontent.com/234957/101776640-26f03700-3ae9-11eb-8688-20cffe463b0a.png)

**Comment by surma** [comment]
I published v0.6.1 which fixes the behavior on Windows.

Leaving this issue open as a reminder to write better documentation.

**Comment by nealmcb** [comment]
Note that the main README doesn't even point to the CLI readme, which is at
* https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli

**Comment by surma** [comment]
> Note that the main README doesn't even point to the CLI readme

What do you think this link in [the README](https://github.com/GoogleChromeLabs/squoosh/blob/dc40f84a6533043a2ea5eb49ea4475fc30c9605a/README.md#cli) does?

![squoosh_README_md_at_dev_·_GoogleChromeLabs_squoosh](https://user-images.githubusercontent.com/234957/107127759-3bb23680-68b0-11eb-927e-acbc5e0207db.png)

**Comment by nealmcb** [comment]
Oops - sorry! Thanks for that @surma. I didn't go back to check all the links, and had assumed that one probably went to an announcement of some sort ,rather than documentation.

It still seems worthwhile to pull out some more documentation into the top-level readme, but for now, at least a search of the issues will lead to some pretty quick hints for folks.

**Comment by surma** [comment]
As I say [a couple comments back](https://github.com/GoogleChromeLabs/squoosh/issues/900#issuecomment-755310143):

> Leaving this issue open as a reminder to write better documentation.

This is definitely a short-coming of the CLI (and mostly due to cutting corners by me to make the deadline).

**Comment by chromaniac2** [comment]
Is wildcard on powershell working now? they are still giving me the error...

```(node:9756) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'D:\1Temp\New folder\*'
(node:9756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
