### ISSUE TITLE
[UI] Left-Right Comparison

### ISSUE THREAD

**Issue by jimbo2150** [GoogleChromeLabs/squoosh#902]
Currently the comparison at the bottom shows the difference between the left or right compression output to the original image file size.

I request a toggle be added to switch the comparison and show the difference between the left and right side. I often want to see the differences between two compression formats rather than the each side and the original.

**Comment by tomByrer** [comment]
Tried the UI lately?
I don't think they added the exact UI features you wanted, but you can slide the A/B.  Also you can clone the configuration to the other side (tiny arrow near the top of the config tab).

Or are you asking for an image diff?

**Comment by kosamari** [comment]
Hi, thanks for the feedback (and sorry it took us while to get back). 
This is a bit of UX puzzle. 

Yes, the percentage shows diff from original, but it also list the would-be size of an image based on different codec you select. So you can sort of see the size difference. I believe current set up is simplest.
