### ISSUE TITLE
Firefox Nightly: Invalid image error

### ISSUE THREAD

**Issue by staabm** [GoogleChromeLabs/squoosh#904]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
the website/tool is un-usable on firefox

**To Reproduce**
1. open https://squoosh.app in Firefox Nigthly

-> 
![grafik](https://user-images.githubusercontent.com/120441/101773547-3b363300-3aed-11eb-935b-0d3f762144ef.png)

(it looks like the old UI, .. in chrome I get a very differnt website)

2. Click on the 'Large photo' example (the most left example)

->

![grafik](https://user-images.githubusercontent.com/120441/101773670-6587f080-3aed-11eb-834f-b45c43992180.png)

**Expected behavior**
no error.. nearly same experience then in chrome

**Version:**
 - OS w/ version: windows10x64
 - Browser w/ version Firefox 85

**Comment by gavinharris-dev** [comment]
Having the same issue in Firefox too:

MacOS 11.4

Firefox: 89.0.2 (64-bit)
Chrome: Version 91.0.4472.114 (Official Build) (x86_64)

Tried the 'Large Photo' and 'Artwork'.

Error in Console:


main-app.2ef4b.js:1:79310
11:42:53.593 Uncaught (in promise) ChunkLoadError: Loading chunk 0 failed.
(error: https://squoosh.app/sw-bridge.953aa.js)
    e https://squoosh.app/:1
    Bt https://squoosh.app/main-app.2ef4b.js:1
    I https://squoosh.app/:1
    x https://squoosh.app/:1
    x https://squoosh.app/:1
    x https://squoosh.app/:1
    x https://squoosh.app/:1
    x https://squoosh.app/:1
    x https://squoosh.app/:1
    S https://squoosh.app/:1
    T https://squoosh.app/:1
    h https://squoosh.app/:1
squoosh.app:1:1682
11:45:24.878
Error: Couldn't decode image
    mt https://squoosh.app/main-app.2ef4b.js:1

**Comment by jakearchibald** [comment]
Hm, I can't reproduce this, and I'm on the same version of Firefox & OSX.

Do you have any extensions installed or flags enabled that might be causing this?

**Comment by jakearchibald** [comment]
@gavinharris-dev ah, you're stuck on an old broken version. It should fix itself if you close all squoosh tabs, then open it again.

**Comment by gavinharris-dev** [comment]
Nice one @jakearchibald! Tested in a Private window and it works.

I had to Unregister the Service Worker on both Firefox and Chrome to force the app to download the updated code (on my non-private window).

Love your work! 🙏
