### ISSUE TITLE
Scrollwheel zooming is uncapped and zooming in too far breaks the panning.

### ISSUE THREAD

**Issue by rphsoftware** [GoogleChromeLabs/squoosh#905]
**Describe the bug**
After zooming in really quickly with a "fast scroll" feature or an unlockable scroll wheel on the mouse, the zoom percentage can become infinite and make the image unpannable.

**To Reproduce**
1. Load any image
2. Scroll up a lot

**Expected behavior**
The zooming should be limited

**Version:**
 - OS w/ version: Arch Linux rolling
 - Browser w/ version: Chrome 87

**Is your issue related to the quality of image compression?**
No

**Additional context, screenshots, screencasts**
https://www.youtube.com/watch?v=id20luk5_xs

**Comment by jakearchibald** [comment]
Fixed in 14c3d190e9c7c0d324e0ce9c3b6c60ec904cdf3a
