### ISSUE TITLE
Drag&drop doesn't work with new version

### ISSUE THREAD

**Issue by kudlav** [GoogleChromeLabs/squoosh#920]
**Describe the bug**
I was using previous version and it worked fine. Then i switched to new version using Reload snackbar option and with this version I cannot use drag&drop.

**To Reproduce**
1. Go to https://squoosh.app/ when using old version
2. Click on Reload option
3. Drag and drop image

```
Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "https://squoosh.app/", lineNumber: 1, columnNumber: 0, data: null, stack: "re/this.openEditor@https://squoosh.app/:1:26937\nre/this.onFileDrop@https://squoosh.app/:1:26532\nC@https://squoosh.app/:1:4854\n_onDrop@https://squoosh.app/:1:12856\n" }
squoosh.app:1
```

**Expected behavior**
Open editor with dropped image.

**Version:**
 - OS w/ version: MacOS 11.1 (20C69)
 - Browser w/ version: Firefox 84.0 (64 bit)

**Comment by surma** [comment]
I can’t reproduce this on current stable with Firefox. Can you recheck that the issue is still there for you? And if so, please re-open.

**Comment by kudlav** [comment]
As I cannot start with old version I cannot follow the steps now.

**Comment by jakearchibald** [comment]
So it's working fine now?

**Comment by kudlav** [comment]
Yes, it's fine. I was upgrading some minor version using Reload snackbar button and it works fine.
