### ISSUE TITLE
[CLI] wrong version published to npm

### ISSUE THREAD

**Issue by DetachHead** [GoogleChromeLabs/squoosh#922]
**Describe the bug**
[the version on npm](https://www.npmjs.com/package/@squoosh/cli/v/0.6.0) is listed as 0.6.0, but it's actually 0.5.0
![image](https://user-images.githubusercontent.com/57028336/103146534-b1e25a00-4796-11eb-9293-7f476ef922f8.png)

**To Reproduce**
1. `npm i -g @squoosh/cli@0.6.0`
2. `squoosh-cli --version`

**Expected behavior**
outputs `0.6.0`

**Version:**
 - OS w/ version: Ubuntu 16.04.7 LTS
 - Node version: 15.4.0
 - npm version: 7.0.15

**Comment by surma** [comment]
Published v0.6.1 :)
