### ISSUE TITLE
[CLI] I have no idea what I am doing.

### ISSUE THREAD

**Issue by randoomx8** [GoogleChromeLabs/squoosh#924]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
No matter what command, I use, it prints out `RuntimeError: abort(RuntimeError: abort(Error: ENOENT: no such file or directory, open 'C:\Users\WorkPC\AppData\Roaming\npm-cache\_npx\12412\node_modules\@squoosh\cli\build\imagequant_node-009a0715.wasm'). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.`

**To Reproduce**
I believe the source of the issue just comes from me not knowing how to use CLI correctly.  
Install npm, npx and then navigate to a folder with images to compress, `cd C:\Users\WorkPC\Downloads\test`, then run a command with the setting copied from squoosh (I just decided to copy the default).  
`npx @squoosh/cli --mozjpeg '{"quality":75,"baseline":false,"arithmetic":false,"progressive":true,"optimize_coding":true,"smoothing":0,"color_space":3,"quant_table":3,"trellis_multipass":false,"trellis_opt_zero":false,"trellis_opt_table":false,"trellis_loops":1,"auto_subsample":true,"chroma_subsample":2,"separate_chroma_quality":false,"chroma_quality":75}'`  
The CLI usage section says I should use <files...> but it does not specify how to tell it to select a whole folder so I thought leaving it empty would do the job (this is what causes the error). I tried several other combinations, they just resulted in another error `The syntax of the command is incorrect.`.

**Expected behavior**
It batch compresses all the images on the folder using the settings I copied from the web version.

**Version:**
 - OS w/ version: Windows10
 - Browser w/ version N/A
 - Node version: v14.15.3
 - npm version: 6.14.9 (LTS)

**Is your issue related to the quality of image compression?**
N/A

**Additional context, screenshots, screencasts**
I know technologically illiterate people like me should not come close to the CMD but I really wanted to batch compress images...

**Comment by DetachHead** [comment]
it seems the CLI doesn't currently support passing a whole folder. however if you're using bash, you can append `*` to the path to expand the contents of the directory before it runs the command so it passes all the files individually, though this will fail if there are spaces in any of the filenames.

alternatively you can use my fork which does have this functionality. https://github.com/DetachHead/squoosh
specify directories by adding a traling `/` to the path.

**Comment by surma** [comment]
This is fixed in v0.6.1 :)
