### ISSUE TITLE
Hardware accelerated encoding/decoding/compression?

### ISSUE THREAD

**Issue by SUPERCILEX** [GoogleChromeLabs/squoosh#932]
Processing lots of files is pretty slow right now, so it'd be awesome to have hardware acceleration support.

**Comment by jakearchibald** [comment]
Which formats are you talking about, and which forms of hardware acceleration?

**Comment by SUPERCILEX** [comment]
I just googled "hardware accelerated jpg compress" before filing this issue, saw some results, and assumed you could use the gpu to do some of the processing. :) If this issue doesn't make sense, feel free to close it.

I was only able to find HA encoding for jpgs, so not sure if it's worth the trouble:
- JPEG: https://developer.nvidia.com/nvjpeg
- AV1 decoding only: https://developer.nvidia.com/nvidia-video-codec-sdk#NVDECFeatures

**Comment by jakearchibald** [comment]
We've been adding things like multithreading and SIMD to our codecs as they become available to web assembly, which is a form of hardware acceleration I guess.

However, when it comes to hardware encoders, that often restricts you to the particular encoder that's on the chipset. For instance, the h264 hardware encoder on my Macbook is fast, but it seems to produce inferior results compared to the software encoder x264, especially at higher bitrates.

We already offer things like "browser JPEG" which defer to the browser's JPEG encoder, which is a lot faster, and could (if the browser chooses) use particular hardware that accelerate the process. However, the built-in encoders seem to produce significantly poorer results than the non-browser equivalents.

Also, deferring to built-in encoders means results would be different on different machines that have different hardware. Again, we already see this with "browser JPEG" when you run in different browsers & operating systems (Safari defers to the operating system's encoders). Whereas when you use MozJPEG, you get the same results everywhere.

**Comment by SUPERCILEX** [comment]
Makes sense, thanks for explaining!
