### ISSUE TITLE
Add Apple touch icon for PWA icon

### ISSUE THREAD

**Issue by LookRain** [GoogleChromeLabs/squoosh#951]
**Is your feature request related to a problem? Please describe.**
On iOS safari, if user adds Squoosh to Home Screen to install it as a PWA, the icon of the App on Home Screen is a screenshot, which doesn't look very nice

![IMG_0207](https://user-images.githubusercontent.com/11829847/105816449-47b81180-5fef-11eb-8e80-6820bedf7919.jpg)

**Describe the solution you'd like**

Since iOS doesn't take the icon from `manifest.json` but from the `apple-touch-icon` link, the icons need to be listed in the generated html like this in different sizes

```html

<link rel="apple-touch-icon" href="touch-icon-iphone.png">
--
<link rel="apple-touch-icon" sizes="152x152" href="touch-icon-ipad.png">
<link rel="apple-touch-icon" sizes="180x180" href="touch-icon-iphone-retina.png">
<link rel="apple-touch-icon" sizes="167x167" href="touch-icon-ipad-retina.png">
```

**Does other service/app have this feature?**

It should be quite common for PWAs that are optimised for iOS

**Additional context**
# Add any other context or screenshots about the feature request here.

**Comment by atjn** [comment]
Consider using something like [pwa-asset-generator](https://github.com/onderceylan/pwa-asset-generator) to automate this.

**Comment by vigneshrajj** [comment]
Can I work on this issue?
