### ISSUE TITLE
another sw-bridge is broken down

### ISSUE THREAD

**Issue by myakura** [GoogleChromeLabs/squoosh#966]
**Describe the bug**
It loads v1 assets and shells but fails updating to v2.

**To Reproduce**
1. Be (un)lucky enough to have a pretty old copy of v1
2. Go to squoosh.app
3. Open DevTools and look at the error message in the console

**Expected behavior**
It should show a popup to upgrade to the v2 version

**Version:**
 - OS w/ version: macOS 10
 - Browser w/ version: Chrome 89

**Additional context, screenshots, screencasts**

![Screenshot: squoosh v1 with devtools open, console showing an error failing to fetch sw-bridge.js](https://user-images.githubusercontent.com/413984/110184838-2bac5900-7e54-11eb-934c-aa7c01421b3b.png)

If I'm not mistaken, this is the same as [what Jake described back in December](https://twitter.com/jaffathecake/status/1336990427442982913), except I've got and kept the different copy of sw-bridge.js.

I don't mean to complain, nor to ask for bringing back `sw-bridge.d76d5.js` to the repo. I just wonder if there might still be folks having old versions in the cache.

The v1 still works fine and I'm pretty impressed by that!

**Comment by jakearchibald** [comment]
Can you give me the service worker registration details? What's the URL and scope?

**Comment by jakearchibald** [comment]
ping! Happy to take a look at this, but I need some clues

**Comment by myakura** [comment]
oops. I deleted the cache the other day... so sorry for that.
