### ISSUE TITLE
Squoosh CLI incorrectly handles grayscale PNGs

### ISSUE THREAD

**Issue by shuding** [GoogleChromeLabs/squoosh#971]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
Squoosh CLI doubles the image and changed the hue for grayscale PNGs:

<img src="https://user-images.githubusercontent.com/3676859/110683391-ebaff200-8216-11eb-9d99-7454340007f0.png" width="216" height="316">

It can be reproduced with both WebP and OxiPNG, but it works expectedly in the web app. 

**To Reproduce**
1. Download https://imgur.com/wgqaUdn (or https://i.imgur.com/eTgdpzy.png)
2. Run `squoosh-cli --webp auto image.png`
3. See bug

**Expected behavior**
It should not change the image content.

**Version:**
 - OS w/ version: macOS 11.2.2
 - Browser w/ version: n/a
 - Node version: v14.16.0
 - npm version: 6.14.11

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
- Original image 

![test-2](https://user-images.githubusercontent.com/3676859/110684195-cff91b80-8217-11eb-9d1f-0bd1fcf36a69.png)

- Output image from Squoosh

![test-2-output-oxipng](https://user-images.githubusercontent.com/3676859/110684204-d2f40c00-8217-11eb-9fa6-22f38d42782c.png)

**Additional context, screenshots, screencasts**

Here's a full screenshot of commands I ran:

<img width="1368" alt="CleanShot 2021-03-11 at 03 00 39@2x" src="https://user-images.githubusercontent.com/3676859/110683661-3df11300-8217-11eb-9f03-6d7977815562.png">

**Comment by developit** [comment]
As per @RReverser: this is likely caused by the Rust-based PNG decoder, which we don't use in the browser version of Squoosh (matches up with the bug description).  We are configuring a greyscale-to-RGB transform, but it doesn't seem to be functioning as the decoding code expects:
https://github.com/GoogleChromeLabs/squoosh/blob/ef77da9e96db1f58a122717919f74ded9b988d7b/codecs/png/src/lib.rs#L45-L46
