### ISSUE TITLE
UX issue - double click on download triggers 2 save windows

### ISSUE THREAD

**Issue by jonasgoddeeris** [GoogleChromeLabs/squoosh#975]
**Describe the bug**
ANNOYING - UX, FOR HEAVY USERS 

2 SAVE WINDOWS when clicking to fast, please be FORGIVING for this 'user error'

**To Reproduce**

Click on 'SAVE BUTTON - (when "in a flow" and double-tapping) 

**Expected behavior**
Only one "save" window appears

**Version:**
 - OS = MacOSX CATELINA 10.15.7 
 - Version 89.0.4389.82 (Official Build) (x86_64)

**Comment by surma** [comment]
I actually can’t reproduce this at all. When I double-click the Download button I get a single download prompt.

**Comment by kosamari** [comment]
Implementation for this button is <a> with download attribute. Which means it'll download image into disk on every click. 

While I understand that it might be frustrating to see duplicate download, we are avoiding to run custom JS. 
I think <a> is a good solution for us here, and this might be a browser UX issue.
