### ISSUE TITLE
Squoosh site suggests --quant "maxNumColors" parameter, while it should be --quant "numColors"

### ISSUE THREAD

**Issue by davidedc** [GoogleChromeLabs/squoosh#976]
**Describe the bug**
When copying the CLI command from the Squoosh site, it suggests --quant "maxNumColors" parameter, while it should be --quant "_numColors_"

**To Reproduce**
1. Go to Squoosh website, pick a test image
2. Select any compressor option
3. Toggle the "reduce palette" toggle
4. Reduce the palette to, say, 54 colors
5. Copy the CLI command by clicking on the "terminal" icon
6. The copied command contains a --quant option similar to this one: `--quant '{"enabled":true,"zx":0,"maxNumColors":54,"dither":1}'`

**Expected behavior**
The copied command should contain a different parameter in the --quant option: `--quant '{"enabled":true,"zx":0,"numColors":54,"dither":1}'` . I.e. **"maxNumColors" is wrong and it should be "numColors"**

**Version:**
 - OS w/ version: irrelevant
 - Browser w/ version irrelevant
 - Node version: irrelevant, but: 15.5.0
 - npm version: irrelevant, but: 7.3.0
 - Squoosh version: as in website Mar 16th 2021

**Is your issue related to the quality of image compression?**
No

**Additional context, screenshots, screencasts**
N/A

**Comment by Nantris** [comment]
@jakearchibald - confirming this issue. Passing `maxNumColors` has no effect on the output. `numColors` works as expected.

**Comment by klesniewicz** [comment]
This is still erroneous and would be nice to see fixed. Why not just rename/refactor all usage of the string “maxNumColors” in the codebase to “numColors”? As far as I can tell, that would eliminate the passing of incorrect argument names through the CLI and should also generate the correct string on Copy/clipboard. This would, of course, mean that the form field used in the web app would be renamed, but at least it would all be consistent.

cc: @jakearchibald

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
