### ISSUE TITLE
Png decode throws errors.

### ISSUE THREAD

**Issue by gijswijs** [GoogleChromeLabs/squoosh#977]
The following bug report shouldn't get high priority, since I don't see a practical application where this would lead to a problem. But it seems to me that the png decoding provided by the codec doesn't work.

Squoosh prefers to use the builtin decoder of the browser to decode the image. If the browser doesn't support the image format it uses the decoder from its own codecs. You can see this in the code [here](https://github.com/GoogleChromeLabs/squoosh/blob/914bff41c607bcc97f8c09f473961e10a8420686/src/client/lazy-app/Compress/index.tsx#L96)

The client assumes (rightly) that there is always support for png and jpg, so there is not even an option in the code that takes into consideration the decoding of jpeg and png files with an alternative to builtin decoding. Also, the mozjpeg codec doesn't even have a `mozjpeg_dec.js` that would theoretically allow for decoding support. But the png codec does seem to offer decoding support.

I've been playing around with all the decoding offered by the codecs, forcing the web app to use the decoding provided by the codec, but the png decoding doesn't seem to work. In the `dev` branch it seems to throw an error by definition:

```
imports.wbg.__wbindgen_throw = function(arg0, arg1) {
    throw new Error(getStringFromWasm0(arg0, arg1));
};
```
[source](https://github.com/GoogleChromeLabs/squoosh/blob/914bff41c607bcc97f8c09f473961e10a8420686/codecs/png/pkg/squoosh_png.js#L160)

With the `live` branch I get the following error:

```
RuntimeError: unreachable executed
    decode http://127.0.0.1:5500/squoosh/codecs/png/pkg/squoosh_png.js:102
```

So I'm not sure whether decoding (in the browser) using the png codec (and not the builtin decoding) even works. Maybe it is only supposed to work in the context of the node cli client?

**Comment by surma** [comment]
We have decoders for both [PNG](https://github.com/GoogleChromeLabs/squoosh/tree/dev/codecs/png/pkg) and [JPEG](https://github.com/GoogleChromeLabs/squoosh/tree/dev/codecs/mozjpeg/dec) because we need them for the [Squoosh CLI](https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli).

So yes, those are for Node (although I would have thought that the PNG decoder works in the browser, but we have never tested that).
