### ISSUE TITLE
Since python2 is not developed anymore, stable version 1.12.0 maybe needs update?

### ISSUE THREAD

**Issue by tasty0tomato** [GoogleChromeLabs/squoosh#978]
**Is your feature request related to a problem? Please describe.**
The version 1.12.0 use old node-gyp which needs python2, but the branch dev does not need it, so I think maybe it is time to release a new version which do not need python2.

**Describe the solution you'd like**
 maybe it is time to release a new version which do not need python2.

**Comment by surma** [comment]
We don’t use node-gyp or python2, but maybe one of our dependencies does? Not sure.

**Comment by tasty0tomato** [comment]
https://github.com/GoogleChromeLabs/squoosh/blob/4768bc17ba7949e569753680eb5b90853d0c1ac3/package-lock.json#L9686

Sorry, I do not know how to copy the other lines.

**Comment by surma** [comment]
Yes, that’s the <code>package-<strong>lock</strong>.json</code>. But it’s not in the `package.json`, meaning it must be one of our dependencies that depends on node-gyp. Taking a closer look at `package-lock.json`, it seem’s that it’s `node-sass` depending on `node-gyp`. 

The most recent [`node-sass@5`](https://npm.im/node-sass) depends on a newer node-gyp which supports Python 3. W should probably update that, but I am not sure if node-sass had any API changes which might break our CSS stuff.

Wanna open a PR to see if that works?

**Comment by tasty0tomato** [comment]
It seems that the dev branch does not use node-gyp any more, so this is also why I am looking for a new stable release.

By the way, you are really handsome!

**Comment by tomByrer** [comment]
Or, use just the `sass` package which is built on dart & doesn't need any building.  the Dart-Sass is actually the canonical version, node-sass typically lags behind in features, but is slightly faster due to written in C.

I switched VideoJS over to dart-sass since I hated building on Windows.

**Comment by tasty0tomato** [comment]
> Or, use just the `sass` package which is built on dart & doesn't need any building. the Dart-Sass is actually the canonical version, node-sass typically lags behind in features, but is slightly faster due to written in C.
> 
> I switched VideoJS over to dart-sass since I hated building on Windows.

I am so so sorry, I cannot understand because I am not familiar with _Dart-Sass_

**Comment by jakearchibald** [comment]
huh, we're not using sass at all, as far as I'm aware. I wonder what's using it.

**Comment by kosamari** [comment]
Note: This would likely be more of code investigation work. If you like that sort of work :)

**Comment by TimvdLippe** [comment]
`node-gyp` has now been removed from the `package-lock.json` file, so I think this issue has been resolved.

**Comment by tasty0tomato** [comment]
@TimvdLippe  Nice! And watching for the next release.

**Comment by heddn** [comment]
tag `1.12.0` faces the issue with python. Can we get a new tagged release that doesn't require it?

**Comment by tasty0tomato** [comment]
Is now a good time to create a new tagged release?

**Comment by jakearchibald** [comment]
Unfortunately not. The CLI versions of Squoosh are deprecated.
