### ISSUE TITLE
Squoosh CLI incorrectly rotates images on resize

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/squoosh#993]
When resizing an image whose EXIF indicates the image is rotated (a portrait photo from a phone for example) the image is resized incorrectly with the CLI. The CLI resizes along the wrong dimensions with the width and heigh correct, but the image is -90deg away from expected orientation.

**To Reproduce**
1. Take a selfie with a Pixel or any other device that will do a portrait photo (or has rotated EXIF)
2. Run `npx @squoosh/cli --resize '{width: 1224, height: 1632}' --avif auto -s 1224-w [image file name]`
3. Check the output - see it is wrong.

**Expected behavior**

Squoosh CLI should do the same as Squoosh.app. Squoosh.app has the image in the correct orientation when loading, and then when compressed it is correct again.

**Version:**
 - OS w/ version: Mac OS
 - Browser w/ version: Chrome Latest.
 - Node version: 15.8
 - npm version: 7.5.0

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
- Original image 

![PXL_20210330_094617447 PORTRAIT](https://user-images.githubusercontent.com/45510/116127301-91cc9400-a6bf-11eb-9cf5-5e2a5ed67c4c.jpg)

- Output image from Squoosh 
 
![Screenshot 2021-04-26 at 18 38 54](https://user-images.githubusercontent.com/45510/116126719-e15e9000-a6be-11eb-86d8-986ab2aa4504.png)

See attached image image.
* Left - Resized via Squoosh.app - Squoosh.app correctly understands rotation when loading and then resizing the image.
* Middle - Squoosh CLI - image resized to half the size and compressed with AVIF
* Right - Original - EXIF indicates the image has been rotated 90 degrees.

**Comment by surma** [comment]
I did not know that we supported EXIF in the web version! That must be included for free in `createImageBitmap()`. I am convinced that used to _not_ be the case. I’ll see if MozJPEG exposes that data!

**Comment by pascalandy** [comment]
Same here with a picture I took with my iphone :-/

**Comment by Mprogramavimai** [comment]
Any fix?

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
