### ISSUE TITLE
squoosh.app displays incorrect filesize

### ISSUE THREAD

**Issue by tomdav999** [GoogleChromeLabs/squoosh#994]
**Describe the bug**
squoosh displays incorrect filesize, it's very annoying when comparing filesize to other online compressor utilities which display correct filesize

**To Reproduce**
go to: https://squoosh.app/
add a file
download the result
downloaded filesize is different than indicated in browser

**Expected behavior**
downloaded filesize is same as indicated in browser

**Version:**
tested in latest chrome and firefox

**Is your issue related to the quality of image compression?**
no

**Additional context, screenshots, screencasts**
none provided, should be easy to reproduce

**Comment by jakearchibald** [comment]
https://web.archive.org/web/20150324153922/https://pacoup.com/2009/05/26/kb-kb-kib-whats-up-with-that/

If this isn't the issue you're seeing, please provide more data, such as an example.

**Comment by tomdav999** [comment]
Ah yes, my aging eyes can't see the subtle lowercase k which is hard to differentiate from uppercase K in the font that you guys use.  So you are right, but is it really standard practice to display filesizes in kB?  I mean, every Windows computer shows filesizes in KB.  Note your WebP folks compare in KB not kB?

https://developers.google.com/speed/webp/docs/webp_study

Is it really best practice to use kB?  Seems to me every other file compression utility on the web favors KB when displaying size, so makes it hard to compare sizes IMO.  Shrug.

**Comment by tomdav999** [comment]
Just for grins I went to my google drive.  Go figure, filesizes are displayed in KB.  I went to my goggle pixel 3, filesizes are in kB.  Oh the humanity!

Could you guys at least provide the option to display sizes in KB?
