### ISSUE TITLE
[CLI] Add scale support

### ISSUE THREAD

**Issue by spayton** [GoogleChromeLabs/squoosh#998]
I suggest adding a 'scale' command to the cli.

Commonly, users have the need to generate scaled versions of images, by way of an size multiplier.  Often processing image sets into many scaled image sets, through scripts.  In this case the output dimensions are not known, the user just wants x2, x0.5 etc

Currently we have a 'resize' method which requires the target width/height.  It could be used to scale, but we would need to 1st find the image dimensions, then do the maths and supply the result - which is a lot of extra work to squeeze onto the command line.

With a scale method, the squoosh-cli would be more useful in itself, and more similiar to the webapp which also offers scale.

**Comment by WesCook** [comment]
It would definitely make Squoosh more useful for batch processing.  There's many cases where I have a defined width, but not height.  eg. `"width": 1920, "height": "scale"`

**Comment by spayton** [comment]
Yes, that's another need.  So for that I assume you'd want to set the width and the height be calculated to maintain aspect ratio?

**Comment by WesCook** [comment]
Yes, that's right.  It's something I use ImageMagick for right now.  Squoosh probably doesn't want to add all of those advanced features, but scaling seems important if there's a resize function.

**Comment by surma** [comment]
> It would definitely make Squoosh more useful for batch processing. There's many cases where I have a defined width, but not height. eg. "width": 1920, "height": "scale"

This already works today. If you only specify one of `width` or `height`, the other one will be calculated, preserving aspect ratio. Scaling using percentages/factors is something I’d like to add as well, tho.

**Comment by WesCook** [comment]
Okay thanks, that's good to know.  I must have missed it when checking CLI flags.

**Comment by AshreneRoy** [comment]
Hi! This sounds like a good issue to explore. I'd like to pick it up 🙂

**Comment by jakearchibald** [comment]
Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), the CLI and libsquoosh packages are no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
