### ISSUE TITLE
Is there a way to run the build folder without setup a localhost? 

### ISSUE THREAD

**Issue by ngvtuan** [GoogleChromeLabs/squoosh#999]
I have tried to run the build folder by click on the index.html file and I have gotten the FILE_NOT_FOUND errors. Is there any way to run the build folder without setup a local host? 

<img width="1440" alt="Screen Shot 2021-05-04 at 1 59 07 PM" src="https://user-images.githubusercontent.com/10944387/116969754-fcde2200-ace0-11eb-8533-97d7a0ec1405.png">

**Comment by surma** [comment]
No, you need a proper HTTP server. Something as straightforward as `npx superstatic build` should work.

**Comment by jakearchibald** [comment]
After building, `npx serve --config ../serve.json build` will serve with the correct headers
